# ac
# Autogenerated from man page /usr/share/man/man8/ac.8.gz
complete -c ac -s d -d 'Display the connect times in 24 hour chunks'
complete -c ac -s p -d 'Print individual users\' totals'
complete -c ac -s t -d 'Only do accounting logins on certain ttys'
complete -c ac -s w -d 'Read connect time data from wtmp instead of the default file, /var/log/utx'

