# acpidump
# Autogenerated from man page /usr/share/man/man8/acpidump.8.gz
complete -c acpidump -s d -d 'Disassemble the DSDT into ASL using iasl 8 and print the results to stdout'
complete -c acpidump -s t -d 'Dump the contents of the various fixed tables listed above'
complete -c acpidump -s h -d 'Displays usage and exit'
complete -c acpidump -s v -d 'Enable verbose messages'
complete -c acpidump -s f -d 'Load the DSDT from the specified file instead of physical memory'
complete -c acpidump -s o -d 'Store the DSDT data block from physical memory into the specified file'

