# acpiconf
# Autogenerated from man page /usr/share/man/man8/acpiconf.8.gz
complete -c acpiconf -s h -d 'Displays a summary of available options'
complete -c acpiconf -s i -d 'Get design information and current status of the battery specified by its num…'
complete -c acpiconf -s k -d 'Ack or abort a pending suspend request using the argument provided'
complete -c acpiconf -s s -d 'Enters the specified sleep mode'

