# addr2line
# Autogenerated from man page /usr/share/man/man1/addr2line.1.gz
complete -c addr2line -s a -d 'Display the address prior to the line number information'
complete -c addr2line -s b -d 'This option is recognized by addr2line but is ignored'
complete -c addr2line -s e -d 'Use the ELF object specified by argument pathname to translate addresses'
complete -c addr2line -s f -d 'Display function names in addition to file and line number information'
complete -c addr2line -s i -d 'If the address specified belongs to an inlined function, also display the lin…'
complete -c addr2line -s j -d 'The values specified by arguments hexaddress are to be treated as offsets int…'
complete -c addr2line -s p -d 'Display the line number information on one line, in human readable manner'
complete -c addr2line -s s -d 'Display only the base name for each file name'
complete -c addr2line -s C -d 'Demangle C++ names'
complete -c addr2line -s H -d 'Print a help message'
complete -c addr2line -s V -d 'Print a version identifier and exit'

