# adjkerntz
# Autogenerated from man page /usr/share/man/man8/adjkerntz.8.gz
complete -c adjkerntz -s i -d 'This form handles system startups and shutdowns'
complete -c adjkerntz -s a -d 'This form is used to update the local time CMOS clock and kernel machdep'

