# apmd
# Autogenerated from man page /usr/share/man/man8/apmd.8.gz
complete -c apmd -s d -d 'Starts in debug mode'
complete -c apmd -s f -d 'Specifies a different configuration file file to be used in place of the defa…'
complete -c apmd -s s -d 'Causes apmd to simulate a POWERSTATECHANGE event when a power state change is…'
complete -c apmd -s v -d 'Verbose mode'

