# apply
# Autogenerated from man page /usr/share/man/man1/apply.1.gz
complete -c apply -s a -d 'The use of the character % as a magic character may be changed with the a opt…'
complete -c apply -s d -d 'Display the commands that would have been executed, but do not actually execu…'

