# at
# Autogenerated from man page /usr/share/man/man1/at.1.gz
complete -c at -s q -d 'Use the specified queue'
complete -c at -s m -d 'Send mail to the user when the job has completed even if there was no output'
complete -c at -s f -d 'Read the job from file rather than standard input'
complete -c at -s l -d 'With no arguments, list all jobs for the invoking user'
complete -c at -s d -d 'Is an alias for at atrm (this option is deprecated; use r instead)'
complete -c at -s b -d 'Is an alias for at batch'
complete -c at -s v -d 'For at atq, shows completed but not yet deleted jobs in the queue; otherwise …'
complete -c at -s c -d 'Cat the jobs listed on the command line to standard output'
complete -c at -s r -d 'Remove the specified jobs'
complete -c at -s t -d 'Specify the job time using the \\*[Px] time format'

