# atf-test-program
# Autogenerated from man page /usr/share/man/man1/atf-test-program.1.gz
complete -c atf-test-program -s l -d 'Lists available test cases alongside a brief description for each of them'
complete -c atf-test-program -s r -d 'Specifies the file that will receive the test case result'
complete -c atf-test-program -s s -d 'The path to the directory where the test program is located'
complete -c atf-test-program -s v -d 'Sets the configuration variable var to the value value.  El SEE ALSO kyua 1'

