# ath3kfw
# Autogenerated from man page /usr/share/man/man8/ath3kfw.8.gz
complete -c ath3kfw -s D -d 'Enable verbose debugging'
complete -c ath3kfw -s d -d 'Specify ugen 4 device name.  I Enable informational debugging'
complete -c ath3kfw -s f -d 'Specify the directory containing the firmware files to search and upload'
complete -c ath3kfw -s h -d 'Display usage message and exit'

