# atq
# Autogenerated from man page /usr/share/man/man1/atq.1.gz
complete -c atq -s q -d 'Use the specified queue'
complete -c atq -s m -d 'Send mail to the user when the job has completed even if there was no output'
complete -c atq -s f -d 'Read the job from file rather than standard input'
complete -c atq -s l -d 'With no arguments, list all jobs for the invoking user'
complete -c atq -s d -d 'Is an alias for atq atrm (this option is deprecated; use r instead)'
complete -c atq -s b -d 'Is an alias for atq batch'
complete -c atq -s v -d 'For atq atq, shows completed but not yet deleted jobs in the queue; otherwise…'
complete -c atq -s c -d 'Cat the jobs listed on the command line to standard output'
complete -c atq -s r -d 'Remove the specified jobs'
complete -c atq -s t -d 'Specify the job time using the \\*[Px] time format'

