# atrm
# Autogenerated from man page /usr/share/man/man1/atrm.1.gz
complete -c atrm -s q -d 'Use the specified queue'
complete -c atrm -s m -d 'Send mail to the user when the job has completed even if there was no output'
complete -c atrm -s f -d 'Read the job from file rather than standard input'
complete -c atrm -s l -d 'With no arguments, list all jobs for the invoking user'
complete -c atrm -s d -d 'Is an alias for atrm atrm (this option is deprecated; use r instead)'
complete -c atrm -s b -d 'Is an alias for atrm batch'
complete -c atrm -s v -d 'For atrm atq, shows completed but not yet deleted jobs in the queue; otherwis…'
complete -c atrm -s c -d 'Cat the jobs listed on the command line to standard output'
complete -c atrm -s r -d 'Remove the specified jobs'
complete -c atrm -s t -d 'Specify the job time using the \\*[Px] time format'

