# audit
# Autogenerated from man page /usr/share/man/man8/audit.8.gz
complete -c audit -s e -d 'Forces the audit system to immediately remove audit log files that meet the e…'
complete -c audit -s i -d 'Initializes and starts auditing'
complete -c audit -s n -d 'Forces the audit system to close the existing audit log file and rotate to a …'
complete -c audit -s s -d 'Specifies that the audit system should [re]synchronize its configuration from…'
complete -c audit -s t -d 'Specifies that the audit system should terminate'

