# auditdistd
# Autogenerated from man page /usr/share/man/man8/auditdistd.8.gz
complete -c auditdistd -s c -d 'Specify an alternative location of the configuration file'
complete -c auditdistd -s d -d 'Print or log debugging information'
complete -c auditdistd -s F -d 'Start the auditdistd daemon in the foreground'
complete -c auditdistd -s h -d 'Print the auditdistd usage message'
complete -c auditdistd -s l -d 'Start in a launchd-friendly mode, ie.  do not use daemon 3'
complete -c auditdistd -s P -d 'Specify an alternative location of a file where main process PID will be stor…'

