# autounmountd
# Autogenerated from man page /usr/share/man/man8/autounmountd.8.gz
complete -c autounmountd -s d -d 'Debug mode: increase verbosity and do not daemonize'
complete -c autounmountd -s r -d 'Number of seconds to wait before trying to unmount an expired filesystem afte…'
complete -c autounmountd -s t -d 'Number of seconds to wait before trying to unmount a filesystem'
complete -c autounmountd -s v -d 'Increase verbosity'

