# automountd
# Autogenerated from man page /usr/share/man/man8/automountd.8.gz
complete -c automountd -s D -d 'Define a variable'
complete -c automountd -s i -d 'For indirect mounts, only create subdirectories if there are no wildcard entr…'
complete -c automountd -s m -d 'Limit the number of forked automountd processes, and thus the number of mount…'
complete -c automountd -s d -d 'Debug mode: increase verbosity and do not daemonize'
complete -c automountd -s o -d 'Specify mount options'
complete -c automountd -s v -d 'Increase verbosity'

