# automount
# Autogenerated from man page /usr/share/man/man8/automount.8.gz
complete -c automount -s D -d 'Define a variable.  It is only useful with L'
complete -c automount -s L -d 'Do not mount or unmount anything'
complete -c automount -s c -d 'Flush caches, discarding possibly stale information obtained from maps and di…'
complete -c automount -s f -d 'Force unmount, to be used with u'
complete -c automount -s o -d 'Specify mount options to be used along with the ones specified in the maps'
complete -c automount -s u -d 'Try to unmount filesystems mounted by automountd 8'
complete -c automount -s v -d 'Increase verbosity'

