# b64encode
# Autogenerated from man page /usr/share/man/man1/b64encode.1.gz
complete -c b64encode -s m -d 'Use the Base64 method of encoding, rather than the traditional b64encode uuen…'
complete -c b64encode -s r -d 'Produce raw output by excluding the initial and final framing lines'
complete -c b64encode -s o -d 'Output to output_file instead of standard output'
complete -c b64encode -s c -d 'Decode more than one uuencoded file from file if possible'
complete -c b64encode -s i -d 'Do not overwrite files'
complete -c b64encode -s p -d 'Decode file and write output to standard output'
complete -c b64encode -s s -d 'Do not strip output pathname to base filename'
complete -c b64encode -s w -d 'Wrap encoded output after column'
complete -c b64encode -s u -d Decode

