# backlight
# Autogenerated from man page /usr/share/man/man8/backlight.8.gz
complete -c backlight -s f -d 'Device to operate on.  If not specified, /dev/backlight/backlight0 is used'
complete -c backlight -s i -d 'Query information about the backlight (name, type)'
complete -c backlight -s q -d 'When querying the brightness level only print the value'

