# banner
# Autogenerated from man page /usr/share/man/man6/banner.6.gz
complete -c banner -s d -d 'Enable debug'
complete -c banner -s t -d 'Enable trace'
complete -c banner -s w -d 'Change the output from a width of 132 to width, suitable for a narrow terminal'

