# base64
# Autogenerated from man page /usr/share/man/man1/base64.1.gz
complete -c base64 -s m -d 'Use the Base64 method of encoding, rather than the traditional base64 uuencod…'
complete -c base64 -s r -d 'Produce raw output by excluding the initial and final framing lines'
complete -c base64 -s o -d 'Output to output_file instead of standard output'
complete -c base64 -s c -d 'Decode more than one uuencoded file from file if possible'
complete -c base64 -s i -d 'Do not overwrite files'
complete -c base64 -s p -d 'Decode file and write output to standard output'
complete -c base64 -s s -d 'Do not strip output pathname to base filename'
complete -c base64 -s w -d 'Wrap encoded output after column'
complete -c base64 -s u -d Decode

