# batch
# Autogenerated from man page /usr/share/man/man1/batch.1.gz
complete -c batch -s q -d 'Use the specified queue'
complete -c batch -s m -d 'Send mail to the user when the job has completed even if there was no output'
complete -c batch -s f -d 'Read the job from file rather than standard input'
complete -c batch -s l -d 'With no arguments, list all jobs for the invoking user'
complete -c batch -s d -d 'Is an alias for batch atrm (this option is deprecated; use r instead)'
complete -c batch -s b -d 'Is an alias for batch batch'
complete -c batch -s v -d 'For batch atq, shows completed but not yet deleted jobs in the queue; otherwi…'
complete -c batch -s c -d 'Cat the jobs listed on the command line to standard output'
complete -c batch -s r -d 'Remove the specified jobs'
complete -c batch -s t -d 'Specify the job time using the \\*[Px] time format'

