# bc
# Autogenerated from man page /usr/share/man/man1/bc.1.gz
complete -c bc -s C -l no-digit-clamp -d 'Disables clamping of digits greater than or equal to the current ibase when p…'
complete -c bc -s c -l digit-clamp -d 'Enables clamping of digits greater than or equal to the current ibase when pa…'
complete -c bc -s E -l seed -d 'Sets the builtin variable seed to the value seed assuming that seed is in bas…'
complete -c bc -s e -l expression -d 'Evaluates expr'
complete -c bc -s f -l file -d 'BC_ENV_ARGS.  However, if any other -e, --expression,'
complete -c bc -o f- -d exit
complete -c bc -s g -l global-stacks -d 'Turns the globals ibase, obase, scale, and seed into stacks'
complete -c bc -s h -l help -d 'Prints a usage message and exits'
complete -c bc -s I -l ibase -d 'Sets the builtin variable ibase to the value ibase assuming that ibase is in …'
complete -c bc -s i -l interactive -d 'Forces interactive mode.  (See the INTERACTIVE MODE section'
complete -c bc -s L -l no-line-length -d 'Disables line length checking and prints numbers without backslashes and newl…'
complete -c bc -s l -l mathlib -d 'Sets scale (see the SYNTAX section) to 20 and loads the included math library…'
complete -c bc -s O -l obase -d 'Sets the builtin variable obase to the value obase assuming that obase is in …'
complete -c bc -s P -l no-prompt -d 'Disables the prompt in TTY mode.  (The prompt is only enabled in TTY mode'
complete -c bc -s q -l quiet -d 'This option is for compatibility with the GNU bc(1) (https://www. gnu'
complete -c bc -s v -s V -l version -d 'unless the BC_BANNER environment variable is set and contains a non-zero inte…'
complete -c bc -s R -l no-read-prompt -d 'Disables the read prompt in TTY mode'
complete -c bc -s r -l redefine -d 'Redefines keyword in order to allow it to be used as a function, variable, or…'
complete -c bc -s S -l scale -d 'Sets the builtin variable scale to the value scale assuming that scale is in …'
complete -c bc -s s -l standard -d 'Process exactly the language defined by the standard (see the STANDARDS secti…'
complete -c bc -s w -l warn -d 'Like -s and --standard, except that warnings (and not errors) are printed for…'
complete -c bc -s z -l leading-zeroes -d 'Makes bc(1) print all numbers greater than -1 and less than 1, and not equal …'
complete -c bc -o C/--no-digit-clamp -d 'OPTIONS section), the existence and setting of the BC_DIGIT_CLAMP environment…'
complete -c bc -o h/--help
complete -c bc -o s/--standard -o w/--warn -d 'options are given since they are not part of the library defined by the stand…'

