# bcmfw
# Autogenerated from man page /usr/share/man/man8/bcmfw.8.gz
complete -c bcmfw -s f -d 'Specify firmware file name for download'
complete -c bcmfw -s h -d 'Display usage message and exit'
complete -c bcmfw -s m -d 'Specify mini-driver file name for download'
complete -c bcmfw -s n -d 'Specify device name.  El FILES -tag -width "'

