# bectl
# Autogenerated from man page /usr/share/man/man8/bectl.8.gz
complete -c bectl -s a -d 'Display all datasets'
complete -c bectl -s D -d 'Display the full space usage for each boot environment, assuming all other bo…'
complete -c bectl -s H -d 'Used for scripting'
complete -c bectl -s s -d 'Display all snapshots as well'
complete -c bectl -s c -d 'Sort boot environments by the given ZFS dataset property'
complete -c bectl -s C -d 'Same as the c option, but displays in descending order'

