# beep
# Autogenerated from man page /usr/share/man/man1/beep.1.gz
complete -c beep -s F -d 'Sets the center frequency of the beep in Hz.  The default is 440 Hz '
complete -c beep -s D -d 'Sets the duration of the beep in milliseconds.  The default is 150 ms '
complete -c beep -s d -d 'Sets the soundcard to use.  The default is /dev/dsp '
complete -c beep -s r -d 'Sets the soundcard samplerate in Hz.  The default is 48000 Hz'
complete -c beep -s g -d 'Sets the waveform gain, between 0 and 100 inclusively.  The default is 75'
complete -c beep -s B -d 'Runs the beep utility in the background'
complete -c beep -s h -d 'Display summary of options'

