# bhyveload
# Autogenerated from man page /usr/share/man/man8/bhyveload.8.gz
complete -c bhyveload -s c -d 'cons-dev is a tty 4 device to use for bhyveload terminal I/O'
complete -c bhyveload -s d -d 'The disk-path is the pathname of the guest\'s boot disk image'
complete -c bhyveload -s e -d 'Set the Fx loader environment variable name to value'
complete -c bhyveload -s h -d 'The host-path is the directory at the top of the guest\'s boot filesystem'
complete -c bhyveload -s l -d 'Specify a different OS loader.  By default bhyveload will use /boot/userboot'
complete -c bhyveload -s m -d 'memsize is the amount of memory allocated to the guest'
complete -c bhyveload -s C -d 'Include guest memory in the core file when bhyveload dumps core'
complete -c bhyveload -s S -d 'Wire guest memory'

