# bhyvectl
# Autogenerated from man page /usr/share/man/man8/bhyvectl.8.gz
complete -c bhyvectl -l vm -d 'Operate on the virtual machine <vmname>'
complete -c bhyvectl -l create -d 'Create the specified VM'
complete -c bhyvectl -l destroy -d 'Destroy the specified VM'
complete -c bhyvectl -l get-stats -d 'Retrieve statistics for the specified VM'
complete -c bhyvectl -l inject-nmi -d 'Inject a non-maskable interrupt (NMI) into the VM'
complete -c bhyvectl -l force-reset -d 'Force the VM to reset'
complete -c bhyvectl -l force-poweroff -d 'Force the VM to power off'
complete -c bhyvectl -l checkpoint -d 'Save a snapshot of a virtual machine'
complete -c bhyvectl -l suspend -d 'Save a snapshot of a virtual machine similar to -checkpoint'

