# bintrans
# Autogenerated from man page /usr/share/man/man1/bintrans.1.gz
complete -c bintrans -s m -d 'Use the Base64 method of encoding, rather than the traditional bintrans uuenc…'
complete -c bintrans -s r -d 'Produce raw output by excluding the initial and final framing lines'
complete -c bintrans -s o -d 'Output to output_file instead of standard output'
complete -c bintrans -s c -d 'Decode more than one uuencoded file from file if possible'
complete -c bintrans -s i -d 'Do not overwrite files'
complete -c bintrans -s p -d 'Decode file and write output to standard output'
complete -c bintrans -s s -d 'Do not strip output pathname to base filename'
complete -c bintrans -s w -d 'Wrap encoded output after column'
complete -c bintrans -s u -d Decode

