# blacklistctl
# Autogenerated from man page /usr/share/man/man8/blacklistctl.8.gz
complete -c blacklistctl -s a -d 'Show all database entries, by default it shows only the embryonic ones'
complete -c blacklistctl -s b -d 'Show only the blocked entries'
complete -c blacklistctl -s d -d 'Increase debugging level'
complete -c blacklistctl -s n -d 'Don\'t display a header'
complete -c blacklistctl -s r -d 'Show the remaining blocked time instead of the last activity time'
complete -c blacklistctl -s w -d 'Normally the width of addresses is good for IPv4, the w flag, makes the displ…'

