# blacklistd
# Autogenerated from man page /usr/share/man/man8/blacklistd.8.gz
complete -c blacklistd -s C -d 'Use controlprog to communicate with the packet filter, usually /usr/libexec/b…'
complete -c blacklistd -s c -d 'The name of the configuration file to read, usually /etc/blacklistd. conf'
complete -c blacklistd -s D -d 'The Berkeley DB file where blacklistd stores its state, usually /var/db/black…'
complete -c blacklistd -s d -d 'Normally, blacklistd disassociates itself from the terminal unless the d flag…'
complete -c blacklistd -s f -d 'Truncate the state database and flush all the rules named rulename are delete…'
complete -c blacklistd -s P -d 'A file containing a list of pathnames, one per line that blacklistd will crea…'
complete -c blacklistd -s R -d 'Specify the default rule name for the packet filter rules, usually blacklistd'
complete -c blacklistd -s r -d 'Re-read the firewall rules from the internal database, then remove and re-add…'
complete -c blacklistd -s s -d 'Add sockpath to the list of Unix sockets blacklistd listens to'
complete -c blacklistd -s t -d 'The interval in seconds blacklistd polls the state file to update the rules'
complete -c blacklistd -s v -d 'Cause blacklistd to print diagnostic messages to stdout instead of syslogd 8'

