# bootptest
# Autogenerated from man page /usr/share/man/man8/bootptest.8.gz
complete -c bootptest -s f -d 'Fill in the boot file field of the request with bootfile'
complete -c bootptest -s h -d 'Use the hardware (Ethernet) address to identify the client'
complete -c bootptest -s m -d 'Initialize the first word of the vendor options field with magic_number'

