# bootpd
# Autogenerated from man page /usr/share/man/man8/bootpd.8.gz
complete -c bootpd -s a -d 'Skip ARP table modifications'
complete -c bootpd -s t -d 'Specify the timeout value (in minutes) that a bootpd or bootpd bootpgw proces…'
complete -c bootpd -s d -d 'Set the debug-level variable that controls the amount of debugging messages g…'
complete -c bootpd -s c -d 'Set the current directory used by bootpd while checking the existence and siz…'
complete -c bootpd -s h -d 'Specify the hostname corresponding to the IP address to listen on'
complete -c bootpd -s i -d 'Force inetd mode'
complete -c bootpd -s s -d 'Force standalone mode'

