# boot
# Autogenerated from man page /usr/share/man/man8/boot.8.gz
complete -c boot -s a -d 'during kernel initialization, ask for the device to mount as the root file sy…'
complete -c boot -s C -d 'try to mount root file system from a CD-ROM'
complete -c boot -s c -d 'this flag is currently a no-op'
complete -c boot -s D -d 'boot with the dual console configuration'
complete -c boot -s d -d 'enter the DDB kernel debugger (see ddb 4 ) as early as possible in kernel ini…'
complete -c boot -s g -d 'use the GDB remote debugging protocol'
complete -c boot -s h -d 'force the serial console'
complete -c boot -s m -d 'mute the console to suppress all kernel console input and output during the b…'
complete -c boot -s n -d 'ignore key press to interrupt boot before loader 8 is invoked'
complete -c boot -s P -d 'probe the keyboard'
complete -c boot -s p -d 'pause after each attached device during the device probing phase'
complete -c boot -s q -d 'be quiet, do not write anything to the console unless automatic boot fails or…'
complete -c boot -s r -d 'use the statically configured default for the device containing the root file…'
complete -c boot -s s -d 'boot into single-user mode; if the console is marked as insecure (see ttys 5 …'
complete -c boot -s S -d 'set the speed of the serial console to speed'
complete -c boot -s v -d 'be verbose during device probing (and later).  El El El Pp Use the /boot'

