# boot0cfg
# Autogenerated from man page /usr/share/man/man8/boot0cfg.8.gz
complete -c boot0cfg -s B -d 'Install the boot0 boot manager'
complete -c boot0cfg -s b -d 'Specify which boot0 image to use'
complete -c boot0cfg -s d -d 'Specify the drive number used by the PC BIOS in referencing the drive which c…'
complete -c boot0cfg -s e -d 'Set the character to be printed in case of input error'
complete -c boot0cfg -s f -d 'Specify that a backup copy of the preexisting MBR should be written to file'
complete -c boot0cfg -s i -d 'Specifies a volume-id (in the form XXXX-XXXX) to be saved at location 0x1b8 i…'
complete -c boot0cfg -s m -d 'Specify slices to be enabled/disabled, where mask is an integer between 0 (no…'
complete -c boot0cfg -s o -d 'A comma-separated string of any of the following options may be specified (wi…'
complete -c boot0cfg -s s -d 'Set the default boot selection to slice'
complete -c boot0cfg -s t -d 'Set the timeout value to ticks.  (There are approximately 18'
complete -c boot0cfg -s v -d 'Verbose: display information about the slices defined, etc'

