# bootparamd
# Autogenerated from man page /usr/share/man/man8/bootparamd.8.gz
complete -c bootparamd -s d -d 'Display the debugging information'
complete -c bootparamd -s s -d 'Log the debugging information with syslog 3'
complete -c bootparamd -s r -d 'The default router (a machine or an IP-address)'
complete -c bootparamd -s f -d 'The file to use as boot parameter file instead of /etc/bootparams'

