# bootpef
# Autogenerated from man page /usr/share/man/man8/bootpef.8.gz
complete -c bootpef -s c -d 'Sets the current directory used by bootpef while creating extension files'
complete -c bootpef -s d -d 'Sets the debug\\-level variable that controls the amount of debugging messages…'
complete -c bootpef -s f -d 'Set the name of the config file that specifies the option data to be sent to …'

