# brandelf
# Autogenerated from man page /usr/share/man/man1/brandelf.1.gz
complete -c brandelf -s f -d 'Forces branding with the supplied ELF ABI number'
complete -c brandelf -s l -d 'Writes the list of all known ELF types to the standard error'
complete -c brandelf -s v -d 'Turns on verbose output'
complete -c brandelf -s t -d 'Brands the given ELF binaries to be of the string ABI type'

