# bsdconfig
# Autogenerated from man page /usr/share/man/man8/bsdconfig.8.gz
complete -c bsdconfig -s d -d 'Provide lots of debugging info on standard-out when running'
complete -c bsdconfig -s D -d 'Send debugging info to file'
complete -c bsdconfig -s f -d 'Load file as script and then exit'
complete -c bsdconfig -s h -d 'Print usage statement and exit'
complete -c bsdconfig -s S -d 'Secure X11 mode implies Fl X'
complete -c bsdconfig -s X -d 'Use Xdialog 1 Pq Pa ports/x11/xdialog in place of dialog 1'

