# bsnmpd
# Autogenerated from man page /usr/share/man/man1/bsnmpd.1.gz
complete -c bsnmpd -s d -d 'Do not daemonize.  Used for debugging'
complete -c bsnmpd -s h -d 'Print a short usage message'
complete -c bsnmpd -s c -d 'Use file as configuration file instead of the standard one'
complete -c bsnmpd -s D -d 'Debugging options are specified with a o flag followed by a comma separated s…'
complete -c bsnmpd -s e -d 'Specify an alternate file where the agent\'s engine id and number of boots are…'
complete -c bsnmpd -s I -d 'Specify a colon separated list of directories to search for configuration inc…'
complete -c bsnmpd -s l -d 'Use prefix as the default basename for the pid and the configuration files'
complete -c bsnmpd -s m -d 'Define a configuration variable'
complete -c bsnmpd -s p -d 'Specify an alternate pid file instead of the default one'

