# bthidd
# Autogenerated from man page /usr/share/man/man8/bthidd.8.gz
complete -c bthidd -s a -d 'Specify the local address to listen on'
complete -c bthidd -s c -d 'Specify path to the configuration file'
complete -c bthidd -s d -d 'Do not detach from the controlling terminal, i. e. , run in foreground'
complete -c bthidd -s H -d 'Specify path to the known HIDs file.  The default path is /var/db/bthidd'
complete -c bthidd -s h -d 'Display usage message and exit'
complete -c bthidd -s p -d 'Specify path to the PID file.  The default path is /var/run/bthidd. pid'
complete -c bthidd -s t -d 'Specify client rescan interval in seconds'
complete -c bthidd -s u -d 'Enable support for input event device protocol'

