# bthost
# Autogenerated from man page /usr/share/man/man1/bthost.1.gz
complete -c bthost -s b -d 'Produce brief output'
complete -c bthost -s h -d 'Display usage message and exit'
complete -c bthost -s p -d 'Activate protocol mode'

