# btpand
# Autogenerated from man page /usr/share/man/man8/btpand.8.gz
complete -c btpand -s a -d 'In client mode, address of remote server'
complete -c btpand -s c -d 'In server mode, specify path to the sdpd 8 control socket'
complete -c btpand -s d -d 'Restrict connections to the local device'
complete -c btpand -s i -d 'btpand uses the tap 4 driver to create a new network interface for use'
complete -c btpand -s l -d 'In server mode, limit the number of simultaneous connections'
complete -c btpand -s m -d 'Set L2CAP connection link mode'
complete -c btpand -s p -d 'Use an alternative L2CAP Protocol/Service Multiplexer PSM for server mode or …'
complete -c btpand -s s -d 'Name of service to provide or connect to, the following services are recognis…'
complete -c btpand -s S -d 'As per s except that btpand will not use SDP services for connection setup'

