# btsockstat
# Autogenerated from man page /usr/share/man/man1/btsockstat.1.gz
complete -c btsockstat -s h -d 'Display usage message and exit'
complete -c btsockstat -s M -d 'Extract values associated with the name list from the specified core instead …'
complete -c btsockstat -s n -d 'Show Bluetooth addresses as numbers'
complete -c btsockstat -s p -d 'Display a list of active sockets (protocol control blocks) for each specified…'
complete -c btsockstat -s r -d 'Display a list of active routing entries (if any) for specified protocol'

