# btxld
# Autogenerated from man page /usr/share/man/man8/btxld.8.gz
complete -c btxld -s q -d 'Quiet: inhibit warnings'
complete -c btxld -s v -d 'Verbose: display information about the files processed'
complete -c btxld -s b -d 'Specify the BTX kernel to be bound with the client'
complete -c btxld -s E -d 'Set the client entry point'
complete -c btxld -s e -d 'Set the BTX loader entry point'
complete -c btxld -s f -d 'Specify the output format, where format is one of bin, aout, or elf'
complete -c btxld -s l -d 'Specify the BTX loader to be bound with the client'
complete -c btxld -s o -d 'Name the output file.  The default is a. out'
complete -c btxld -s P -d 'Specify the first page of the client\'s segment to be marked present, where pa…'
complete -c btxld -s W -d 'Specify the first page of the client\'s segment to be marked writable, where p…'

