# c99
# Autogenerated from man page /usr/share/man/man1/c99.1.gz
complete -c c99 -s c -d 'Suppress the link-edit phase of the compilation, and do not remove any object…'
complete -c c99 -s D -d 'Define name as if by a C-language #define directive'
complete -c c99 -s E -d 'Copy C-language source files to the standard output, expanding all preprocess…'
complete -c c99 -s g -d 'Produce symbolic information in the object or executable files'
complete -c c99 -s I -d 'Change the algorithm for searching for headers whose names are not absolute p…'
complete -c c99 -s L -d 'Change the algorithm of searching for the libraries named in the l objects to…'
complete -c c99 -s o -d 'Use the pathname outfile, instead of the default a'
complete -c c99 -s O -d 'If optlevel is zero, disable all optimizations'
complete -c c99 -s s -d 'Produce object and/or executable files from which symbolic and other informat…'
complete -c c99 -s U -d 'Remove any initial definition of name'
complete -c c99 -s l -d 'Search the library named lib Ns Ar library Ns Pa . a'

