# CA.pl
# Autogenerated from man page /usr/share/openssl/man/man1/CA.pl.1.gz
complete -c 'CA.pl' -s '?' -s h -o help -d 'Prints a usage message'
complete -c 'CA.pl' -o newcert -d 'Creates a new self signed certificate'
complete -c 'CA.pl' -o newreq -d 'Creates a new certificate request'
complete -c 'CA.pl' -o newreq-nodes -d 'Is like -newreq except that the private key will not be encrypted'
complete -c 'CA.pl' -o newca -d 'Creates a new \\s-1CA\\s0 hierarchy for use with the ca program (or the -signce…'
complete -c 'CA.pl' -o pkcs12 -d 'Create a PKCS#12 file containing the user certificate, private key and \\s-1CA…'
complete -c 'CA.pl' -o sign -o signcert -o xsign -d 'Calls the openssl-ca\\|(1) command to sign a certificate request'
complete -c 'CA.pl' -o signCA -d 'This option is the same as the -sign option except it uses the configuration …'
complete -c 'CA.pl' -o crl -d 'Generate a \\s-1CRL. \\s0 Executes openssl-ca\\|(1)'
complete -c 'CA.pl' -o revoke -d 'Revoke the certificate contained in the specified certfile'
complete -c 'CA.pl' -o verify -d 'Verifies certificates against the \\s-1CA\\s0 certificate for demoCA'

