# calendar
# Autogenerated from man page /usr/share/man/man1/calendar.1.gz
complete -c calendar -s A -d 'Print lines from today and the next num days (forward, future)'
complete -c calendar -s a -d 'Process the ``calendar\'\' files for users found in /etc/passwd and mail the re…'
complete -c calendar -s B -d 'Print lines from today and the previous num days (backward, past)'
complete -c calendar -s D -d 'Print UTC offset, longitude and moon or sun information'
complete -c calendar -s d -d 'Debug option: print current date information'
complete -c calendar -s F -d 'Specify which day of the week is ``Friday\'\' (the day before the weekend begin…'
complete -c calendar -s f -d 'Use calendarfile as the default calendar file'
complete -c calendar -s l -d 'Perform lunar and solar calculations from this longitude'
complete -c calendar -s U -d 'Perform lunar and solar calculations from this UTC offset'
complete -c calendar -s W -d 'Print lines from today and the next num days (forward, future)'

