# camdd
# Autogenerated from man page /usr/share/man/man8/camdd.8.gz
complete -c camdd -s i -d 'Specify the input and output device or file.  Both i and o must be specified'
complete -c camdd -s C -d 'Specify the retry count for commands sent via the asynchronous pass 4 interfa…'
complete -c camdd -s E -d 'Enable kernel error recovery for the pass 4 driver'
complete -c camdd -s m -d 'Specify the maximum amount of data to be transferred'
complete -c camdd -s t -d 'Specify the command timeout in seconds to use for commands sent via the pass …'
complete -c camdd -s v -d 'Enable verbose reporting of errors'
complete -c camdd -s h -d 'Display the camdd usage message'

