# cap_mkdb
# Autogenerated from man page /usr/share/man/man1/cap_mkdb.1.gz
complete -c cap_mkdb -s b -d 'Use big-endian byte order for database metadata'
complete -c cap_mkdb -s f -d 'Specify a different database basename'
complete -c cap_mkdb -s l -d 'Use little-endian byte order for database metadata'
complete -c cap_mkdb -s v -d 'Print out the number of capability records in the database'

