# cat
# Autogenerated from man page /usr/share/man/man1/cat.1.gz
complete -c cat -s b -d 'Number the non-blank output lines, starting at 1'
complete -c cat -s e -d 'Display non-printing characters (see the v option), and display a dollar sign…'
complete -c cat -s l -d 'Set an exclusive advisory lock on the standard output file descriptor'
complete -c cat -s n -d 'Number the output lines, starting at 1'
complete -c cat -s s -d 'Squeeze multiple adjacent empty lines, causing the output to be single spaced'
complete -c cat -s t -d 'Display non-printing characters (see the v option), and display tab character…'
complete -c cat -s u -d 'Disable output buffering'
complete -c cat -s v -d 'Display non-printing characters so they are visible'

