# ccdconfig
# Autogenerated from man page /usr/share/man/man8/ccdconfig.8.gz
complete -c ccdconfig -s c -d 'Configure a ccd.  This is the default behavior of ccdconfig'
complete -c ccdconfig -s C -d 'Configure all ccd devices listed in the ccd configuration file'
complete -c ccdconfig -s f -d 'When configuring or unconfiguring all devices, read the file config_file inst…'
complete -c ccdconfig -s g -d 'Dump the current ccd configuration in a format suitable for use as the ccd co…'
complete -c ccdconfig -s u -d 'Unconfigure a ccd'
complete -c ccdconfig -s U -d 'Unconfigure all ccd devices listed the ccd configuration file'
complete -c ccdconfig -s v -d 'Cause ccdconfig to be verbose'

