# cdcontrol
# Autogenerated from man page /usr/share/man/man1/cdcontrol.1.gz
complete -c cdcontrol -s s -d 'Silent mode.  Do not print table headers and human readable comments'
complete -c cdcontrol -s v -d 'Verbose mode.  Print as much information as possible'
complete -c cdcontrol -s f -d 'Specify a device, such as /dev/cd0'

