# certctl
# Autogenerated from man page /usr/share/man/man8/certctl.8.gz
complete -c certctl -s D -d 'Specify the DESTDIR (overriding values from the environment)'
complete -c certctl -s d -d 'Specify the DISTBASE (overriding values from the environment)'
complete -c certctl -s M -d 'Specify the path of the METALOG file (default: $DESTDIR/METALOG)'
complete -c certctl -s n -d 'No-Op mode, do not actually perform any actions'
complete -c certctl -s v -d 'Be verbose, print details about actions before performing them'
complete -c certctl -s U -d 'Unprivileged mode, do not change the ownership of created links'

