# chflags
# Autogenerated from man page /usr/share/man/man1/chflags.1.gz
complete -c chflags -s f -d 'Do not display a diagnostic message if chflags could not modify the flags for…'
complete -c chflags -s H -d 'If the R option is specified, symbolic links on the command line are followed…'
complete -c chflags -s h -d 'If the file is a symbolic link, change the file flags of the link itself rath…'
complete -c chflags -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c chflags -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c chflags -s R -d 'Change the file flags of the file hierarchies rooted in the files, instead of…'
complete -c chflags -s v -d 'Cause chflags to be verbose, showing filenames as the flags are modified'
complete -c chflags -s x -d 'Do not cross mount points'

