# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
complete -c chfn -s a -d 'The super-user is allowed to directly supply a user database entry, in the fo…'
complete -c chfn -s e -d 'Change the account expire time'
complete -c chfn -s p -d 'The super-user is allowed to directly supply an encrypted password field, in …'
complete -c chfn -s s -d 'Attempt to change the user\'s shell to newshell'
complete -c chfn -s d -d 'Specify a particular NIS domain'
complete -c chfn -s h -d 'Specify the name or address of an NIS server to query'
complete -c chfn -s l -d 'Force chfn to modify the local copy of a user\'s password information in the e…'
complete -c chfn -s o -d 'Force the use of RPC-based updates when communicating with rpc'
complete -c chfn -s y -d 'Opposite effect of l'

