# chio
# Autogenerated from man page /usr/share/man/man1/chio.1.gz
complete -c chio -s f -d 'Use the device changer rather than the default device /dev/ch0'
complete -c chio -s v -d 'Print the primary volume tag for each loaded medium, if any'
complete -c chio -s V -d 'Print the alternate volume tag for each loaded medium, if any'
complete -c chio -s s -d 'Print the additional sense code and additional sense code qualifier for each …'
complete -c chio -s S -d 'Print the element source address for each element'
complete -c chio -s b -d 'Print SCSI bus information for each element'
complete -c chio -s I -d 'Print the internal element addresses for each element'
complete -c chio -s a -d 'Print all additional information (as in vVsSba )'

