# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1.gz
complete -c chmod -s f -d 'Do not display a diagnostic message if chmod could not modify the mode for fi…'
complete -c chmod -s H -d 'If the R option is specified, symbolic links on the command line are followed…'
complete -c chmod -s h -d 'If the file is a symbolic link, change the mode of the link itself rather tha…'
complete -c chmod -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c chmod -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c chmod -s R -d 'Change the modes of the file hierarchies rooted in the files, instead of just…'
complete -c chmod -s v -d 'Cause chmod to be verbose, showing filenames as the mode is modified'

