# chroot
# Autogenerated from man page /usr/share/man/man8/chroot.8.gz
complete -c chroot -s G -d 'Run the command with the permissions of the specified groups'
complete -c chroot -s g -d 'Run the command with the permissions of the specified group'
complete -c chroot -s u -d 'Run the command as the user'
complete -c chroot -s n -d 'Use the PROC_NO_NEW_PRIVS_CTL procctl 2 command before chrooting, effectively…'

