# ck-list-sessions
# Autogenerated from man page /usr/local/man/man1/ck-list-sessions.1.gz
complete -c ck-list-sessions -l all -d 'the system'
complete -c ck-list-sessions -l format
complete -c ck-list-sessions -s a -d 'Show all ConsoleKit sessions'
complete -c ck-list-sessions -s f -d 'Display information using the specified format'
complete -c ck-list-sessions -s h -l help -d 'Display detailed usage message'
complete -c ck-list-sessions -s V -l version -d 'Display the version of the ck-list-sessions application'

