# ckdist
# Autogenerated from man page /usr/share/man/man1/ckdist.1.gz
complete -c ckdist -s a -d 'Report on all distribution components, not just those in respect of which err…'
complete -c ckdist -s i -d 'Ignore missing distribution components'
complete -c ckdist -s r -d 'Search specified directories recursively'
complete -c ckdist -s s -d 'Suppress complaints about inaccessible checksum files and directories'
complete -c ckdist -s x -d 'Verify the existence of distribution components (and also check sizes, in the…'
complete -c ckdist -s d -d 'Look for distribution components in the directory dir'
complete -c ckdist -s n -d 'Access distribution components using the filename name.  When accessing '
complete -c ckdist -s t -d 'Assume that all specified checksum files are of the format type, and search d…'

