# column
# Autogenerated from man page /usr/share/man/man1/column.1.gz
complete -c column -s c -d 'Output is formatted for a display columns wide'
complete -c column -s s -d 'Specify a set of characters to be used to delimit columns for the t option'
complete -c column -s t -d 'Determine the number of columns the input contains and create a table'
complete -c column -s x -d 'Fill columns before filling rows'

