# config
# Autogenerated from man page /usr/share/man/man8/config.8.gz
complete -c config -s V -d 'Print the config version number'
complete -c config -s C -d 'If the INCLUDE_CONFIG_FILE is present in a configuration file, kernel image w…'
complete -c config -s I -d 'Search in path for any file included by the include directive'
complete -c config -s d -d 'Use destdir as the output directory, instead of the default one'
complete -c config -s s -d 'Use srcdir as the source directory, instead of the default one'
complete -c config -s m -d 'Print the MACHINE and MACHINE_ARCH values for this kernel and exit'
complete -c config -s g -d 'Configure a system for debugging'
complete -c config -s x -d 'Print kernel configuration file embedded into a kernel file'

