# console-kit-daemon.1m
# Autogenerated from man page /usr/local/man/man1/console-kit-daemon.1m.gz
complete -c 'console-kit-daemon.1m' -l debug -d 'Enable debug output'
complete -c 'console-kit-daemon.1m' -s h -l help -d 'Display detailed usage message'
complete -c 'console-kit-daemon.1m' -l no-daemon -d 'Avoid starting console-kit-daemon as a daemon.   Useful for debugging'
complete -c 'console-kit-daemon.1m' -l timed-exit -d 'Exit after 30 seconds. 	Useful for debugging.  ENVIRONMENT VARIABLES'

