# cp
# Autogenerated from man page /usr/share/man/man1/cp.1.gz
complete -c cp -s H -d 'If the R option is specified, symbolic links on the command line are followed'
complete -c cp -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c cp -s P -d 'No symbolic links are followed'
complete -c cp -s R -d 'If source_file designates a directory, cp copies the directory and the entire…'
complete -c cp -s a -d 'Archive mode.  Same as RpP'
complete -c cp -s f -d 'For each existing destination pathname, remove it and create a new file, with…'
complete -c cp -s i -d 'Cause cp to write a prompt to the standard error output before copying a file…'
complete -c cp -s l -d 'Create hard links to regular files in a hierarchy instead of copying'
complete -c cp -s n -d 'Do not overwrite an existing file'
complete -c cp -s p -d 'Cause cp to preserve the following attributes of each source file in the copy…'
complete -c cp -s s -d 'Create symbolic links to regular files in a hierarchy instead of copying'
complete -c cp -s v -d 'Cause cp to be verbose, showing files as they are copied'
complete -c cp -s x -d 'File system mount points are not traversed'

