# cpucontrol
# Autogenerated from man page /usr/share/man/man8/cpucontrol.8.gz
complete -c cpucontrol -s d -d 'Directory paths where to look for microcode images'
complete -c cpucontrol -s n -d 'Do not look for the microcode images in the standard directories'
complete -c cpucontrol -s m -d 'Show value of the specified MSR'
complete -c cpucontrol -s i -d 'Retrieve CPUID info.  Level should be given as a hex number'
complete -c cpucontrol -s u -d 'Apply CPU firmware updates'
complete -c cpucontrol -s e -d 'Re-evaluate the kernel flags indicating the present CPU features'
complete -c cpucontrol -s v -d 'Increase the verbosity level'
complete -c cpucontrol -s h -d 'Show help message'

