# cpuset
# Autogenerated from man page /usr/share/man/man1/cpuset.1.gz
complete -c cpuset -s C -d 'Create a new cpuset and assign the target process to that set'
complete -c cpuset -s c -d 'The requested operation should reference the cpuset available via the target …'
complete -c cpuset -s d -d 'Specifies a NUMA domain id as the target of the operation'
complete -c cpuset -s g -d 'Causes cpuset to print either a list of valid CPUs or, using i, the id of the…'
complete -c cpuset -s i -d 'When used with the g option print the id rather than the valid mask of the ta…'
complete -c cpuset -s j -d 'Specifies a jail id or name as the target of the operation'
complete -c cpuset -s l -d 'Specifies a list of CPUs to apply to a target'
complete -c cpuset -s n -d 'Specifies a list of domains and allocation policy to apply to a target'
complete -c cpuset -s p -d 'Specifies a pid as the target of the operation'
complete -c cpuset -s s -d 'Specifies a set id as the target of the operation'
complete -c cpuset -s r -d 'The requested operation should reference the root set available via the targe…'
complete -c cpuset -s t -d 'Specifies a thread id as the target of the operation'
complete -c cpuset -s x -d 'Specifies an irq as the target of the operation'

