# crashinfo
# Autogenerated from man page /usr/share/man/man8/crashinfo.8.gz
complete -c crashinfo -s b -d 'Run in batch mode.  Write most messages to the core. txt'
complete -c crashinfo -s d -d 'Specify an alternate core dump directory'
complete -c crashinfo -s n -d 'Use the core dump saved in vmcore'
complete -c crashinfo -s k -d 'Specify an explicit kernel file'

