# cron
# Autogenerated from man page /usr/share/man/man8/cron.8.gz
complete -c cron -s j -d 'Enable time jitter'
complete -c cron -s J -d 'Enable time jitter for superuser jobs'
complete -c cron -s m -d 'Overrides the default recipient for cron mail'
complete -c cron -s n -d 'Do not daemonize; run in foreground instead'
complete -c cron -s s -d 'Enable special handling of situations when the GMT offset of the local timezo…'
complete -c cron -s o -d 'Disable the special handling of situations when the GMT offset of the local t…'
complete -c cron -s x -d 'Enable writing of debugging information to standard output'

