# crunchgen
# Autogenerated from man page /usr/share/man/man1/crunchgen.1.gz
complete -c crunchgen -s c -d 'Set output C file name to c-file-name.  The default name is <conf-name>. c'
complete -c crunchgen -s e -d 'Set crunched binary executable file name to exec-file-name'
complete -c crunchgen -s f -d 'Flush cache.  Forces the recalculation of cached parameters'
complete -c crunchgen -s l -d 'List names.  Lists the names this binary will respond to'
complete -c crunchgen -s h -d 'Set the name of a file to be included at the beginning of the Makefile Ns s g…'
complete -c crunchgen -s m -d 'Set output Makefile name to makefile-name.  The default name is <conf-name>'
complete -c crunchgen -s o -d 'Add make obj rules to each program make target'
complete -c crunchgen -s p -d 'Set the pathname to be prepended to the srcdir when computing the objdir'
complete -c crunchgen -s q -d 'Quiet operation.  Status messages are suppressed'

