# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1.gz
complete -c ctags -s B -d 'Use backward searching patterns ?. ?'
complete -c ctags -s F -d 'Use forward searching patterns /. / (the default)'
complete -c ctags -s T -d 'Do not create tags for typedefs, structs, unions, and enums'
complete -c ctags -s a -d 'Append to tags file'
complete -c ctags -s d -d 'Create tags for #defines that do not take arguments; #defines that take argum…'
complete -c ctags -s f -d 'Place the tag descriptions in a file called tagsfile'
complete -c ctags -s u -d 'Update the specified files in the tags file, that is, all references to them …'
complete -c ctags -s v -d 'An index of the form expected by vgrind 1 is produced on the standard output'
complete -c ctags -s w -d 'Suppress warning diagnostics'
complete -c ctags -s x -d 'ctags produces a list of object names, the line number and file name on which…'

