# ctfconvert
# Autogenerated from man page /usr/share/man/man1/ctfconvert.1.gz
complete -c ctfconvert -s l -d 'Sets the label as label'
complete -c ctfconvert -s L -d 'Instructs ctfconvert to read the label from the environment variable labelenv'
complete -c ctfconvert -s g -d 'Don\'t delete the original debugging section'
complete -c ctfconvert -s i -d 'Ignore object files built from other languages than C'
complete -c ctfconvert -s s -d 'Use the . dynsym ELF section instead of the . symtab ELF section'
complete -c ctfconvert -s o -d 'Write the output to file in outfile'

