# ctfdump
# Autogenerated from man page /usr/share/man/man1/ctfdump.1.gz
complete -c ctfdump -s d -d 'Show the data object section'
complete -c ctfdump -s f -d 'Show the function section'
complete -c ctfdump -s h -d 'Show the header'
complete -c ctfdump -s l -d 'Show the label section'
complete -c ctfdump -s s -d 'Show the string table'
complete -c ctfdump -s S -d 'Show statistics'
complete -c ctfdump -s t -d 'Show the type section'
complete -c ctfdump -s u -d 'Write the uncompressed CTF data to a raw CTF file called ufile'

