# ctfmerge
# Autogenerated from man page /usr/share/man/man1/ctfmerge.1.gz
complete -c ctfmerge -s f -d 'Match global symbols to global CTF data'
complete -c ctfmerge -s g -d 'Don\'t delete the original debugging sections'
complete -c ctfmerge -s s -d 'Use the . dynsym ELF section instead of the . symtab ELF section'
complete -c ctfmerge -s t -d 'Make sure that all object files have a CTF section'
complete -c ctfmerge -s v -d 'Enable verbose mode'
complete -c ctfmerge -s l -d 'Sets the label as label'
complete -c ctfmerge -s L -d 'Instructs ctfmerge to read the label from the environment variable labelenv'
complete -c ctfmerge -s o -d 'Use outfile to store the merged CTF data'
complete -c ctfmerge -s d -d 'Uniquify against uniqfile'
complete -c ctfmerge -s w -d 'Additive merge with withfile'
complete -c ctfmerge -s c -d 'Copy CTF data from srcfile into destfile'

