# ctld
# Autogenerated from man page /usr/share/man/man8/ctld.8.gz
complete -c ctld -s f -d 'Specifies the name of the configuration file.  The default is /etc/ctl. conf'
complete -c ctld -s d -d 'Debug mode'
complete -c ctld -s t -d 'Test the configuration file for validity and exit'
complete -c ctld -s u -d 'Use UCL configuration file format instead of the traditional non-UCL format'

