# ctlstat
# Autogenerated from man page /usr/share/man/man8/ctlstat.8.gz
complete -c ctlstat -s t -d 'Total mode'
complete -c ctlstat -s c -d 'Display statistics this many times'
complete -c ctlstat -s C -d 'Disable CPU statistics display'
complete -c ctlstat -s d -d 'Display DMA operation time (latency) instead of overall I/O time (latency)'
complete -c ctlstat -s D -d 'Text dump mode'
complete -c ctlstat -s h -d 'Suppress display of the header'
complete -c ctlstat -s j -d 'JSON dump mode'
complete -c ctlstat -s P -d 'Prometheus dump mode'
complete -c ctlstat -s l -d 'Request statistics for the specified LUN'
complete -c ctlstat -s n -d 'Display statistics for this many devices'
complete -c ctlstat -s p -d 'Request statistics for the specified port'
complete -c ctlstat -s w -d 'Wait this many seconds in between displays'

