# cu
# Autogenerated from man page /usr/share/man/man1/cu.1.gz
complete -c cu -s a -d 'Set the acu'
complete -c cu -s e -d 'Use even parity'
complete -c cu -s h -d 'Echo characters locally (half-duplex mode)'
complete -c cu -s l -d 'Specify the line to use'
complete -c cu -s o -d 'Use odd parity'
complete -c cu -s s -d 'Set the speed of the connection.  The default is 9600'
complete -c cu -s t -d 'Connect via a hard-wired connection to a host on a dial-up line'

