# cups-config
# Autogenerated from man page /usr/local/man/man1/cups-config.1.gz
complete -c cups-config -l api-version -d 'Reports the current API version (major. minor)'
complete -c cups-config -l build -d 'Reports a system-specific build number'
complete -c cups-config -l cflags -d 'Reports the necessary compiler options'
complete -c cups-config -l datadir -d 'Reports the default CUPS data directory'
complete -c cups-config -l help -d 'Reports the program usage message'
complete -c cups-config -l ldflags -d 'Reports the necessary linker options'
complete -c cups-config -l libs -d 'Reports the necessary libraries to link to'
complete -c cups-config -l serverbin -d 'Reports the default CUPS binary directory, where filters and backends are sto…'
complete -c cups-config -l serverroot -d 'Reports the default CUPS configuration file directory'
complete -c cups-config -l static -d 'When used with --libs, reports the static libraries instead of the default (s…'
complete -c cups-config -l version -d 'Reports the full version number of the CUPS installation (major. minor'
complete -c cups-config -l image -d 'Formerly used to add the CUPS imaging library to the list of libraries'

