# cut
# Autogenerated from man page /usr/share/man/man1/cut.1.gz
complete -c cut -s b -d 'The list specifies byte positions'
complete -c cut -s c -d 'The list specifies character positions'
complete -c cut -s d -d 'Use delim as the field delimiter character instead of the tab character'
complete -c cut -s f -d 'The list specifies fields, separated in the input by the field delimiter char…'
complete -c cut -s n -d 'Do not split multi-byte characters'
complete -c cut -s s -d 'Suppress lines with no field delimiter characters'
complete -c cut -s w -d 'Use whitespace (spaces and tabs) as the delimiter'

