# daemon
# Autogenerated from man page /usr/share/man/man8/daemon.8.gz
complete -c daemon -s c -d 'Change the current working directory to the root /'
complete -c daemon -s f -d 'Redirect standard input, standard output and standard error to /dev/null'
complete -c daemon -s H -d 'Close output_file and re-open it when signal SIGHUP is received, for interope…'
complete -c daemon -s S -d 'Enable syslog output'
complete -c daemon -s o -d 'Append output from the daemonized process to output_file'
complete -c daemon -s m -d 'Redirect output from the child process stdout (1), stderr (2), or both (3)'
complete -c daemon -s p -d 'Write the ID of the created process into the child_pidfile using the pidfile …'
complete -c daemon -s P -d 'Write the ID of the daemon process into the supervisor_pidfile using the pidf…'
complete -c daemon -s r -d 'Supervise and restart the program after a one-second delay if it has been ter…'
complete -c daemon -s R -d 'Supervise and restart the program after the specified delay if it has been te…'
complete -c daemon -s t -d 'Set the title for the daemon process'
complete -c daemon -s u -d 'Login name of the user to execute the program under'
complete -c daemon -s s -d 'These priorities are accepted: emerg, alert, crit, err, warning, notice, info…'
complete -c daemon -s l -d 'These facilities are accepted: auth, authpriv, console, cron, daemon, ftp, ke…'
complete -c daemon -s T -d 'Set the tag which is appended to all syslog messages.  The default is daemon'

