# date
# Autogenerated from man page /usr/share/man/man1/date.1.gz
complete -c date -s f -d 'Use input_fmt as the format string to parse the new_date provided rather than…'
complete -c date -s I -d 'Use -iso8601 output format'
complete -c date -s j -d 'Do not try to set the date'
complete -c date -s n -d 'Obsolete flag, accepted and ignored for compatibility'
complete -c date -s R -d 'Use RFC 2822 date and time output format'
complete -c date -s r -d 'Print the date and time represented by seconds, where seconds is the number o…'
complete -c date -s u -d 'Display or set the date in UTC (Coordinated Universal) time'
complete -c date -s z -d 'Just before printing the time, change to the specified timezone; see the desc…'

