# dc
# Autogenerated from man page /usr/share/man/man1/dc.1.gz
complete -c dc -s C -l no-digit-clamp -d 'Disables clamping of digits greater than or equal to the current ibase when p…'
complete -c dc -s c -l digit-clamp -d 'Enables clamping of digits greater than or equal to the current ibase when pa…'
complete -c dc -s E -l seed -d 'Sets the builtin variable seed to the value seed assuming that seed is in bas…'
complete -c dc -s e -l expression -d 'Evaluates expr'
complete -c dc -s f -l file -d 'DC_ENV_ARGS.  However, if any other -e, --expression,'
complete -c dc -o f- -d exit
complete -c dc -s h -l help -d 'Prints a usage message and exits'
complete -c dc -s I -l ibase -d 'Sets the builtin variable ibase to the value ibase assuming that ibase is in …'
complete -c dc -s i -l interactive -d 'Forces interactive mode.  (See the INTERACTIVE MODE section'
complete -c dc -s L -l no-line-length -d 'Disables line length checking and prints numbers without backslashes and newl…'
complete -c dc -s O -l obase -d 'Sets the builtin variable obase to the value obase assuming that obase is in …'
complete -c dc -s P -l no-prompt -d 'Disables the prompt in TTY mode.  (The prompt is only enabled in TTY mode'
complete -c dc -s R -l no-read-prompt -d 'Disables the read prompt in TTY mode'
complete -c dc -s S -l scale -d 'Sets the builtin variable scale to the value scale assuming that scale is in …'
complete -c dc -s v -s V -l version -d 'Print the version information (copyright header) and exits'
complete -c dc -s x -l extended-register -d 'Enables extended register mode'
complete -c dc -s z -l leading-zeroes -d 'Makes dc(1) print all numbers greater than -1 and less than 1, and not equal …'
complete -c dc -o C/--no-digit-clamp -d 'OPTIONS section), the existence and setting of the DC_DIGIT_CLAMP environment…'
complete -c dc -o h/--help

