# dconschat
# Autogenerated from man page /usr/share/man/man8/dconschat.8.gz
complete -c dconschat -s b -d 'Translate Ctrl-C to ALT_BREAK (CR + ~ + Ctrl-B) on gdb 1 Pq Pa ports/devel/gd…'
complete -c dconschat -s r -d 'Replay old buffer on connection'
complete -c dconschat -s v -d 'Verbose debug output.  Multiple v options increase verbosity'
complete -c dconschat -s w -d 'Listen on a wildcard address rather than localhost'
complete -c dconschat -s R -d 'Read-only.  Do not write anything to the dcons 4 buffer'
complete -c dconschat -s T -d 'Enable ad-hoc workaround for the TELNET protocol to remove unnecessary byte s…'
complete -c dconschat -s 1 -d 'One-shot.  Read available buffer, then exit.  This implies the r option'
complete -c dconschat -s e -d 'Specify escape character.  The default is \'~\''
complete -c dconschat -s h -d 'Specify polling rate.  The default value is 100'
complete -c dconschat -s C -d 'Specify the console port.  The default value is 0 (stdin/stdout)'
complete -c dconschat -s G -d 'Specify gdb 1 Pq Pa ports/devel/gdb port'
complete -c dconschat -s M -d 'Specify core file'
complete -c dconschat -s N -d 'Specify system file such as /boot/kernel/kernel'
complete -c dconschat -s t -d 'Specify the 64-bit extended unique identifier of the target, and use FireWire…'
complete -c dconschat -s a -d 'Specify the physical I/O address of the dcons 4 buffer'
complete -c dconschat -s u -d 'Specify FireWire bus number.  The default is 0'

