# decryptcore
# Autogenerated from man page /usr/share/man/man8/decryptcore.8.gz
complete -c decryptcore -s f -d 'Remove a decryped core dump if it already exists'
complete -c decryptcore -s L -d 'Write log messages to syslogd 8'
complete -c decryptcore -s v -d 'Print or log verbose/debugging information'
complete -c decryptcore -s p -d 'Specify location of a private key file which will be used to decrypt a dump k…'
complete -c decryptcore -s k -d 'Specify location of a dump key file'
complete -c decryptcore -s e -d 'Specify location of an encrypted core'
complete -c decryptcore -s c -d 'Specify location of a resulting decrypted core dump'
complete -c decryptcore -s d -d 'Specify an alternative crash dump directory'
complete -c decryptcore -s n -d 'Specify a number of a crash dump to be decrypted'

