# devd
# Autogenerated from man page /usr/share/man/man8/devd.8.gz
complete -c devd -s d -d 'Run in the foreground instead of becoming a daemon and log additional informa…'
complete -c devd -s f -d 'Use configuration file file instead of the default /etc/devd. conf'
complete -c devd -s l -d 'Limit concurrent socket connections to num'
complete -c devd -s n -d 'Do not process all pending events before becoming a daemon'
complete -c devd -s q -d 'Quiet mode.  Only log messages at priority LOG_WARNING or above'

