# devfs
# Autogenerated from man page /usr/share/man/man8/devfs.8.gz
complete -c devfs -s m -d 'Operate on mount-point, which is expected to be a devfs 5 mount'
complete -c devfs -s s -d 'Operate on the ruleset with the number ruleset'

