# devinfo
# Autogenerated from man page /usr/share/man/man8/devinfo.8.gz
complete -c devinfo -s r -d 'Causes hardware resource information (such as IRQ, I/O ports, I/O memory addr…'
complete -c devinfo -s u -d 'Displays the same information as with r but sorts by resource type rather tha…'
complete -c devinfo -s v -d 'Display all devices in the driver tree, not just those that are attached or b…'
complete -c devinfo -s p -d 'Display the path of dev back to the root of the device tree'

