# devmatch
# Autogenerated from man page /usr/share/man/man8/devmatch.8.gz
complete -c devmatch -s a -d 'Include all devices, not just the ones that are unattached'
complete -c devmatch -s d -d 'Produce a human readable dump of the linker. hints file'
complete -c devmatch -s h -d 'Use the named file instead of linker'
complete -c devmatch -s p -d 'Parse and use a standard NOMATCH event from devd 8 for matching instead of se…'
complete -c devmatch -s q -d 'Suppress some error messages and simply return a non-zero exit code'
complete -c devmatch -s u -d 'Attempt to produce a list of those drivers with PNP info whose driver tables …'
complete -c devmatch -s v -d 'Produce more verbose output.  El SEE ALSO rc'

