# df
# Autogenerated from man page /usr/share/man/man1/df.1.gz
complete -c df -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c df -s a -d 'Show all mount points, including those that were mounted with the MNT_IGNORE …'
complete -c df -s b -d 'Explicitly use 512 byte blocks, overriding any BLOCKSIZE specification from t…'
complete -c df -s c -d 'Display a grand total'
complete -c df -s g -d 'Use 1073741824 byte (1 Gibibyte) blocks rather than the default'
complete -c df -s h -d 'Human-readable output'
complete -c df -s H -d 'Same as h but based on powers of 1000'
complete -c df -s i -d 'Include statistics on the number of free and used inodes'
complete -c df -s k -d 'Use 1024 byte (1 Kibibyte) blocks rather than the default'
complete -c df -s l -d 'Select locally-mounted file system for display'
complete -c df -s m -d 'Use 1048576 byte (1 Mebibyte) blocks rather than the default'
complete -c df -s n -d 'Print out the previously obtained statistics from the file systems'
complete -c df -s P -d 'Explicitly use 512 byte blocks, overriding any BLOCKSIZE specification from t…'
complete -c df -s t -d 'Select file systems to display'
complete -c df -s T -d 'Include file system type'

