# dhclient
# Autogenerated from man page /usr/share/man/man8/dhclient.8.gz
complete -c dhclient -s b -d 'Forces dhclient to immediately move to the background'
complete -c dhclient -s c -d 'Specify an alternate location, file, for the configuration file'
complete -c dhclient -s d -d 'Forces dhclient to always run as a foreground process'
complete -c dhclient -s l -d 'Specify an alternate location, file, for the leases file'
complete -c dhclient -s p -d 'Specify an alternate location for the PID file'
complete -c dhclient -s q -d 'Forces dhclient to be less verbose on startup'
complete -c dhclient -s u -d 'Forces dhclient to reject leases with unknown options in them'

