# diskinfo
# Autogenerated from man page /usr/share/man/man8/diskinfo.8.gz
complete -c diskinfo -s v -d 'Print fields one per line with a descriptive comment'
complete -c diskinfo -s c -d 'Perform a simple measurement of the I/O read command overhead'
complete -c diskinfo -s i -d 'Perform a simple IOPS benchmark'
complete -c diskinfo -s p -d 'Return the physical path of the disk'
complete -c diskinfo -s s -d 'Return the disk ident, usually the serial number'
complete -c diskinfo -s S -d 'Perform synchronous random write test (ZFS SLOG test), measuring time require…'
complete -c diskinfo -s t -d 'Perform a simple and rather naive benchmark of the disks seek and transfer pe…'
complete -c diskinfo -s w -d 'Allow disruptive write tests'

