# dma
# Autogenerated from man page /usr/share/man/man8/dma.8.gz
complete -c dma -s A -d '\\&Ac acts as a compatibility option for sendmail'
complete -c dma -s b -d '-tag -width indent'
complete -c dma -o bp -d 'List all mails currently stored in the mail queue'
complete -c dma -o bq -d 'Queue the mail, but do not attempt to deliver it'
complete -c dma -s D -d 'Do not run in the background.  Useful for debugging'
complete -c dma -s f -d 'Set sender address (envelope-from) to sender'
complete -c dma -s i -d 'Ignore dots alone on lines by themselves in incoming messages'
complete -c dma -s L -d 'Set the identifier used in syslog messages to the supplied tag'
complete -c dma -s O -d 'This is a compatibility option for sendmail'
complete -c dma -s o -d 'Specifying oi is synonymous to i.  All other options are ignored'
complete -c dma -s q -d 'Process saved messages in the queue.  The argument is optional and ignored'
complete -c dma -s r -d 'Same as f'
complete -c dma -s t -d 'Obtain recipient addresses from the message header'

