# dmesg
# Autogenerated from man page /usr/share/man/man8/dmesg.8.gz
complete -c dmesg -s a -d 'Show all data in the message buffer'
complete -c dmesg -s c -d 'Clear the kernel buffer after printing'
complete -c dmesg -s M -d 'Extract values associated with the name list from the specified core'
complete -c dmesg -s N -d 'If M is also specified, extract the name list from the specified system inste…'

