# dnctl
# Autogenerated from man page /usr/share/man/man8/dnctl.8.gz
complete -c dnctl -s a -d 'Show counter values when listing rules.  The show command implies this option'
complete -c dnctl -s b -d 'Only show the action and the comment, not the body of a rule.  Implies c'
complete -c dnctl -s c -d 'When entering or showing rules, print them in compact form, i. e'
complete -c dnctl -s d -d 'When listing, show dynamic rules in addition to static ones'
complete -c dnctl -s D -d 'When listing, show only dynamic states'
complete -c dnctl -s f -d 'Run without prompting for confirmation for commands that can cause problems i…'
complete -c dnctl -s i -d 'When listing a table (see the LOOKUP TABLES section below for more informatio…'
complete -c dnctl -s n -d 'Only check syntax of the command strings, without actually passing them to th…'
complete -c dnctl -s N -d 'Try to resolve addresses and service names in output'
complete -c dnctl -s q -d 'Be quiet when executing the add, nat, zero, resetlog or flush commands; (impl…'
complete -c dnctl -s S -d 'When listing rules, show the set each rule belongs to'
complete -c dnctl -s s -d 'When listing pipes, sort according to one of the four counters (total or curr…'
complete -c dnctl -s t -d 'When listing, show last match timestamp converted with ctime'
complete -c dnctl -s T -d 'When listing, show last match timestamp as seconds from the epoch'

