# dumpon
# Autogenerated from man page /usr/share/man/man8/dumpon.8.gz
complete -c dumpon -s i -d 'Insert the specified dump configuration into the prioritized fallback dump de…'
complete -c dumpon -s r -d 'Remove the specified dump device configuration or configurations from the fal…'
complete -c dumpon -s k -d 'Configure encrypted kernel dumps'
complete -c dumpon -s C -d 'Select the symmetric algorithm used for encrypted kernel crash dump'
complete -c dumpon -s l -d 'List the currently configured dump device(s), or /dev/null if no devices are …'
complete -c dumpon -s v -d 'Enable verbose mode'
complete -c dumpon -s Z -d 'Enable compression (Zstandard)'
complete -c dumpon -s z -d 'Enable compression (gzip)'
complete -c dumpon -s c -d 'The local IP address of the netdump 4 client'
complete -c dumpon -s g -d 'The first-hop router between client and server'
complete -c dumpon -s s -d 'The IP address of the netdumpd 8 server'

