# editmap
# Autogenerated from man page /usr/share/man/man8/editmap.8.gz
complete -c editmap -s C -d 'Use the specified  sendmail configuration file for looking up the TrustedUser…'
complete -c editmap -s N -d 'Include the null byte that terminates strings in the map (for alias maps)'
complete -c editmap -s f -d 'Normally all upper case letters in the key are folded to lower case'
complete -c editmap -s q -d 'Query the map for the specified key'
complete -c editmap -s u -d 'Update the record for  key with  value or inserts a new record if one doesn\'t…'
complete -c editmap -s x -d 'Deletes the specific key from the map'

