# edit
# Autogenerated from man page /usr/share/man/man1/edit.1.gz
complete -c edit -s i -d 'Turns off display of information window at top of terminal'
complete -c edit -s h -d 'Turns off highlighting of borders of windows and menus (improves performance …'
complete -c edit -s e -d 'Turns off expansion of tab character to spaces'

