# ee
# Autogenerated from man page /usr/share/man/man1/ee.1.gz
complete -c ee -s i -d 'Turns off display of information window at top of terminal'
complete -c ee -s h -d 'Turns off highlighting of borders of windows and menus (improves performance …'
complete -c ee -s e -d 'Turns off expansion of tab character to spaces'

