# efidp
# Autogenerated from man page /usr/share/man/man8/efidp.8.gz
complete -c efidp -s f -d 'Formats a binary UEFI Device Path into its canonical UTF-8 textual form'
complete -c efidp -s p -d 'Parses a UEFI Device Path UTF-8 specification and outputs the binary Device P…'
complete -c efidp -s e -d 'Translate a Unix file path to an EFI Device Path'
complete -c efidp -s u -d 'Translate an EFI device path to a Unix file path'

