# efitable
# Autogenerated from man page /usr/share/man/man8/efitable.8.gz
complete -c efitable -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c efitable -s t -d 'Specify the name of the table to print'
complete -c efitable -s u -d 'Specify the UUID of the table to print'

