# elfctl
# Autogenerated from man page /usr/share/man/man1/elfctl.1.gz
complete -c elfctl -s h -d 'Print a usage message and exit'
complete -c elfctl -s i -d 'Ignore unknown feature flags in featurelist'
complete -c elfctl -s l -d 'List known ELF feature flags'
complete -c elfctl -s e -d 'Edit features from the given comma separated list featurelist'

