# elfdump
# Autogenerated from man page /usr/share/man/man1/elfdump.1.gz
complete -c elfdump -s a -d 'Dump all information'
complete -c elfdump -s c -d 'Dump section headers'
complete -c elfdump -s d -d 'Dump dynamic symbols'
complete -c elfdump -s e -d 'Dump ELF header'
complete -c elfdump -s E -d 'Return success if file is an ELF file and failure if it is not'
complete -c elfdump -s G -d 'Dump the GOT'
complete -c elfdump -s h -d 'Dump the hash values'
complete -c elfdump -s i -d 'Dump the dynamic interpreter'
complete -c elfdump -s n -d 'Dump note sections'
complete -c elfdump -s p -d 'Dump the program header'
complete -c elfdump -s r -d 'Dump relocations'
complete -c elfdump -s s -d 'Dump the symbol table'
complete -c elfdump -s w -d 'Write output to a file instead of the standard output'

