# etcupdate
# Autogenerated from man page /usr/share/man/man8/etcupdate.8.gz
complete -c etcupdate -s A -d 'Always install the new version of any files that match any of the patterns li…'
complete -c etcupdate -s B -d 'Do not build generated files in a private object tree'
complete -c etcupdate -s D -d 'Specify an alternate destination directory as the target of a merge'
complete -c etcupdate -s d -d 'Specify an alternate directory to use as the work directory'
complete -c etcupdate -s F -d 'Ignore changes in the FreeBSD ID string when comparing files in the destinati…'
complete -c etcupdate -s I -d 'Ignore any files that match any of the patterns listed in patterns'
complete -c etcupdate -s L -d 'Specify an alternate path for the log file'
complete -c etcupdate -s M -d 'Pass options as additional parameters to make 1 when building a current tree'
complete -c etcupdate -s m -d 'Use make as the make 1 binary when building a current tree'
complete -c etcupdate -s n -d 'Enable dry-run mode.  Do not merge any changes to the destination directory'
complete -c etcupdate -s N -d 'Perform a NO_ROOT build when building a current tree'
complete -c etcupdate -s p -d 'Enable pre-world mode'
complete -c etcupdate -s r -d 'Do not update the current and previous trees during a merge'
complete -c etcupdate -s s -d 'Specify an alternate source tree to use when building or extracting a current…'
complete -c etcupdate -s t -d 'Extract a new current tree from a tarball previously generated by the build c…'

