# etdump
# Autogenerated from man page /usr/share/man/man1/etdump.1.gz
complete -c etdump -s f -d 'Select the output format'
complete -c etdump -s o -d 'Write output to file.  If \'-\' is specified then standard out is used'

