# etherswitchcfg
# Autogenerated from man page /usr/share/man/man8/etherswitchcfg.8.gz
complete -c etherswitchcfg -s m -d 'When reporting port information, also list available media options for that p…'
complete -c etherswitchcfg -s v -d 'Produce more verbose output'
complete -c etherswitchcfg -o addtag -d 'Disable the add VLAN tag option'
complete -c etherswitchcfg -o striptag -d 'Disable the strip VLAN tag option'
complete -c etherswitchcfg -o striptagingress -d 'Disable the strip VLAN tag on ingress option'
complete -c etherswitchcfg -o firstlock -d 'Disable the first lock option'
complete -c etherswitchcfg -o droptagged -d 'Disable the drop tagged packets option'
complete -c etherswitchcfg -o dropuntagged -d 'Disable the drop untagged packets option.  doubletag Enable QinQ for the port'
complete -c etherswitchcfg -o doubletag -d 'Disable QinQ for the port.  ingress Enable the ingress filter on the port'
complete -c etherswitchcfg -o ingress -d 'Disable the ingress filter'

