# ex
# Autogenerated from man page /usr/share/man/man1/ex.1.gz
complete -c ex -s c -d 'Execute cmd on the first file loaded'
complete -c ex -s e -d 'Start editing in ex mode, as if the command name were ex ex'
complete -c ex -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c ex -s R -d 'Start editing in read-only mode, as if the command name was ex view, or the r…'
complete -c ex -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c ex -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c ex -s s -d 'Enter batch mode; applicable only to ex ex edit sessions'
complete -c ex -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c ex -s v -d 'Start editing in vi mode, as if the command name was ex vi'
complete -c ex -s w -d 'Set the initial window size to the specified number of lines'

