# expand
# Autogenerated from man page /usr/share/man/man1/expand.1.gz
complete -c expand -s a -d 'expand ( unexpand only'
complete -c expand -s t -d 'Set tab stops at column positions tab1 , tab2 , .  , tabn'

