# extraclangtools15
# Autogenerated from man page /usr/local/man/man1/extraclangtools15.1.gz
complete -c extraclangtools15 -s p
complete -c extraclangtools15 -o prefix -d 'Prepend the given path to non-absolute file paths in the header list file'
complete -c extraclangtools15 -o module-map-path -d 'Generate a module map and output it to the given file'
complete -c extraclangtools15 -o problem-files-list -d 'For use only with module map assistant'
complete -c extraclangtools15 -o root-module -d 'Put modules generated by the -module-map-path option in an enclosing module w…'
complete -c extraclangtools15 -o block-check-header-list-only -d 'Limit the #include-inside-extern-or-namespace-block check to only those heade…'
complete -c extraclangtools15 -o no-coverage-check -d 'Don\'t do the coverage check for a module map'
complete -c extraclangtools15 -o coverage-check-only -d 'Only do the coverage check for a module map'
complete -c extraclangtools15 -o display-file-lists -d 'Display lists of good files (no compile errors), problem files, and a combine…'
complete -c extraclangtools15 -o callbacks -d 'This option specifies a comma-separated list of globs describing the list of …'
complete -c extraclangtools15 -o output -d 'By default, pp-trace outputs the trace information to stdout'
complete -c extraclangtools15 -l -
complete -c extraclangtools15 -o qualified-name -d '$ clang-rename -offset=42 -new-name=bar1 -offset=150 -new-name=bar2 test'

