# fdformat
# Autogenerated from man page /usr/share/man/man8/fdformat.8.gz
complete -c fdformat -s F -d 'Use fill as the fill byte for newly formatted sectors'
complete -c fdformat -s f -d 'Specify the density settings for a fmt kilobyte format, as described in fdcon…'
complete -c fdformat -s s -d 'Specify the density settings using explicit parameters, as described in fdcon…'
complete -c fdformat -s n -d 'Do not verify floppy after formatting'
complete -c fdformat -s q -d 'Suppress any normal output from the command, and do not ask the user for a co…'
complete -c fdformat -s v -d 'Do not format, verify only'
complete -c fdformat -s y -d 'Do not ask for confirmation whether to format the floppy disk but still repor…'

