# fdisk
# Autogenerated from man page /usr/share/man/man8/fdisk.8.gz
complete -c fdisk -s a -d 'Change the active slice only.  Ignored if f is given'
complete -c fdisk -s b -d 'Get the boot code from the file bootcode.  Default is /boot/mbr'
complete -c fdisk -s B -d 'Reinitialize the boot code contained in sector 0 of the disk'
complete -c fdisk -s f -d 'Set slice values using the file configfile'
complete -c fdisk -s i -d 'Initialize sector 0 of the disk'
complete -c fdisk -s I -d 'Initialize sector 0 slice table for one Fx slice covering the entire disk'
complete -c fdisk -s p -d 'Print a slice table in fdisk configuration file format and exit; see CONFIGUR…'
complete -c fdisk -s q -d 'Be quiet.  Benign warnings (such as "GEOM not found") are suppressed'
complete -c fdisk -s s -d 'Print summary information and exit'
complete -c fdisk -s t -d 'Test mode; do not write slice values'
complete -c fdisk -s u -d 'Update (edit) the disk\'s sector 0 slice table.  Ignored if f is given'
complete -c fdisk -s v -d 'Be verbose'
complete -c fdisk -o 1234 -d 'Operate on a single slice table entry only.  Ignored if f is given'

