# fdread
# Autogenerated from man page /usr/share/man/man1/fdread.1.gz
complete -c fdread -s q -d 'Turn on quiet mode'
complete -c fdread -s r -d 'Enable error recovery'
complete -c fdread -s d -d 'Specify the input floppy device, defaulting to /dev/fd0'
complete -c fdread -s f -d 'Value of the fill byte used for dummy blocks in the output file in recovery m…'
complete -c fdread -s o -d 'Specify the output file to be file'
complete -c fdread -s I -d 'Read numsects sector ID fields, and write out their contents to standard outp…'
complete -c fdread -s t -d 'Specify the track number (cylinder number * number of heads + head number) to…'

