# fdwrite
# Autogenerated from man page /usr/share/man/man1/fdwrite.1.gz
complete -c fdwrite -s v -d 'Toggle verbosity on stdout.  Default is ``on\'\''
complete -c fdwrite -s y -d 'Do not ask for presence of a floppy disk in the drive'
complete -c fdwrite -s f -d 'Input file to read.  If none is given, stdin is assumed'
complete -c fdwrite -s d -d 'The name of the floppy device to write to.  Default is /dev/fd0'

