# fftw-wisdom-to-conf
# Autogenerated from man page /usr/local/man/man1/fftw-wisdom-to-conf.1.gz
complete -c fftw-wisdom-to-conf -s h -l help -d 'Display help on the command-line options and usage'
complete -c fftw-wisdom-to-conf -s V -l version -d 'Print the version number and copyright information'

