# fingerd
# Autogenerated from man page /usr/share/man/man8/fingerd.8.gz
complete -c fingerd -s d -d 'Enable debugging mode'
complete -c fingerd -s k -d 'Suppress login information'
complete -c fingerd -s s -d 'Enable secure mode'
complete -c fingerd -s l -d 'Enable logging'
complete -c fingerd -s p -d 'Use an alternate program as the local information provider'

