# freebsd-version
# Autogenerated from man page /usr/share/man/man1/freebsd-version.1.gz
complete -c freebsd-version -s k -d 'Print the version and patch level of the installed kernel'
complete -c freebsd-version -s r -d 'Print the version and patch level of the running kernel'
complete -c freebsd-version -s u -d 'Print the version and patch level of the installed userland'
complete -c freebsd-version -s j -d 'Print the version and patch level of the installed userland in the given jail…'

