# freebsd-update
# Autogenerated from man page /usr/share/man/man8/freebsd-update.8.gz
complete -c freebsd-update -s b -d 'Operate on a system mounted at basedir'
complete -c freebsd-update -s d -d 'Store working files in workdir'
complete -c freebsd-update -s f -d 'Read configuration options from conffile.  (default: /etc/freebsd-update'
complete -c freebsd-update -s F -d 'Force freebsd-update Cm fetch to proceed in the case of an unfinished upgrade'
complete -c freebsd-update -s j -d 'Operate on the given jail specified by jid or name'
complete -c freebsd-update -s k -d 'Trust an RSA key with SHA256 of KEY'
complete -c freebsd-update -s r -d 'Specify the new release (e. g. , 11'
complete -c freebsd-update -s s -d 'Fetch files from the specified server or server pool'
complete -c freebsd-update -s t -d 'Mail output of cron command, if any, to address'
complete -c freebsd-update -l not-running-from-cron -d 'Force freebsd-update Cm fetch to proceed when there is no controlling tty 4'
complete -c freebsd-update -l currently-running -d 'Do not detect the currently-running release; instead, assume that the system …'

