# from
# Autogenerated from man page /usr/share/man/man1/from.1.gz
complete -c from -s c -d 'Just print a count of messages and exit'
complete -c from -s f -d 'The supplied file is examined instead of the invoker\'s mailbox'
complete -c from -s s -d 'Only mail from addresses containing the supplied string are printed'

