# fsck_msdosfs
# Autogenerated from man page /usr/share/man/man8/fsck_msdosfs.8.gz
complete -c fsck_msdosfs -s C -d 'Compatibility with the corresponding fsck 8 option (skip check if clean), def…'
complete -c fsck_msdosfs -s F -d 'Compatibility with the wrapper fsck 8 which seeks to determine whether the fi…'
complete -c fsck_msdosfs -s M -d 'Causes fsck_msdosfs to not use mmap 2 when checking a FAT32 file system'
complete -c fsck_msdosfs -s f -d 'Force fsck_msdosfs to check clean file systems when preening'
complete -c fsck_msdosfs -s n -d 'Causes fsck_msdosfs to assume no as the answer to all operator questions, exc…'
complete -c fsck_msdosfs -s p -d 'Preen the specified file systems'
complete -c fsck_msdosfs -s y -d 'Causes fsck_msdosfs to assume yes as the answer to all operator questions'

