# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.8.gz
complete -c fsck -s C -d 'Check if the clean flag is set in the superblock and skip file system checks …'
complete -c fsck -s c -d 'Specify the fstab file to use'
complete -c fsck -s d -d 'Debugging mode.  Just print the commands without executing them'
complete -c fsck -s f -d 'Force checking of file systems'
complete -c fsck -s n -d 'Causes fsck to assume no as the answer to all operator questions, except "CON…'
complete -c fsck -s p -d 'Enter preen mode'
complete -c fsck -s F -d 'Run in foreground mode'
complete -c fsck -s B -d 'Run in background mode'
complete -c fsck -s t -d 'Invoke fsck only for the comma separated list of file system types'
complete -c fsck -s v -d 'Print the commands before executing them'
complete -c fsck -s y -d 'Causes fsck to assume yes as the answer to all operator questions'
complete -c fsck -s T -d 'List of comma separated file system specific options for the specified file s…'

