# fsdb
# Autogenerated from man page /usr/share/man/man8/fsdb.8.gz
complete -c fsdb -s d -d 'Enable additional debugging output (which comes primarily from fsck 8 Ns -der…'
complete -c fsdb -s f -d 'Left for historical reasons and has no meaning'
complete -c fsdb -s r -d 'Open the file system read/only, and disables all commands that would write to…'

