# fsirand
# Autogenerated from man page /usr/share/man/man8/fsirand.8.gz
complete -c fsirand -s b -d 'Use the default block size (usually 512 bytes) instead of the value gleaned f…'
complete -c fsirand -s f -d 'Force fsirand to run even if the file system on special is not marked as clean'
complete -c fsirand -s p -d 'Print the current generation numbers for all inodes instead of generating new…'

