# fstyp
# Autogenerated from man page /usr/share/man/man8/fstyp.8.gz
complete -c fstyp -s l -d 'In addition to filesystem type, print filesystem label if available'
complete -c fstyp -s s -d 'Ignore file type'
complete -c fstyp -s u -d 'Include filesystems and devices that cannot be mounted directly by mount 8'

