# fuser
# Autogenerated from man page /usr/share/man/man1/fuser.1.gz
complete -c fuser -s c -d 'Treat files as mount points and report on any files open in the file system'
complete -c fuser -s f -d 'The report must be only for named files'
complete -c fuser -s k -d 'Send signal to reported processes SIGKILL No by default'
complete -c fuser -s M -d 'Extract values associated with the name list from the specified core instead …'
complete -c fuser -s m -d 'Search through mmapped files too'
complete -c fuser -s N -d 'Extract the name list from the specified system instead of the default, which…'
complete -c fuser -s s -d 'Use given signal name instead of default SIGKILL'
complete -c fuser -s u -d 'Write the user name associated with each process to stderr'

