# fwcontrol
# Autogenerated from man page /usr/share/man/man8/fwcontrol.8.gz
complete -c fwcontrol -s u -d 'Specify the FireWire bus number to be operated on.  The default is bus 0'
complete -c fwcontrol -s r -d 'Initiate bus reset'
complete -c fwcontrol -s t -d 'Show the topology map'
complete -c fwcontrol -s p -d 'Dump PHY registers'
complete -c fwcontrol -s c -d 'Show the configuration ROM on the node'
complete -c fwcontrol -s d -d 'Hex dump of the configuration ROM'
complete -c fwcontrol -s o -d 'Send a link-on PHY packet to the node'
complete -c fwcontrol -s s -d 'Write to the RESET_START register on the node'
complete -c fwcontrol -s l -d 'Load hex dump file of the configuration ROM and parse it'
complete -c fwcontrol -s f -d 'Force specified node to be the root node on the next bus reset by sending a P…'
complete -c fwcontrol -s g -d 'Broadcast new gap_count by sending a PHY_config packet'
complete -c fwcontrol -s i -d 'Set the PRIORITY_BUDGET register on all supported nodes'
complete -c fwcontrol -s M -d 'Explicitly specify either dv or mpeg mode for the incoming stream'
complete -c fwcontrol -s R -d 'Receive DV or MPEG TS stream and dump it to a file'
complete -c fwcontrol -s S -d 'Send a DV file as isochronous stream'
complete -c fwcontrol -s m -d 'Set default fwmem target.  Hostname will be converted to EUI64 using eui64 5'

