# fwget
# Autogenerated from man page /usr/share/man/man8/fwget.8.gz
complete -c fwget -s n -d 'Dry run, only show needed packages'
complete -c fwget -s v -d 'Be more verbose El SEE ALSO firmware 9 HISTORY The fwget utility appeared in …'

