# g-ir-generate
# Autogenerated from man page /usr/local/man/man1/g-ir-generate.1.gz
complete -c g-ir-generate -l help -d 'Show help options'
complete -c g-ir-generate -l shlib -d 'The shared library to read the symbols from'
complete -c g-ir-generate -l output -d 'Save the resulting output in FILENAME'
complete -c g-ir-generate -l version -d 'Show program\\(aqs version number and exit'

