# g-ir-doc-tool
# Autogenerated from man page /usr/local/man/man1/g-ir-doc-tool.1.gz
complete -c g-ir-doc-tool -l help -d 'Show help options'
complete -c g-ir-doc-tool -l output -d 'Save the resulting output in DIRECTORY'
complete -c g-ir-doc-tool -l format -d 'Output format.  One of devdocs, mallard or sections'
complete -c g-ir-doc-tool -l language -d 'Output language.  One of c, python, or gjs'
complete -c g-ir-doc-tool -l add-include-path -d 'Adds a directory which will be used to find includes inside the GIR format'
complete -c g-ir-doc-tool -l version -d 'Show program\\(aqs version number and exit'
complete -c g-ir-doc-tool -l write-sections-file -d 'Backwards-compatible equivalent to -f sections'

