# g-ir-compiler
# Autogenerated from man page /usr/local/man/man1/g-ir-compiler.1.gz
complete -c g-ir-compiler -l help -d 'Show help options'
complete -c g-ir-compiler -l output -d 'Save the resulting output in FILENAME'
complete -c g-ir-compiler -l verbose -d 'Show verbose messages'
complete -c g-ir-compiler -l debug -d 'Show debug messages'
complete -c g-ir-compiler -l includedir -d 'Adds a directory which will be used to find includes inside the GIR format'
complete -c g-ir-compiler -l module -d FIXME
complete -c g-ir-compiler -l shared-library -d 'Specifies the shared library where the symbols in the typelib can be found'
complete -c g-ir-compiler -l version -d 'Show program\\(aqs version number and exit'

