# gconcat
# Autogenerated from man page /usr/share/man/man8/gconcat.8.gz
complete -c gconcat -s h -d 'Hardcode providers\' names in metadata'
complete -c gconcat -s f -d 'Stop the given device even if it is opened.  El destroy Same as stop'
complete -c gconcat -s v -d 'Be more verbose'

