# gcore
# Autogenerated from man page /usr/share/man/man1/gcore.1.gz
complete -c gcore -s c -d 'Write the core file to the specified file instead of core. <pid>'
complete -c gcore -s f -d 'Dumps all available segments, excluding only malformed and undumpable segments'
complete -c gcore -s k -d 'Use the ptrace 2 PT_COREDUMP kernel facility to write the core dump, instead …'

