# gdk-pixbuf-query-loaders
# Autogenerated from man page /usr/local/man/man1/gdk-pixbuf-query-loaders.1.gz
complete -c gdk-pixbuf-query-loaders -l update-cache -d 'Writes the output to the default cache location instead of the standard output'

