# gensnmptree
# Autogenerated from man page /usr/share/man/man1/gensnmptree.1.gz
complete -c gensnmptree -s d -d 'Switch on debugging'
complete -c gensnmptree -s E -d 'Extract enumerations and bit constructs'
complete -c gensnmptree -s e -d 'gensnmptree expects MIB variable names (only the last component) on its comma…'
complete -c gensnmptree -s F -d 'emit definitions for C-functions includeable in a C-file that do some basic s…'
complete -c gensnmptree -s f -d 'emit definitions for inline C-functions that do some basic stuff on enums lik…'
complete -c gensnmptree -s h -d 'Print a short help page'
complete -c gensnmptree -s I -d 'Add the named directory to the include path just before the standard include …'
complete -c gensnmptree -s i -d 'Read from the named file instead of standard input'
complete -c gensnmptree -s l -d 'Generate local preprocessor includes'
complete -c gensnmptree -s t -d 'Instead of normal output print the resulting tree'
complete -c gensnmptree -s p -d 'Prefix the file names and the table name with prefix'

