# getextattr
# Autogenerated from man page /usr/share/man/man8/getextattr.8.gz
complete -c getextattr -s f -d '(Force'
complete -c getextattr -s h -d '(No follow'
complete -c getextattr -s i -d '(From stdin. ) Read attribute data from stdin instead of as an argument'
complete -c getextattr -s n -d '( NUL Ns -terminate. ) NUL Ns -terminate the extent content written out'
complete -c getextattr -s q -d '(Quiet. ) Do not print out the pathname and suppress error messages'
complete -c getextattr -s s -d '(Stringify. ) Escape nonprinting characters and put quotes around the output'
complete -c getextattr -s x -d '(Hex. ) Print the output in hexadecimal'

