# getfacl
# Autogenerated from man page /usr/share/man/man1/getfacl.1.gz
complete -c getfacl -s d -d 'The operation applies to the default ACL of a directory instead of the access…'
complete -c getfacl -s h -d 'If the target of the operation is a symbolic link, return the ACL from the sy…'
complete -c getfacl -s i -d 'For NFSv4 ACLs, append numerical ID at the end of each entry containing user …'
complete -c getfacl -s n -d 'Display user and group IDs numerically rather than converting to a user or gr…'
complete -c getfacl -s q -d 'Do not write commented information about file name and ownership'
complete -c getfacl -s v -d 'For NFSv4 ACLs, display access mask and flags in a verbose form'

