# ggated
# Autogenerated from man page /usr/share/man/man8/ggated.8.gz
complete -c ggated -s a -d 'Specifies an IP address to bind to'
complete -c ggated -s h -d 'Print available options'
complete -c ggated -s n -d 'Do not use TCP_NODELAY option on TCP sockets'
complete -c ggated -s p -d 'Port on which ggated listens for connections.  Default is 3080'
complete -c ggated -s F -d 'PID file that ggated uses'
complete -c ggated -s R -d 'Size of receive buffer to use.  Default is 131072 (128kB)'
complete -c ggated -s S -d 'Size of send buffer to use.  Default is 131072 (128kB)'
complete -c ggated -s v -d 'Do not fork, run in foreground and print debug information on standard output'

