# ggatec
# Autogenerated from man page /usr/share/man/man8/ggatec.8.gz
complete -c ggatec -s f -d 'Forcibly destroy ggatec ggate provider (cancels all pending requests)'
complete -c ggatec -s n -d 'Do not use TCP_NODELAY option on TCP sockets'
complete -c ggatec -s o -d 'Specify permissions to use when opening the file or device: read-only ro, wri…'
complete -c ggatec -s p -d 'Port to connect to on the remote host.  Default is 3080'
complete -c ggatec -s q -d 'Number of pending I/O requests that can be queued before they will start to b…'
complete -c ggatec -s R -d 'Size of receive buffer to use.  Default is 131072 (128kB)'
complete -c ggatec -s S -d 'Size of send buffer to use.  Default is 131072 (128kB)'
complete -c ggatec -s s -d 'Sector size for ggatec ggate provider'
complete -c ggatec -s t -d 'Number of seconds to wait before an I/O request will be canceled'
complete -c ggatec -s u -d 'Unit number to use'
complete -c ggatec -s v -d 'Do not fork, run in foreground and print debug information on standard output'

