# ggatel
# Autogenerated from man page /usr/share/man/man8/ggatel.8.gz
complete -c ggatel -s f -d 'Forcibly destroy ggatel ggate provider (cancels all pending requests)'
complete -c ggatel -s o -d 'Specify permissions to use when opening the file or device: read-only ro, wri…'
complete -c ggatel -s s -d 'Sector size for ggatel ggate provider'
complete -c ggatel -s t -d 'Number of seconds to wait before an I/O request will be canceled'
complete -c ggatel -s u -d 'Unit number to use'
complete -c ggatel -s v -d 'Do not fork, run in foreground and print debug information on standard output'

