# git-subtree
# Autogenerated from man page /usr/local/man/man1/git-subtree.1.gz
complete -c git-subtree -l squash -d 'merge <local-commit> [<repository>] Merge recent changes up to <local-commit>…'
complete -c git-subtree -l annotate -d 'git merge and friends will work as expected.  When a previous merge with'
complete -c git-subtree -s q -l quiet -d 'Suppress unnecessary output messages on stderr'
complete -c git-subtree -s d -l debug -d 'Produce even more unnecessary output messages on stderr'
complete -c git-subtree -s P -l prefix -d 'Specify the path in the repository to the subtree you want to manipulate'
complete -c git-subtree -s m -l message -d 'Specify <message> as the commit message for the merge commit'
complete -c git-subtree -l rejoin
complete -c git-subtree -s b -l branch -d 'After generating the synthetic history, create a new branch called <branch> t…'
complete -c git-subtree -l ignore-joins -d 'If you use'
complete -c git-subtree -l onto -d 'If your subtree was originally imported using something other than git subtre…'

