# gjournal
# Autogenerated from man page /usr/share/man/man8/gjournal.8.gz
complete -c gjournal -s c -d 'Checksum journal records'
complete -c gjournal -s f -d 'May be used to convert an existing file system to use gjournal, but only if t…'
complete -c gjournal -s h -d 'Hardcode provider names in metadata'
complete -c gjournal -s s -d 'Specifies size of the journal if only one provider is used for both data and …'
complete -c gjournal -s v -d 'Be more verbose'

