# gmirror
# Autogenerated from man page /usr/share/man/man8/gmirror.8.gz
complete -c gmirror -s b -d 'Specifies balance algorithm to use, one of: -tag -width "'
complete -c gmirror -s F -d 'Do not synchronize after a power failure or system crash'
complete -c gmirror -s h -d 'Hardcode providers\' names in metadata'
complete -c gmirror -s n -d 'Turn off autosynchronization of stale components'
complete -c gmirror -s s -d 'When using the split balance algorithm and an I/O READ request is bigger than…'
complete -c gmirror -s a -d 'Turn on autosynchronization of stale components'
complete -c gmirror -s d -d 'Do not hardcode providers\' names in metadata'
complete -c gmirror -s f -d 'Synchronize device after a power failure or system crash'
complete -c gmirror -s p -d 'Specifies priority for the given component prov'
complete -c gmirror -s i -d 'Mark component(s) as inactive immediately after insertion'
complete -c gmirror -s v -d 'Be more verbose'

