# gmountver
# Autogenerated from man page /usr/share/man/man8/gmountver.8.gz
complete -c gmountver -s f -d 'Force the removal of the specified mountver device'
complete -c gmountver -s v -d 'Be more verbose'

