# gnop
# Autogenerated from man page /usr/share/man/man8/gnop.8.gz
complete -c gnop -s c -d 'Specifies the number of I/O requests to allow before setting the read, write …'
complete -c gnop -s d -d 'Specifies the delay of the requests in milliseconds'
complete -c gnop -s e -d 'Specifies the error number to return on failure'
complete -c gnop -s f -d 'Force the removal of the specified provider'
complete -c gnop -s o -d 'Where to begin on the original provider'
complete -c gnop -s p -d 'Value of the stripesize property of the transparent provider'
complete -c gnop -s P -d 'Value of the stripeoffset property of the transparent provider'
complete -c gnop -s q -d 'Specifies read delay probability in percent'
complete -c gnop -s r -d 'Specifies read failure probability in percent'
complete -c gnop -s s -d 'Size of the transparent provider'
complete -c gnop -s S -d 'Sector size of the transparent provider'
complete -c gnop -s w -d 'Specifies write failure probability in percent'
complete -c gnop -s v -d 'Be more verbose'
complete -c gnop -s x -d 'Specifies write delay probability in percent'
complete -c gnop -s z -d 'Physical path of the transparent provider'
complete -c gnop -s Z -d 'The name of the new provider.  The suffix '

