# gpioctl
# Autogenerated from man page /usr/share/man/man8/gpioctl.8.gz
complete -c gpioctl -s c -d 'Configure pin by setting provided flags'
complete -c gpioctl -s f -d 'GPIO controller device to use If not specified, defaults to /dev/gpioc0'
complete -c gpioctl -s l -d 'list available pins'
complete -c gpioctl -s n -d 'set the name used to describe the pin'
complete -c gpioctl -s t -d 'toggle value of provided pin'
complete -c gpioctl -s v -d 'be verbose: for each listed pin print current configuration'
complete -c gpioctl -s p -d 'Force pin to be interpreted as a pin number'
complete -c gpioctl -s N -d 'Force pin to be interpreted as a pin name El EXAMPLES -bullet It List pins av…'

