# graid3
# Autogenerated from man page /usr/share/man/man8/graid3.8.gz
complete -c graid3 -s F -d 'Do not synchronize after a power failure or system crash'
complete -c graid3 -s h -d 'Hardcode providers\' names in metadata'
complete -c graid3 -s n -d 'Turn off autosynchronization of stale components'
complete -c graid3 -s r -d 'Use parity component for reading in round-robin fashion'
complete -c graid3 -s s -d 'Manually specify array block size'
complete -c graid3 -s w -d 'Use verify reading feature'
complete -c graid3 -s a -d 'Turn on autosynchronization of stale components'
complete -c graid3 -s d -d 'Do not hardcode providers\' names in metadata'
complete -c graid3 -s f -d 'Synchronize device after a power failure or system crash'
complete -c graid3 -s R -d 'Turn off round-robin reading'
complete -c graid3 -s W -d 'Turn off verify reading.  El rebuild Rebuild the given component forcibly'
complete -c graid3 -s v -d 'Be more verbose'

