# graid
# Autogenerated from man page /usr/share/man/man8/graid.8.gz
complete -c graid -s f -d 'Enforce specified configuration creation if it is officially unsupported, but…'
complete -c graid -s o -d 'Specifies metadata format options'
complete -c graid -s S -d 'Use size bytes on each component for this volume'
complete -c graid -s s -d 'Specifies strip size in bytes.  Defaults to 131072'
complete -c graid -s v -d 'Be more verbose'

