# growfs
# Autogenerated from man page /usr/share/man/man8/growfs.8.gz
complete -c growfs -s N -d 'Test mode'
complete -c growfs -s y -d 'Causes growfs to assume yes as the answer to all operator questions'
complete -c growfs -s s -d 'Determines the size of the file system after enlarging in sectors'

