# gshsec
# Autogenerated from man page /usr/share/man/man8/gshsec.8.gz
complete -c gshsec -s f -d 'Force the removal of the specified shared secret device'
complete -c gshsec -s h -d 'Hardcode providers\' names in metadata'
complete -c gshsec -s v -d 'Be more verbose'

