# gssd
# Autogenerated from man page /usr/share/man/man8/gssd.8.gz
complete -c gssd -s d -d 'Run in debug mode.  In this mode, gssd will not fork when it starts'
complete -c gssd -s h -d 'Enable support for host-based initiator credentials'
complete -c gssd -s v -d 'Run in verbose mode'
complete -c gssd -s s -d 'Look for an appropriate credential cache file in this list of directories'
complete -c gssd -s c -d 'Set a file-substring for the credential cache file names'
complete -c gssd -s r -d 'Use Kerberos credentials for this realm when searching for credentials in dir…'

