# gstat
# Autogenerated from man page /usr/share/man/man8/gstat.8.gz
complete -c gstat -s a -d 'Only display providers that are at least 0. 1% busy'
complete -c gstat -s b -d 'Batch mode.  Collect numbers, print and exit.  Default if stdout is not a tty'
complete -c gstat -s B -d 'Endless batch mode'
complete -c gstat -s c -d 'Enable display of geom 4 consumers too'
complete -c gstat -s C -d 'CSV output mode'
complete -c gstat -s d -d 'Enable display of statistics for delete BIO_DELETE operations'
complete -c gstat -s f -d 'A regular expression that can be used to only show statistics for some devices'
complete -c gstat -s o -d 'Enable display of statistics for other operations BIO_FLUSH'
complete -c gstat -s s -d 'Enable blocks\' size statistics'
complete -c gstat -s I -d 'Refresh the gstat display every interval microseconds'
complete -c gstat -s p -d 'Only display physical providers (those with rank of 1)'

