# gstripe
# Autogenerated from man page /usr/share/man/man8/gstripe.8.gz
complete -c gstripe -s f -d 'Force the removal of the specified striped device'
complete -c gstripe -s h -d 'Hardcode providers\' names in metadata'
complete -c gstripe -s s -d 'Specifies size of stripe block in bytes'
complete -c gstripe -s v -d 'Be more verbose'

