# gtk-query-immodules-3.0
# Autogenerated from man page /usr/local/man/man1/gtk-query-immodules-3.0.1.gz
complete -c 'gtk-query-immodules-3.0' -l update-cache -d 'Write the output to the default cache location instead of stdout'

