# gtk3-demo
# Autogenerated from man page /usr/local/man/man1/gtk3-demo.1.gz
complete -c gtk3-demo -s h -l help -d 'Show help options'
complete -c gtk3-demo -l list -d 'List available examples'
complete -c gtk3-demo -o run -d 'Run the named example.  Use --list to see the available examples'
complete -c gtk3-demo -l autoquit -d 'Quit after a short timeout.  This is intended for use with --run, e. g'
complete -c gtk3-demo -l run

