# gunion
# Autogenerated from man page /usr/share/man/man8/gunion.8.gz
complete -c gunion -s o -d 'Where to begin on the original provider'
complete -c gunion -s s -d 'Size of the transparent provider'
complete -c gunion -s S -d 'Sector size of the transparent provider'
complete -c gunion -s v -d 'Be more verbose'
complete -c gunion -s Z -d 'The name of the new provider.  The suffix '
complete -c gunion -s f -d 'Force the removal of the specified provider'
complete -c gunion -s r -d 'Reboot the system at the completion of the commit operation'

