# gunzip
# Autogenerated from man page /usr/share/man/man1/gunzip.1.gz
complete -c gunzip -s 1
complete -c gunzip -s 2
complete -c gunzip -s 9 -d 'These options change the compression level used, with the 1 option being the …'
complete -c gunzip -s c -d 'This option specifies that output will go to the standard output stream, leav…'
complete -c gunzip -s d -d 'This option selects decompression rather than compression'
complete -c gunzip -s f -d 'This option turns on force mode'
complete -c gunzip -s h -d 'This option prints a usage summary and exits'
complete -c gunzip -s k -d 'This option prevents gunzip from deleting input files after (de)compression'
complete -c gunzip -s L -d 'This option prints gunzip license'
complete -c gunzip -s l -d 'This option displays information about the file\'s compressed and uncompressed…'
complete -c gunzip -s N -d 'This option causes the stored filename in the input file to be used as the ou…'
complete -c gunzip -s n -d 'This option stops the filename and timestamp from being stored in the output …'
complete -c gunzip -s q -d 'With this option, no warnings or errors are printed'
complete -c gunzip -s r -d 'This option is used to gunzip the files in a directory tree individually, usi…'
complete -c gunzip -s S -d 'This option changes the default suffix from . gz to suffix'
complete -c gunzip -s t -d 'This option will test compressed files for integrity'
complete -c gunzip -s V -d 'This option prints the version of the gunzip program'
complete -c gunzip -s v -d 'This option turns on verbose mode, which prints the compression ratio for eac…'

