# gvinum
# Autogenerated from man page /usr/share/man/man8/gvinum.8.gz
complete -c gvinum -s f -d 'The f force option overrides safety checks'
complete -c gvinum -s r -d 'The r recursive option applies the command recursively to subordinate objects'
complete -c gvinum -s v -d 'The v verbose option provides more detailed output'
complete -c gvinum -s V -d 'The V "very verbose" option provides even more detailed output than v'

