# gvirstor
# Autogenerated from man page /usr/share/man/man8/gvirstor.8.gz
complete -c gvirstor -s f -d 'Force the removal of the specified virtual device'
complete -c gvirstor -s h -d 'Hardcode providers\' names in metadata'
complete -c gvirstor -s v -d 'Be more verbose'

