# gzcat
# Autogenerated from man page /usr/share/man/man1/gzcat.1.gz
complete -c gzcat -s 1
complete -c gzcat -s 2
complete -c gzcat -s 9 -d 'These options change the compression level used, with the 1 option being the …'
complete -c gzcat -s c -d 'This option specifies that output will go to the standard output stream, leav…'
complete -c gzcat -s d -d 'This option selects decompression rather than compression'
complete -c gzcat -s f -d 'This option turns on force mode'
complete -c gzcat -s h -d 'This option prints a usage summary and exits'
complete -c gzcat -s k -d 'This option prevents gzcat from deleting input files after (de)compression'
complete -c gzcat -s L -d 'This option prints gzcat license'
complete -c gzcat -s l -d 'This option displays information about the file\'s compressed and uncompressed…'
complete -c gzcat -s N -d 'This option causes the stored filename in the input file to be used as the ou…'
complete -c gzcat -s n -d 'This option stops the filename and timestamp from being stored in the output …'
complete -c gzcat -s q -d 'With this option, no warnings or errors are printed'
complete -c gzcat -s r -d 'This option is used to gzcat the files in a directory tree individually, usin…'
complete -c gzcat -s S -d 'This option changes the default suffix from . gz to suffix'
complete -c gzcat -s t -d 'This option will test compressed files for integrity'
complete -c gzcat -s V -d 'This option prints the version of the gzcat program'
complete -c gzcat -s v -d 'This option turns on verbose mode, which prints the compression ratio for eac…'

