# gzip
# Autogenerated from man page /usr/share/man/man1/gzip.1.gz
complete -c gzip -s 1
complete -c gzip -s 2
complete -c gzip -s 9 -d 'These options change the compression level used, with the 1 option being the …'
complete -c gzip -s c -d 'This option specifies that output will go to the standard output stream, leav…'
complete -c gzip -s d -d 'This option selects decompression rather than compression'
complete -c gzip -s f -d 'This option turns on force mode'
complete -c gzip -s h -d 'This option prints a usage summary and exits'
complete -c gzip -s k -d 'This option prevents gzip from deleting input files after (de)compression'
complete -c gzip -s L -d 'This option prints gzip license'
complete -c gzip -s l -d 'This option displays information about the file\'s compressed and uncompressed…'
complete -c gzip -s N -d 'This option causes the stored filename in the input file to be used as the ou…'
complete -c gzip -s n -d 'This option stops the filename and timestamp from being stored in the output …'
complete -c gzip -s q -d 'With this option, no warnings or errors are printed'
complete -c gzip -s r -d 'This option is used to gzip the files in a directory tree individually, using…'
complete -c gzip -s S -d 'This option changes the default suffix from . gz to suffix'
complete -c gzip -s t -d 'This option will test compressed files for integrity'
complete -c gzip -s V -d 'This option prints the version of the gzip program'
complete -c gzip -s v -d 'This option turns on verbose mode, which prints the compression ratio for eac…'

