# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
complete -c halt -s c -d 'The system will turn off the power and then turn it back on if it can'
complete -c halt -s d -d 'The system is requested to create a crash dump'
complete -c halt -s k -d 'Boot the specified kernel on the next system boot'
complete -c halt -s l -d 'The halt or reboot is not logged to the system log'
complete -c halt -s N -d 'The file system cache is not flushed during the initial process clean-up, how…'
complete -c halt -s n -d 'The file system cache is not flushed'
complete -c halt -s p -d 'The system will turn off the power if it can'
complete -c halt -s q -d 'The system is halted or restarted quickly and ungracefully, and only the flus…'
complete -c halt -s r -d 'The system kills all processes, unmounts all filesystems, mounts the new root…'

