# hastctl
# Autogenerated from man page /usr/share/man/man8/hastctl.8.gz
complete -c hastctl -s e -d 'Size of an extent.  Extent is a block which is used for synchronization'
complete -c hastctl -s k -d 'Maximum number of dirty extents to keep dirty all the time'
complete -c hastctl -s m -d 'Size of the smaller provider used as backend storage on both nodes'
complete -c hastctl -s c -d 'Specify alternative location of the configuration file'
complete -c hastctl -s d -d 'Print debugging information'

