# hastd
# Autogenerated from man page /usr/share/man/man8/hastd.8.gz
complete -c hastd -s c -d 'Specify alternative location of the configuration file'
complete -c hastd -s d -d 'Print or log debugging information'
complete -c hastd -s F -d 'Start the hastd daemon in the foreground'
complete -c hastd -s h -d 'Print the hastd usage message'
complete -c hastd -s P -d 'Specify alternative location of a file where main process PID will be stored'

