# hccontrol
# Autogenerated from man page /usr/share/man/man8/hccontrol.8.gz
complete -c hccontrol -s h -d 'Display usage message and exit'
complete -c hccontrol -s N -d 'Show Bluetooth addresses as numbers'
complete -c hccontrol -s n -d 'Connect to the specified HCI Netgraph node'

