# hcsecd
# Autogenerated from man page /usr/share/man/man8/hcsecd.8.gz
complete -c hcsecd -s d -d 'Do not detach from the controlling terminal'
complete -c hcsecd -s f -d 'Specify the name of the configuration file'
complete -c hcsecd -s h -d 'Display usage message and exit.  El FILES -tag -width "'

