# hd
# Autogenerated from man page /usr/share/man/man1/hd.1.gz
complete -c hd -s b -d 'One-byte octal display'
complete -c hd -s c -d 'One-byte character display'
complete -c hd -s C -d 'Canonical hex+ASCII display'
complete -c hd -s d -d 'Two-byte decimal display'
complete -c hd -s e -d 'Specify a format string to be used for displaying data'
complete -c hd -s f -d 'Specify a file that contains one or more newline separated format strings'
complete -c hd -s n -d 'Interpret only length bytes of input'
complete -c hd -s o -d 'Two-byte octal display'
complete -c hd -s s -d 'Skip offset bytes from the beginning of the input'
complete -c hd -s v -d 'Cause hd to display all input data'
complete -c hd -s x -d 'Two-byte hexadecimal display'

