# head
# Autogenerated from man page /usr/share/man/man1/head.1.gz
complete -c head -s c -d 'Print bytes of each of the specified files'
complete -c head -s n -d 'Print count lines of each of the specified files'
complete -c head -s q -d 'Suppresses printing of headers when multiple files are being examined'
complete -c head -s v -d 'Prepend each file with a header'

