# hexdump
# Autogenerated from man page /usr/share/man/man1/hexdump.1.gz
complete -c hexdump -s b -d 'One-byte octal display'
complete -c hexdump -s c -d 'One-byte character display'
complete -c hexdump -s C -d 'Canonical hex+ASCII display'
complete -c hexdump -s d -d 'Two-byte decimal display'
complete -c hexdump -s e -d 'Specify a format string to be used for displaying data'
complete -c hexdump -s f -d 'Specify a file that contains one or more newline separated format strings'
complete -c hexdump -s n -d 'Interpret only length bytes of input'
complete -c hexdump -s o -d 'Two-byte octal display'
complete -c hexdump -s s -d 'Skip offset bytes from the beginning of the input'
complete -c hexdump -s v -d 'Cause hexdump to display all input data'
complete -c hexdump -s x -d 'Two-byte hexadecimal display'

