# hostapd
# Autogenerated from man page /usr/share/man/man8/hostapd.8.gz
complete -c hostapd -s d -d 'Enable debugging messages'
complete -c hostapd -s h -d 'Show help text'
complete -c hostapd -s t -d 'Include timestamps in debugging output'
complete -c hostapd -s v -d 'Display version information on the terminal and exit'
complete -c hostapd -s B -d 'Detach from the controlling terminal and run as a daemon process in the backg…'
complete -c hostapd -s K -d 'Include key information in debugging output'
complete -c hostapd -s P -d 'Store PID in pidfile'

