# hprop
# Autogenerated from man page /usr/share/man/man8/hprop.8.gz
complete -c hprop -s m -d 'Where to find the master key to encrypt or decrypt keys with'
complete -c hprop -s d -d 'The database to be propagated'
complete -c hprop -l source -d 'Specifies the type of the source database'
complete -c hprop -s R -d 'Local realm override'
complete -c hprop -s D -d 'The encryption keys in the database can either be in clear, or encrypted with…'
complete -c hprop -s E -d 'This option transmits the database with encrypted keys'
complete -c hprop -s n -d 'Dump the database on stdout, in a format that can be fed to hpropd'

