# hpropd
# Autogenerated from man page /usr/share/man/man8/hpropd.8.gz
complete -c hpropd -s d -d database
complete -c hpropd -s n -d 'read from stdin'
complete -c hpropd -l print -d 'print dump to stdout'
complete -c hpropd -s i -d 'not started from inetd'
complete -c hpropd -s k -d 'keytab to use for authentication'
complete -c hpropd -s 4 -d 'create v4 type DB El SEE ALSO hprop 8'

