# hv_kvp_daemon
# Autogenerated from man page /usr/share/man/man8/hv_kvp_daemon.8.gz
complete -c hv_kvp_daemon -s d -d 'Run as regular process instead of a daemon for debugging purpose'
complete -c hv_kvp_daemon -s n -d 'Generate debugging output'

