# hyprctl
# Autogenerated from man page /usr/local/man/man1/hyprctl.1.gz
complete -c hyprctl -l batch -d 'Specify a batch of commands to execute'
complete -c hyprctl -s j -d 'Outputs information in JSON'

