# i2c
# Autogenerated from man page /usr/share/man/man8/i2c.8.gz
complete -c i2c -s a -d '7-bit address on the I2C device to operate on (hex)'
complete -c i2c -s b -d 'binary mode - when performing a read operation, the data read from the device…'
complete -c i2c -s c -d 'number of bytes to transfer (decimal)'
complete -c i2c -s d -d 'transfer direction: r - read, w - write'
complete -c i2c -s f -d 'I2C bus to use (default is /dev/iic0)'
complete -c i2c -s i -d 'Interpreted mode'
complete -c i2c -s h -d Help
complete -c i2c -s m -d 'addressing mode, i. e'
complete -c i2c -s n -d 'address(es) to be skipped during bus scan'
complete -c i2c -s o -d 'offset within the device for data transfer (hex).  The default is zero'
complete -c i2c -s r -d 'reset the controller'
complete -c i2c -s s -d 'scan the bus for devices'
complete -c i2c -s v -d 'be verbose'
complete -c i2c -s w -d 'device offset width (in bits)'

