# ibv_ud_pingpong
# Autogenerated from man page /usr/share/man/man1/ibv_ud_pingpong.1.gz
complete -c ibv_ud_pingpong -s p -l port -d 'use TCP port PORT for initial synchronization (default 18515)'
complete -c ibv_ud_pingpong -s d -l ib-dev -d 'use IB device DEVICE (default first device found)'
complete -c ibv_ud_pingpong -s i -l ib-port -d 'use IB port PORT (default port 1)'
complete -c ibv_ud_pingpong -s s -l size -d 'ping-pong messages of size SIZE (default 2048)'
complete -c ibv_ud_pingpong -s r -l rx-depth -d 'post DEPTH receives at a time (default 500)'
complete -c ibv_ud_pingpong -s n -l iters -d 'perform ITERS message exchanges (default 1000)'
complete -c ibv_ud_pingpong -s l -l sl -d 'send messages with service level SL (default 0)'
complete -c ibv_ud_pingpong -s e -l events -d 'sleep while waiting for work completion events (default is to poll for comple…'
complete -c ibv_ud_pingpong -s g -l gid-idx -d 'local port GIDINDEX'

