# ibv_asyncwatch
# Autogenerated from man page /usr/share/man/man1/ibv_asyncwatch.1.gz
complete -c ibv_asyncwatch -s d -l ib-dev -d 'use IB device DEVICE (default first device found)'
complete -c ibv_asyncwatch -s h -l help -d 'Print a help text and exit'

