# ibv_devinfo
# Autogenerated from man page /usr/share/man/man1/ibv_devinfo.1.gz
complete -c ibv_devinfo -s d -l ib-dev -d 'use IB device DEVICE (default first device found)'
complete -c ibv_devinfo -s i -l ib-port -d 'query port PORT (default all ports)'
complete -c ibv_devinfo -s l -l list -d 'only list names of RDMA devices'
complete -c ibv_devinfo -s v -l verbose -d 'print all available information about RDMA devices'

