# id
# Autogenerated from man page /usr/share/man/man1/id.1.gz
complete -c id -s A -d 'Display the process audit user ID and other process audit properties, which r…'
complete -c id -s G -d 'Display the different group IDs (effective, real and supplementary) as white-…'
complete -c id -s M -d 'Display the MAC label of the current process'
complete -c id -s P -d 'Display the id as a password file entry'
complete -c id -s a -d 'Ignored for compatibility with other id implementations'
complete -c id -s c -d 'Display current login class'
complete -c id -s g -d 'Display the effective group ID as a number'
complete -c id -s n -d 'Display the name of the user or group ID for the G, g and u options instead o…'
complete -c id -s p -d 'Make the output human-readable'
complete -c id -s r -d 'Display the real ID for the g and u options instead of the effective ID'
complete -c id -s u -d 'Display the effective user ID as a number'

