# ident
# Autogenerated from man page /usr/share/man/man1/ident.1.gz
complete -c ident -s q -d 'Quiet mode: suppress warnings if no pattern found'
complete -c ident -s V -d 'Do nothing, added for compatibility with GNU ident'

