# ifmcstat
# Autogenerated from man page /usr/share/man/man8/ifmcstat.8.gz
complete -c ifmcstat -s i -d 'specifies the interface to be displayed'
complete -c ifmcstat -s f -d 'specifies the address family to be displayed; inet, inet6 and link are suppor…'
complete -c ifmcstat -s v -d 'specifies that link-layer memberships should be printed; they are suppressed …'
complete -c ifmcstat -s K -d 'attempts to use kvm 3 to retrieve the multicast group information'
complete -c ifmcstat -s M -d 'extracts values associated with the name list from the specified core, instea…'
complete -c ifmcstat -s N -d 'extracts the name list from the specified kernel instead of the default, whic…'

