# iostat
# Autogenerated from man page /usr/share/man/man8/iostat.8.gz
complete -c iostat -s C -d 'Display CPU statistics.  This is on by default, unless d or x is specified'
complete -c iostat -s c -d 'Repeat the display count times'
complete -c iostat -s d -d 'Display only device statistics'
complete -c iostat -s h -d 'Put iostat in top mode'
complete -c iostat -s I -d 'Display total statistics for a given time period, rather than average statist…'
complete -c iostat -s K -d 'In the blocks transferred display (-o), display block count in kilobytes rath…'
complete -c iostat -s M -d 'Extract values associated with the name list from the specified core instead …'
complete -c iostat -s N -d 'Extract the name list from the specified system instead of the default /boot/…'
complete -c iostat -s n -d 'Display up to devs number of devices'
complete -c iostat -s o -d 'Display old-style iostat device statistics'
complete -c iostat -s T -d 'Display TTY statistics.  This is on by default, unless d or x is specified'
complete -c iostat -s t -d 'Specify which types of devices to display'
complete -c iostat -s w -d 'Pause wait seconds between each display'
complete -c iostat -s x -d 'Show extended disk statistics'
complete -c iostat -s z -d 'If x is specified, omit lines for devices with no activity'

