# iovctl
# Autogenerated from man page /usr/share/man/man8/iovctl.8.gz
complete -c iovctl -s C -d 'Enable SR-IOV on the specified PF device and create VF children'
complete -c iovctl -s d -d 'Specify the PF device to use for the given operation'
complete -c iovctl -s D -d 'Delete all VF children of the specified PF device'
complete -c iovctl -s f -d 'Specify the pathname of the configuration file'
complete -c iovctl -s n -d 'Perform a dry-run'
complete -c iovctl -s S -d 'Read the configuration schema from the specified device and print its content…'

