# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1.gz
complete -c ipcrm -s v -d 'If specified once with -W or with -1 for an object, it will show all removed …'
complete -c ipcrm -s W -d 'Try to wipe all specified message queues, semaphores and shared memory segmen…'
complete -c ipcrm -s y -d 'Use the kvm 3 interface instead of the sysctl 3 interface to extract the requ…'
complete -c ipcrm -s q -d 'Remove the message queue associated with the ID msqid from the system'
complete -c ipcrm -s m -d 'Mark the shared memory segment associated with ID shmid for removal'
complete -c ipcrm -s s -d 'Remove the semaphore set associated with ID semid from the system'
complete -c ipcrm -s Q -d 'Remove the message queue associated with key msgkey from the system'
complete -c ipcrm -s M -d 'Mark the shared memory segment associated with key shmkey for removal'
complete -c ipcrm -s S -d 'Remove the semaphore set associated with key semkey from the system'

