# ipfs
# Autogenerated from man page /usr/share/man/man8/ipfs.8.gz
complete -c ipfs -s d -d 'Change the default directory used with  -R and  -W options for saving state i…'
complete -c ipfs -s n -d 'Don\'t actually take any action that would affect information stored in the ke…'
complete -c ipfs -s v -d 'Provides a verbose description of what\'s being done'
complete -c ipfs -s i -d 'Change all instances of interface name ifname1 in the state save file to ifna…'
complete -c ipfs -s N -d 'Operate on NAT information'
complete -c ipfs -s S -d 'Operate on filtering state information'
complete -c ipfs -s u -d 'Unlock state tables in the kernel'
complete -c ipfs -s l -d 'Lock state tables in the kernel'
complete -c ipfs -s r -d 'Read information in from the specified file and load it into the kernel'
complete -c ipfs -s w -d 'Write information out to the specified file and from the kernel'
complete -c ipfs -s R -d 'Restores all saved state information, if any, from two files, ipstate'
complete -c ipfs -s W -d 'options for saving state information'

