# ipfwpcap
# Autogenerated from man page /usr/share/man/man8/ipfwpcap.8.gz
complete -c ipfwpcap -s d -d 'Turns on extra debugging messages'
complete -c ipfwpcap -s r -d 'Writes packets back to the divert 4 socket'
complete -c ipfwpcap -o rr -d 'Indicates that it is okay to quit if maxbytes or maxpkts are reached'
complete -c ipfwpcap -s b -d 'Stop dumping after maxbytes bytes'
complete -c ipfwpcap -s p -d 'Stop dumping after maxpkt packets'
complete -c ipfwpcap -s P -d 'File to store PID number in.  Default is /var/run/ipwfpcap. portnr. pid'

