# ipnat
# Autogenerated from man page /usr/share/man/man8/ipnat.8.gz
complete -c ipnat -s C -d 'delete all entries in the current NAT rule listing (NAT rules)'
complete -c ipnat -s d -d 'Enable printing of some extra debugging information'
complete -c ipnat -s F -d 'delete all active entries in the current NAT translation table (currently act…'
complete -c ipnat -s h -d 'Print number of hits for each MAP/Redirect filter'
complete -c ipnat -s l -d 'Show the list of current NAT table entry mappings'
complete -c ipnat -s n -d 'This flag (no-change) prevents ipf from actually making any ioctl calls or do…'
complete -c ipnat -s p -d 'This flag is used with the -r flag to cause any active NAT sessions that were…'
complete -c ipnat -s r -d 'Remove matching NAT rules rather than add them to the internal lists'
complete -c ipnat -s s -d 'Retrieve and display NAT statistics'
complete -c ipnat -s v -d 'Turn verbose mode on'

