# iprop-log
# Autogenerated from man page /usr/share/man/man8/iprop-log.8.gz
complete -c iprop-log -l version
complete -c iprop-log -s h -d 'El Pp command can be one of the following: -tag -width truncate truncate -tag…'
complete -c iprop-log -s c -d 'configuration file'
complete -c iprop-log -s r -d 'realm El Pp Truncates the log'
complete -c iprop-log -l start-version -d 'start replay with this version Xo end-version= Ns Ar version-number Xc end re…'

