# iprop
# Autogenerated from man page /usr/share/man/man8/iprop.8.gz
complete -c iprop -s c
complete -c iprop -s r
complete -c iprop -s k -d 'keytab to get authentication from'
complete -c iprop -s d -d 'Database (default per KDC)'
complete -c iprop -l slave-stats-file -d 'file for slave status information'
complete -c iprop -l time-missing -d 'time before slave is polled for presence (default 2 min)'
complete -c iprop -l time-gone -d 'time of inactivity after which a slave is considered gone (default 5 min)'
complete -c iprop -l detach -d 'detach from console'
complete -c iprop -l version
complete -c iprop -l help -d 'El Pp Supported options for iprop ipropd-slave : -tag -width Ds'
complete -c iprop -l time-lost -d 'time before server is considered lost (default 5 min)'

