# iscsid
# Autogenerated from man page /usr/share/man/man8/iscsid.8.gz
complete -c iscsid -s P -d 'Specify alternative location of a file where main process PID will be stored'
complete -c iscsid -s d -d 'Debug mode'
complete -c iscsid -s l -d 'Specifies debug level.  The default is 0'
complete -c iscsid -s m -d 'Specifies limit for concurrently running child processes handling connections'
complete -c iscsid -s t -d 'Specifies timeout for login session, after which the connection will be forci…'

