# jexec
# Autogenerated from man page /usr/share/man/man8/jexec.8.gz
complete -c jexec -s l -d 'Execute in a clean environment'
complete -c jexec -s u -d 'The user name from host environment as whom the command should run'
complete -c jexec -s U -d 'The user name from jailed environment as whom the command should run'

