# jls
# Autogenerated from man page /usr/share/man/man8/jls.8.gz
complete -c jls -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c jls -s d -d 'List dying as well as active jails'
complete -c jls -s h -d 'Print a header line containing the parameters listed'
complete -c jls -s N -d 'In the standard display mode, print each jail\'s name instead of its numeric ID'
complete -c jls -s n -d 'Print parameters in name=value format, where each parameter is preceded by it…'
complete -c jls -s q -d 'Put quotes around parameters if they contain spaces or quotes, or are the emp…'
complete -c jls -s s -d 'Print parameters suitable for passing to jail 8, skipping read-only and unuse…'
complete -c jls -s v -d 'Extend the standard display with a multiple-line summary per jail, containing…'
complete -c jls -s j -d 'The jid or name of the jail to list'

