# join
# Autogenerated from man page /usr/share/man/man1/join.1.gz
complete -c join -s a -d 'In addition to the default output, produce a line for each unpairable line in…'
complete -c join -s e -d 'Replace empty output fields with string'
complete -c join -s o -d 'The o option specifies the fields that will be output from each file for each…'
complete -c join -s t -d 'Use character char as a field delimiter for both input and output'
complete -c join -s v -d 'Do not display the default output, but display a line for each unpairable lin…'
complete -c join -s 1 -d 'Join on the field Ns \'th field of file1'
complete -c join -s 2 -d 'Join on the field Ns \'th field of file2'
complete -c join -o j1 -d 'Join on the field Ns \'th field of file1'
complete -c join -o j2 -d 'Join on the field Ns \'th field of file2'
complete -c join -s j -d 'Join on the field Ns \'th field of both file1 and file2'

