# jot
# Autogenerated from man page /usr/share/man/man1/jot.1.gz
complete -c jot -s r -d 'Generate random data instead of the default sequential data'
complete -c jot -s b -d 'Just print word repetitively'
complete -c jot -s w -d 'Print word with the generated data appended to it'
complete -c jot -s c -d 'This is an abbreviation for w Ar %c'
complete -c jot -s s -d 'Print data separated by string.  Normally, newlines separate data'
complete -c jot -s n -d 'Do not print the final newline normally appended to the output'
complete -c jot -s p -d 'Print only as many digits or characters of the data as indicated by the integ…'

