# kadmin
# Autogenerated from man page /usr/share/man/man8/kadmin.8.gz
complete -c kadmin -s p -d 'principal to authenticate as'
complete -c kadmin -s K -d 'keytab for authentication principal'
complete -c kadmin -s c -d 'location of config file'
complete -c kadmin -s k -d 'location of master key file'
complete -c kadmin -s r -d 'realm to use'
complete -c kadmin -s a -d 'server to contact'
complete -c kadmin -s s -d 'port to use'
complete -c kadmin -s l -d 'local admin mode El Pp If no command is given on the command line, kadmin wil…'

