# kadmind
# Autogenerated from man page /usr/share/man/man8/kadmind.8.gz
complete -c kadmind -s c -d 'location of config file'
complete -c kadmind -s k -d 'location of master key file'
complete -c kadmind -l keytab -d 'what keytab to use'
complete -c kadmind -s r -d 'realm to use'
complete -c kadmind -s d -d 'enable debugging'
complete -c kadmind -s p -d 'ports to listen to'

