# kbdcontrol
# Autogenerated from man page /usr/share/man/man1/kbdcontrol.1.gz
complete -c kbdcontrol -s A -d 'Detach the keyboard, specified by the keyboard device name, from the keyboard…'
complete -c kbdcontrol -s a -d 'Attach the keyboard, specified by the keyboard device name, to the keyboard m…'
complete -c kbdcontrol -s b -d 'duration '
complete -c kbdcontrol -s r -d 'delay '
complete -c kbdcontrol -s l -d 'Install keyboard map file from keymap_file'
complete -c kbdcontrol -s d -d 'Dump the current keyboard map onto stdout'
complete -c kbdcontrol -s f -d 'Set function key number # to send string'
complete -c kbdcontrol -s F -d 'Set function keys back to the standard definitions'
complete -c kbdcontrol -s x -d 'Use hexadecimal numbers in keyboard map dump'
complete -c kbdcontrol -s i -d 'Print brief information about the keyboard'
complete -c kbdcontrol -s K -d 'Disconnect the keyboard from the console'
complete -c kbdcontrol -s k -d 'Use the specified device as the console keyboard'
complete -c kbdcontrol -s L -d 'Load keyboard map file from keymap_file and write the "struct keymap" compile…'
complete -c kbdcontrol -s P -d 'Search for the keymap file in path'

