# kbdmap
# Autogenerated from man page /usr/share/man/man1/kbdmap.1.gz
complete -c kbdmap -s K -d 'Run as command kbdmap'
complete -c kbdmap -s V -d 'Run as command kbdmap vidfont'
complete -c kbdmap -s d -d 'Use default language.  Ignore LANG environment variable'
complete -c kbdmap -s h -d 'Print options and exit'
complete -c kbdmap -s l -d 'Use language for description and menu'
complete -c kbdmap -s p -d 'Print description of available keymaps or fonts to stdout and exit'
complete -c kbdmap -s r -d 'Load default font from /etc/rc. conf'
complete -c kbdmap -s s -d 'Show currently supported languages and exit'
complete -c kbdmap -s v -d 'More warnings'

