# kcm
# Autogenerated from man page /usr/share/man/man8/kcm.8.gz
complete -c kcm -l cache-name -d 'system cache name'
complete -c kcm -s c -d 'location of config file'
complete -c kcm -s g -d 'system cache group'
complete -c kcm -l max-request -d 'max size for a kcm-request'
complete -c kcm -l disallow-getting-krbtgt -d 'disallow extracting any krbtgt from the kcm kcm daemon'
complete -c kcm -l detach -d 'detach from console'
complete -c kcm -s h
complete -c kcm -s k -d 'system principal name'
complete -c kcm -s l -d 'lifetime of system tickets'
complete -c kcm -s m -d 'octal mode of system cache'
complete -c kcm -s n -d 'disable credentials cache name constraints'
complete -c kcm -s r -d 'renewable lifetime of system tickets'
complete -c kcm -s s -d 'path to kcm domain socket'
complete -c kcm -l door-path -d 'path to kcm door socket'
complete -c kcm -s S -d 'server to get system ticket for'
complete -c kcm -s t -d 'system keytab name'
complete -c kcm -s u -d 'system cache owner'
complete -c kcm -s v -d El

