# kdc
# Autogenerated from man page /usr/share/man/man8/kdc.8.gz
complete -c kdc -s c -d 'Specifies the location of the config file, the default is /var/heimdal/kdc'
complete -c kdc -s p -d 'Turn off the requirement for pre-autentication in the initial AS-REQ for all …'
complete -c kdc -l max-request -d 'Gives an upper limit on the size of the requests that the kdc is willing to h…'
complete -c kdc -s H -d 'Makes the kdc listen on port 80 and handle requests encapsulated in HTTP'
complete -c kdc -l no-524 -d 'don\'t respond to 524 requests'
complete -c kdc -l kerberos4 -d 'respond to Kerberos 4 requests'
complete -c kdc -l kerberos4-cross-realm -d 'respond to Kerberos 4 requests from foreign realms'
complete -c kdc -s r -d 'What realm this server should act as when dealing with version 4 requests'
complete -c kdc -s P -d 'Specifies the set of ports the KDC should listen on'
complete -c kdc -l addresses -d 'The list of addresses to listen for requests on'
complete -c kdc -l detach -d 'detach from pty and run as a daemon'
complete -c kdc -l disable-des -d 'disable add des encryption types, makes the kdc not use them'

