# kdestroy
# Autogenerated from man page /usr/share/man/man1/kdestroy.1.gz
complete -c kdestroy -o credential -d 'remove principal from the credential cache if it exists'
complete -c kdestroy -s c
complete -c kdestroy -o cache -d 'The cache file to remove'
complete -c kdestroy -s A
complete -c kdestroy -l all -d 'remove all credential caches'
complete -c kdestroy -l no-unlog -d 'Do not remove AFS tokens'
complete -c kdestroy -l no-delete-v4 -d 'Do not remove v4 tickets.  El SEE ALSO kinit 1, klist 1'

