# kdump
# Autogenerated from man page /usr/share/man/man1/kdump.1.gz
complete -c kdump -s A -d 'Display the ABI of the traced process'
complete -c kdump -s c -d 'Display the CPU number with each trace entry'
complete -c kdump -s d -d 'Display all numbers in decimal'
complete -c kdump -s E -d 'Display elapsed timestamps (time since beginning of trace)'
complete -c kdump -s f -d 'Display the specified file instead of ktrace. out'
complete -c kdump -s H -d 'List the thread ID (tid) of the thread with each trace record, if available'
complete -c kdump -s l -d 'Loop reading the trace file, once the end-of-file is reached, waiting for mor…'
complete -c kdump -s m -d 'Display at most maxdata bytes when decoding I/O'
complete -c kdump -s n -d 'Suppress ad hoc translations'
complete -c kdump -s p -d 'Display only trace events that correspond to the process or thread pid'
complete -c kdump -s R -d 'Display relative timestamps (time since previous entry)'
complete -c kdump -s r -d 'When decoding STRU records, display structure members such as UIDs, GIDs, dat…'
complete -c kdump -s S -d 'Display system call numbers'
complete -c kdump -s s -d 'Suppress display of I/O data'
complete -c kdump -s T -d 'Display absolute timestamps for each entry (seconds since epoch)'
complete -c kdump -s t -d 'See the t option of ktrace 1'

