# keyserv
# Autogenerated from man page /usr/share/man/man8/keyserv.8.gz
complete -c keyserv -s d -d 'Disable the use of default keys for nobody'
complete -c keyserv -s D -d 'Run in debugging mode and log all requests to keyserv'
complete -c keyserv -s n -d 'Root\'s secret key is not read from /etc/. rootkey'
complete -c keyserv -s p -d 'Specify where to search for libdes. so. 3.  Default is /usr/lib'
complete -c keyserv -s v -d 'Display status of DES support (enabled/disabled)'

