# kf
# Autogenerated from man page /usr/share/man/man1/kf.1.gz
complete -c kf -s F -d 'forward forwardable credentials'
complete -c kf -s G -d 'do not forward forwardable credentials'
complete -c kf -s h
complete -c kf -l version -d 'El Pp kf is useful when you do not want to enter your password on a remote ho…'

