# kgetcred
# Autogenerated from man page /usr/share/man/man1/kgetcred.1.gz
complete -c kgetcred -l canonicalize -d 'requests that the KDC canonicalize the principal'
complete -c kgetcred -s c -d 'the credential cache to use'
complete -c kgetcred -s e -d 'encryption type to use'
complete -c kgetcred -l no-transit-check -d 'requests that the KDC doesn\'t do transit checking'
complete -c kgetcred -l version
complete -c kgetcred -l help -d 'El SEE ALSO kinit 1, klist 1'

