# kill
# Autogenerated from man page /usr/share/man/man1/kill.1.gz
complete -c kill -s s -d 'A symbolic signal name specifying the signal to be sent instead of the defaul…'
complete -c kill -s l -d 'If no operand is given, list the signal names; otherwise, write the signal na…'
complete -c kill -o signal_name -d 'A symbolic signal name specifying the signal to be sent instead of the defaul…'
complete -c kill -o signal_number -d 'A non-negative decimal integer, specifying the signal to be sent instead of t…'

