# killall
# Autogenerated from man page /usr/share/man/man1/killall.1.gz
complete -c killall -s d -d 'Be more verbose about what will be done, but do not send any signal'
complete -c killall -s e -d 'Use the effective user ID instead of the (default) real user ID for matching …'
complete -c killall -o help -d 'Give a help on the command usage and exit'
complete -c killall -s I -d 'Request confirmation before attempting to signal each process'
complete -c killall -s l -d 'List the names of the available signals and exit, like in kill 1'
complete -c killall -s m -d 'Match the argument procname as a (case sensitive) regular expression against …'
complete -c killall -s v -d 'Be verbose about what will be done'
complete -c killall -s s -d 'Same as v, but do not send any signal'
complete -c killall -o SIGNAL -d 'Send a different signal instead of the default TERM'
complete -c killall -s j -d 'Kill processes in the specified jail'
complete -c killall -s u -d 'Limit potentially matching processes to those belonging to the specified user'
complete -c killall -s t -d 'Limit potentially matching processes to those running on the specified tty'
complete -c killall -s c -d 'Limit potentially matching processes to those matching the specified procname'
complete -c killall -s q -d 'Suppress error message if no processes are matched'
complete -c killall -s z -d 'Do not skip zombies'

