# kimpersonate
# Autogenerated from man page /usr/share/man/man8/kimpersonate.8.gz
complete -c kimpersonate -s s -d 'name of server principal'
complete -c kimpersonate -s c -d 'name of client principal'
complete -c kimpersonate -s k -d 'name of keytab file'
complete -c kimpersonate -s 5 -d 'create a Kerberos 5 ticket'
complete -c kimpersonate -s e -d 'lifetime of ticket in seconds'
complete -c kimpersonate -s a -d 'address of client'
complete -c kimpersonate -s t -d 'encryption type'
complete -c kimpersonate -s f -d 'ticket flags for krb5 ticket'
complete -c kimpersonate -l verbose -d 'Verbose output'
complete -c kimpersonate -l version -d 'Print version'
complete -c kimpersonate -l help -d 'El FILES Uses /etc/krb5'

