# kldconfig
# Autogenerated from man page /usr/share/man/man8/kldconfig.8.gz
complete -c kldconfig -s d -d 'Remove the specified paths from the module search path'
complete -c kldconfig -s f -d 'Do not fail if a path specified for adding is already present in the search p…'
complete -c kldconfig -s i -d 'Add the specified paths to the beginning of the search path, not to the end'
complete -c kldconfig -s m -d 'Instead of replacing the module search path with the set of paths specified, …'
complete -c kldconfig -s n -d 'Do not actually change the module search path'
complete -c kldconfig -s r -d 'Display the current search path'
complete -c kldconfig -s S -d 'Specify the sysctl name to use instead of the default kern. module_path'
complete -c kldconfig -s U -d 'Unique-ify the current search path - if any of the directories is repeated on…'
complete -c kldconfig -s v -d 'Verbose output: display the new module search path'

