# kldload
# Autogenerated from man page /usr/share/man/man8/kldload.8.gz
complete -c kldload -s n -d 'Do not try to load module if already loaded'
complete -c kldload -s v -d 'Be more verbose'
complete -c kldload -s q -d 'Silence any extraneous warnings'

