# kldstat
# Autogenerated from man page /usr/share/man/man8/kldstat.8.gz
complete -c kldstat -s h -d 'Display the size field in a human-readable form, using unit suffixes instead …'
complete -c kldstat -s v -d 'Be more verbose'
complete -c kldstat -s d -d 'Show the module specific data (as int, unsigned int and unsigned long)'
complete -c kldstat -s i -d 'Display the status of only the file with this ID'
complete -c kldstat -s n -d 'Display the status of only the file with this filename'
complete -c kldstat -s q -d 'Only check if file is loaded or compiled into the kernel'
complete -c kldstat -s m -d 'Display the status of only the module with this modname'

