# kldunload
# Autogenerated from man page /usr/share/man/man8/kldunload.8.gz
complete -c kldunload -s f -d 'Force the unload'
complete -c kldunload -s v -d 'Be more verbose'
complete -c kldunload -s i -d 'Unload the file with this ID'
complete -c kldunload -s n -d 'Unload the file with this name.  name Unload the file with this name'

