# kldxref
# Autogenerated from man page /usr/share/man/man8/kldxref.8.gz
complete -c kldxref -s R -d 'Recurse into subdirectories'
complete -c kldxref -s d -d 'Do not generate a hint file, but print module metadata on standard output'
complete -c kldxref -s f -d 'Specify a different name for the hints files than linker. hints'
complete -c kldxref -s v -d 'Operate in verbose mode'

