# klist
# Autogenerated from man page /usr/share/man/man1/klist.1.gz
complete -c klist -s c -d 'credential cache to list'
complete -c klist -s s -d 'Test for there being an active and valid TGT for the local realm of the user …'
complete -c klist -s T -d 'display AFS tokens'
complete -c klist -s 5 -d 'display v5 cred cache (this is the default)'
complete -c klist -s f -d 'Include ticket flags in short form, each character stands for a specific flag…'
complete -c klist -s v -d 'Verbose output'
complete -c klist -s l -d 'List the credential caches for the current users, not all cache types support…'

