# kpasswdd
# Autogenerated from man page /usr/share/man/man8/kpasswdd.8.gz
complete -c kpasswdd -l addresses -d 'For each till the argument is given, add the address to what kpasswdd should …'
complete -c kpasswdd -l check-library -d 'If your system has support for dynamic loading of shared libraries, you can u…'
complete -c kpasswdd -l check-function -d 'This is the function to call in the loaded library'
complete -c kpasswdd -s k -d 'Keytab to get authentication key from'
complete -c kpasswdd -s r -d 'Default realm'
complete -c kpasswdd -s p -d 'Port to listen on (default service kpasswd - 464)'

