# kstash
# Autogenerated from man page /usr/share/man/man8/kstash.8.gz
complete -c kstash -s e -d 'the encryption type to use, defaults to DES3-CBC-SHA1'
complete -c kstash -s k -d 'the name of the master key file'
complete -c kstash -l convert-file -d 'don\'t ask for a new master key, just read an old master key file, and write i…'
complete -c kstash -l random-key -d 'generate a random master key'
complete -c kstash -l master-key-fd -d 'filedescriptor to read passphrase from, if not specified the passphrase will …'

