# ktrace
# Autogenerated from man page /usr/share/man/man1/ktrace.1.gz
complete -c ktrace -s a -d 'Append to the trace file instead of recreating it'
complete -c ktrace -s C -d 'Disable tracing on all user-owned processes, and, if executed by root, all pr…'
complete -c ktrace -s c -d 'Clear the specified trace points associated with the given file or processes'
complete -c ktrace -s d -d 'Descendants; perform the operation for all current children of the designated…'
complete -c ktrace -s f -d 'Log trace records to trfile instead of ktrace. out'
complete -c ktrace -s g -d 'Enable (disable) tracing on all processes in the process group (only one g fl…'
complete -c ktrace -s i -d 'Inherit; pass the trace flags to all future children of the designated proces…'
complete -c ktrace -s p -d 'Enable (disable) tracing on the indicated process id (only one p flag is perm…'
complete -c ktrace -s t -d 'Specify the list of trace points to enable or disable, one per letter'

