# ktrdump
# Autogenerated from man page /usr/share/man/man8/ktrdump.8.gz
complete -c ktrdump -s c -d 'Print the CPU number that each entry was logged from'
complete -c ktrdump -s l -d 'Poll the kernel ktr trace buffer periodically dumping any new events after ea…'
complete -c ktrdump -s f -d 'Print the file and line number that each entry was logged from'
complete -c ktrdump -s q -d 'Quiet mode; do not print the column header'
complete -c ktrdump -s r -d 'Print relative timestamps rather than absolute timestamps'
complete -c ktrdump -s t -d 'Print the timestamp for each entry'
complete -c ktrdump -s H -d 'Print the thread ID for each entry'
complete -c ktrdump -s i -d 'File containing saved ktr trace events; for more information see the ktr 4 ma…'
complete -c ktrdump -s N -d 'The kernel image to resolve symbols from'
complete -c ktrdump -s M -d 'The core file or memory image to read from.  The default is /dev/mem'
complete -c ktrdump -s o -d 'The file to write the output to.  The default is standard output'

