# kyua-test
# Autogenerated from man page /usr/share/man/man1/kyua-test.1.gz
complete -c kyua-test -l build-root -d 'Specifies the build root in which to find the test programs referenced by the…'
complete -c kyua-test -l kyuafile -d 'Specifies the Kyuafile to process'
complete -c kyua-test -l results-file -d 'Specifies the results file to create'

