# kyua-debug
# Autogenerated from man page /usr/share/man/man1/kyua-debug.1.gz
complete -c kyua-debug -l build-root -d 'Specifies the build root in which to find the test programs referenced by the…'
complete -c kyua-debug -l kyuafile -d 'Specifies the Kyuafile to process'
complete -c kyua-debug -l stderr -d 'Specifies the file to which to send the standard error of the test program\'s …'
complete -c kyua-debug -l stdout -d 'Specifies the file to which to send the standard output of the test program\'s…'

