# kyua-report-junit
# Autogenerated from man page /usr/share/man/man1/kyua-report-junit.1.gz
complete -c kyua-report-junit -l output -d 'Specifies the file into which to store the JUnit report'
complete -c kyua-report-junit -l results-file -d 'Specifies the results file to operate on'

