# kyua-db-exec
# Autogenerated from man page /usr/share/man/man1/kyua-db-exec.1.gz
complete -c kyua-db-exec -l no-headers -d 'Avoids printing the headers of the table in the output of the command'
complete -c kyua-db-exec -l results-file -d 'Specifies the results file to operate on'

