# kyua
# Autogenerated from man page /usr/share/man/man1/kyua.1.gz
complete -c kyua -l config -d 'Specifies the configuration file to process, which must be in the format desc…'
complete -c kyua -l logfile -d 'Specifies the location of the file to which kyua will log run time events use…'
complete -c kyua -l loglevel -d 'Specifies the maximum logging level to record in the log file'
complete -c kyua -l variable -d 'Sets the name configuration variable to value'

