# kyua-report-html
# Autogenerated from man page /usr/share/man/man1/kyua-report-html.1.gz
complete -c kyua-report-html -l force -d 'Forces the deletion of the output directory if it exists'
complete -c kyua-report-html -l output -d 'Specifies the target directory into which to generate the HTML files'
complete -c kyua-report-html -l results-file -d 'Specifies the results file to operate on'
complete -c kyua-report-html -l results-filter -d 'Comma-separated list of the test result types to include in the report'

