# kyua-list
# Autogenerated from man page /usr/share/man/man1/kyua-list.1.gz
complete -c kyua-list -l build-root -d 'Specifies the build root in which to find the test programs referenced by the…'
complete -c kyua-list -l kyuafile -d 'Specifies the Kyuafile to process'
complete -c kyua-list -l verbose -d 'Prints metadata properties for every test case'

