# kyua-report
# Autogenerated from man page /usr/share/man/man1/kyua-report.1.gz
complete -c kyua-report -l output -d 'Specifies the path to which the report should be written to'
complete -c kyua-report -l results-file -d 'Specifies the results file to operate on'
complete -c kyua-report -l results-filter -d 'Comma-separated list of the test result types to include in the report'
complete -c kyua-report -l verbose -d 'Prints a detailed report of the execution'

