# l2control
# Autogenerated from man page /usr/share/man/man8/l2control.8.gz
complete -c l2control -s a -d 'Connect to the local device with the specified BD_ADDR or name'
complete -c l2control -s h -d 'Display usage message and exit'
complete -c l2control -s n -d 'Show Bluetooth addresses as numbers'

