# l2ping
# Autogenerated from man page /usr/share/man/man8/l2ping.8.gz
complete -c l2ping -s a -d 'Specify the remote device to ping'
complete -c l2ping -s c -d 'Number of packets to send'
complete -c l2ping -s f -d 'Do not wait between sending each packet'
complete -c l2ping -s h -d 'Display usage message and exit'
complete -c l2ping -s i -d 'Wait wait seconds between sending each packet'
complete -c l2ping -s n -d 'Numeric output only'
complete -c l2ping -s S -d 'Specify the local device which should be used to send L2CAP ECHO_REQUEST data…'
complete -c l2ping -s s -d 'Specify the number of payload bytes to be sent.  The default size is 44 bytes'

