# lam
# Autogenerated from man page /usr/share/man/man1/lam.1.gz
complete -c lam -s f -d 'Print line fragments according to the format string min '
complete -c lam -s p -d 'Like f, but pad this file\'s field when end-of-file is reached and other files…'
complete -c lam -s s -d 'Print sepstring before printing line fragments from the next file'
complete -c lam -s t -d 'The input line terminator is c instead of a newline'

