# lastlogin
# Autogenerated from man page /usr/share/man/man8/lastlogin.8.gz
complete -c lastlogin -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c lastlogin -s f -d 'Open last login database file instead of the system-wide database'
complete -c lastlogin -s r -d 'Print the entries in reverse sorted order'
complete -c lastlogin -s t -d 'Sort the elements by last login time, instead of user name'

