# last
# Autogenerated from man page /usr/share/man/man1/last.1.gz
complete -c last -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c last -s d -d 'Specify the snapshot date and time'
complete -c last -s f -d 'Read the file file instead of the default, /var/log/utx. log'
complete -c last -s h -d 'Host names may be names or internet numbers'
complete -c last -s n -d 'Limit the report to maxrec lines'
complete -c last -s s -d 'Report the duration of the login session in seconds, instead of the default d…'
complete -c last -s t -d 'Specify the tty'
complete -c last -s w -d 'Widen the duration field to show seconds, as well as the default days, hours …'
complete -c last -s y -d 'Report the year in the session start time'

