# lastcomm
# Autogenerated from man page /usr/share/man/man1/lastcomm.1.gz
complete -c lastcomm -s E -d 'Print the time the process exited'
complete -c lastcomm -s S -d 'Print the time the process started'
complete -c lastcomm -s c -d 'Print the amount of cpu time used by the process'
complete -c lastcomm -s e -d 'Print the amount of elapsed time used by the process'
complete -c lastcomm -s s -d 'Print the amount of system time used by the process'
complete -c lastcomm -s u -d 'Print the amount of user time used by the process'
complete -c lastcomm -s f -d 'Read from file rather than the default /var/account/acct'

