# ld-elf.so.1
# Autogenerated from man page /usr/share/man/man1/ld-elf.so.1.1.gz
complete -c 'ld-elf.so.1' -s b -d 'Use the executable exe instead of image_path for activation'
complete -c 'ld-elf.so.1' -s d -d 'Turn off the emulation of the binary execute permission'
complete -c 'ld-elf.so.1' -s f -d 'File descriptor fd references the binary to be activated by ld-elf. so. 1'
complete -c 'ld-elf.so.1' -s p -d 'If the image_path argument specifies a name which does not contain a slash / …'
complete -c 'ld-elf.so.1' -s u -d 'Ignore all LD_ environment variables that otherwise affect the dynamic linker…'
complete -c 'ld-elf.so.1' -s v -d 'Display information about this run-time linker binary, then exit'

