# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
complete -c ldconfig -o 32 -d 'Generate the hints for 32-bit ABI shared libraries on 64-bit systems that sup…'
complete -c ldconfig -o elf -d 'Ignored for backwards compatibility'
complete -c ldconfig -s R -d 'Appends pathnames on the command line to the directory list from the hints fi…'
complete -c ldconfig -s f -d 'Read and/or update the specified hints file, instead of the standard file'
complete -c ldconfig -s i -d 'Run in insecure mode.  The security checks will not be performed'
complete -c ldconfig -s m -d 'Instead of replacing the list of the directories to search with the directori…'
complete -c ldconfig -s r -d 'List the current list of the directories from the hints file on the standard …'
complete -c ldconfig -s v -d 'Switch on verbose mode'

