# libinput-list-kernel-devices
# Autogenerated from man page /usr/local/man/man1/libinput-list-kernel-devices.1.gz
complete -c libinput-list-kernel-devices -l help -d 'Print help'
complete -c libinput-list-kernel-devices -l hid -d 'List HID devices instead of evdev device nodes NOTES'

