# libinput-measure-touchpad-size
# Autogenerated from man page /usr/local/man/man1/libinput-measure-touchpad-size.1.gz
complete -c libinput-measure-touchpad-size -l help -d 'Print help LIBINPUT Part of the libinput(1) suite'

