# libwacom-list-local-devices
# Autogenerated from man page /usr/local/man/man1/libwacom-list-local-devices.1.gz
complete -c libwacom-list-local-devices -l database -d 'Sets the data directory path to be used'

