# link
# Autogenerated from man page /usr/share/man/man1/link.1.gz
complete -c link -s F -d 'If the target file already exists and is a directory, then remove it so that …'
complete -c link -s L -d 'When creating a hard link to a symbolic link, create a hard link to the targe…'
complete -c link -s P -d 'When creating a hard link to a symbolic link, create a hard link to the symbo…'
complete -c link -s f -d 'If the target file already exists, then unlink it so that the link may occur'
complete -c link -s h -d 'If the target_file or target_dir is a symbolic link, do not follow it'
complete -c link -s i -d 'Cause link to write a prompt to standard error if the target file exists'
complete -c link -s n -d 'Same as h, for compatibility with other link implementations'
complete -c link -s s -d 'Create a symbolic link'
complete -c link -s v -d 'Cause link to be verbose, showing files as they are processed'
complete -c link -s w -d 'Warn if the source of a symbolic link does not currently exist'

