# lldb-server
# Autogenerated from man page /usr/share/man/man1/lldb-server.1.gz
complete -c lldb-server -l fd -d 'Communicate over the given file descriptor instead of sockets'
complete -c lldb-server -l named-pipe -d 'Write the listening port number to the specified named pipe'
complete -c lldb-server -l pipe -d 'Write the listening port number to the specified pipe (fd)'
complete -c lldb-server -l reverse-connect -d 'Connect to the client instead of passively waiting for a connection'
complete -c lldb-server -l help -d 'Prints out the usage information and exits'
complete -c lldb-server -l log-channels -d 'Channels to log.  A colon-separated list of entries'
complete -c lldb-server -l log-file -d 'Destination file to log to.  If empty, log to stderr'
complete -c lldb-server -l setsid -d 'Run lldb-server in a new session'
complete -c lldb-server -l attach -d 'Attach to the process given by a (numeric) process id or a name'
complete -c lldb-server -l server -d 'Run in server mode, handling multiple connections'
complete -c lldb-server -l listen -d 'Hostname and port to listen on.  Obligatory'
complete -c lldb-server -l socket-file -d 'Write the listening socket port number to the specified file'
complete -c lldb-server -l gdbserver-port -d 'Define a port to be used for gdb-server connections'
complete -c lldb-server -l min-gdbserver-port
complete -c lldb-server -l max-gdbserver-port -d 'Specify the range of ports that can be used for gdb-server connections'
complete -c lldb-server -l port-offset -d 'Add the specified offset to port numbers returned by server'

