# llvm-bcanalyzer15
# Autogenerated from man page /usr/local/man/man1/llvm-bcanalyzer15.1.gz
complete -c llvm-bcanalyzer15 -l dump -d 'Causes llvm-bcanalyzer to dump the bitcode in a human readable format'
complete -c llvm-bcanalyzer15 -l help -d 'Print a summary of command line options'

