# llvm-dwarfutil15
# Autogenerated from man page /usr/local/man/man1/llvm-dwarfutil15.1.gz
complete -c llvm-dwarfutil15 -l garbage-collection -d 'Removes pieces of debug information related to discarded sections'
complete -c llvm-dwarfutil15 -l odr-deduplication -d 'Remove duplicated types (if "One Definition Rule" is supported by source lang…'
complete -c llvm-dwarfutil15 -l help -s h -d 'Print a summary of command line options'
complete -c llvm-dwarfutil15 -l no-garbage-collection -d 'Disable %--garbage-collection'
complete -c llvm-dwarfutil15 -l no-odr-deduplication -d 'Disable %--odr-deduplication'
complete -c llvm-dwarfutil15 -l no-separate-debug-file -d 'Disable %--separate-debug-file'
complete -c llvm-dwarfutil15 -l num-threads -s j -d 'Specifies the maximum number (n) of simultaneous threads to use for processing'
complete -c llvm-dwarfutil15 -l separate-debug-file -d 'Generate separate file containing output debug info'
complete -c llvm-dwarfutil15 -l tombstone -d '<value> can be one of the following values: o 2 bfd: zero for all addresses a…'
complete -c llvm-dwarfutil15 -l verbose -d 'Enable verbose logging.  This option disables multi-thread mode'
complete -c llvm-dwarfutil15 -l verify -d 'Run the DWARF verifier on the output DWARF debug info'
complete -c llvm-dwarfutil15 -l version -d 'Print the version of this program'

