# llvm-libtool-darwin15
# Autogenerated from man page /usr/local/man/man1/llvm-libtool-darwin15.1.gz
complete -c llvm-libtool-darwin15 -o arch_only -d 'Build a static library only for the specified <architecture> and ignore all o…'
complete -c llvm-libtool-darwin15 -o color -d 'Use colors in output'
complete -c llvm-libtool-darwin15 -s D -d 'Use zero for timestamps and UIDs/GIDs.  This is set by default'
complete -c llvm-libtool-darwin15 -o filelist -d 'Read input file names from <listfile>'
complete -c llvm-libtool-darwin15 -s h -o help -d 'Show help and usage for this command'
complete -c llvm-libtool-darwin15 -o help-list -d 'Show help and usage for this command without grouping the options into catego…'
complete -c llvm-libtool-darwin15 -s l -d 'Searches for the library libx. a in the library search path'
complete -c llvm-libtool-darwin15 -s L -d 'Adds <dir> to the list of directories in which to search for libraries'
complete -c llvm-libtool-darwin15 -o no_warning_for_no_symbols -d 'Do not warn about files that have no symbols'
complete -c llvm-libtool-darwin15 -o warnings_as_errors -d 'Produce a non-zero exit status if any warnings are emitted'
complete -c llvm-libtool-darwin15 -s o -d 'Specify the output file name.  Must be specified exactly once'
complete -c llvm-libtool-darwin15 -o static -d 'Produces a static library from the input files'
complete -c llvm-libtool-darwin15 -s U -d 'Use actual timestamps and UIDs/GIDs'
complete -c llvm-libtool-darwin15 -s V -d 'Display the version of this program and perform any operation specified'
complete -c llvm-libtool-darwin15 -o version -d 'Display the version of this program and exit immediately'

