# llvm-remark-size-diff15
# Autogenerated from man page /usr/local/man/man1/llvm-remark-size-diff15.1.gz
complete -c llvm-remark-size-diff15 -l parser -d 'Select the type of input remark parser.  Required'
complete -c llvm-remark-size-diff15 -l report-style -d 'Output style.  * human: Human-readable textual report.  Default option'
complete -c llvm-remark-size-diff15 -l pretty -d 'Pretty-print JSON output.  Optional'
complete -c llvm-remark-size-diff15 -s o -d 'Output file for the report.  Outputs to stdout by default'

