# llvm-tli-checker15
# Autogenerated from man page /usr/local/man/man1/llvm-tli-checker15.1.gz
complete -c llvm-tli-checker15 -l dump-tli -d 'Print \\(dqavailable\\(dq/\\(dqnot available\\(dq for each library function, acco…'
complete -c llvm-tli-checker15 -l help -s h -d 'Print a summary of command line options and exit'
complete -c llvm-tli-checker15 -l libdir -d 'A base directory to prepend to each library file path'
complete -c llvm-tli-checker15 -l report -d 'The amount of information to report'
complete -c llvm-tli-checker15 -l separate -d 'Read and report a summary for each library file separately'
complete -c llvm-tli-checker15 -l triple -d 'The triple to use for initializing TargetLibraryInfo'

