# llvm-cxxfilt
# Autogenerated from man page /usr/share/man/man1/llvm-cxxfilt.1.gz
complete -c llvm-cxxfilt -l format -s s -d 'Mangling scheme to assume'
complete -c llvm-cxxfilt -l help -s h -d 'Print a summary of command line options'
complete -c llvm-cxxfilt -l no-strip-underscore -s n -d 'Do not strip a leading underscore'
complete -c llvm-cxxfilt -l strip-underscore -s _ -d 'Strip a single leading underscore, if present, from each input name before de…'
complete -c llvm-cxxfilt -l types -s t -d 'Attempt to demangle names as type names as well as function names'
complete -c llvm-cxxfilt -l version -d 'Display the version of the llvm-cxxfilt executable'

