# llvm-stress15
# Autogenerated from man page /usr/local/man/man1/llvm-stress15.1.gz
complete -c llvm-stress15 -s o -d 'Specify the output filename'
complete -c llvm-stress15 -o size -d 'Specify the size of the generated . ll file'
complete -c llvm-stress15 -o seed -d 'Specify the seed to be used for the randomly generated instructions'

