# llvm-ar15
# Autogenerated from man page /usr/local/man/man1/llvm-ar15.1.gz
complete -c llvm-ar15 -l format -d 'This option allows for default, gnu, darwin or bsd <type> to be selected'
complete -c llvm-ar15 -s h -l help -d 'Print a summary of command-line options and their meanings'
complete -c llvm-ar15 -s M -d 'This option allows for MRI scripts to be read through the standard input stre…'
complete -c llvm-ar15 -l output -d 'Specify a directory where archive members should be extracted to'
complete -c llvm-ar15 -l thin -d 'When creating or modifying an archive, this option specifies that the archive…'
complete -c llvm-ar15 -l version -d 'Display the version of the llvm-ar executable'
complete -c llvm-ar15 -s X -d 'Specifies the type of object file llvm-ar will recognise'
complete -c llvm-ar15 -l plugin
complete -c llvm-ar15 -l rsp-quoting

