# llvm-as15
# Autogenerated from man page /usr/local/man/man1/llvm-as15.1.gz
complete -c llvm-as15 -s f -d 'Enable binary output on terminals'
complete -c llvm-as15 -o help -d 'Print a summary of command line options'
complete -c llvm-as15 -s o -d 'Specify the output file name'

