# llvm-locstats15
# Autogenerated from man page /usr/local/man/man1/llvm-locstats15.1.gz
complete -c llvm-locstats15 -l only-variables -d 'calculate the location statistics only for local variables'
complete -c llvm-locstats15 -l only-formal-parameters -d 'calculate the location statistics only for formal parameters'
complete -c llvm-locstats15 -l ignore-debug-entry-values -d 'ignore the location statistics on locations containing the debug entry values…'
complete -c llvm-locstats15 -l draw-plot -d 'make histogram of location buckets generated (requires matplotlib)'
complete -c llvm-locstats15 -l compare -d 'compare the debug location coverage on two files provided, and draw a plot sh…'

