# llvm-link15
# Autogenerated from man page /usr/local/man/man1/llvm-link15.1.gz
complete -c llvm-link15 -s f -d 'Enable binary output on terminals'
complete -c llvm-link15 -s o -d 'Specify the output file name'
complete -c llvm-link15 -s S -d 'Write output in LLVM intermediate language (instead of bitcode)'
complete -c llvm-link15 -s d -d 'If specified, llvm-link prints a human-readable version of the output bitcode…'
complete -c llvm-link15 -o help -d 'Print a summary of command line options'
complete -c llvm-link15 -s v -d 'Verbose mode.   Print information about what llvm-link is doing'

