# llvm-dis15
# Autogenerated from man page /usr/local/man/man1/llvm-dis15.1.gz
complete -c llvm-dis15 -s o -d OPTIONS
complete -c llvm-dis15 -s f -d 'Enable binary output on terminals'
complete -c llvm-dis15 -o help -d 'Print a summary of command line options'

