# llvm-ifs15
# Autogenerated from man page /usr/local/man/man1/llvm-ifs15.1.gz
complete -c llvm-ifs15 -l input-format -d 'Specify input file format'
complete -c llvm-ifs15 -l output-elf -d 'Specify the output file for ELF shared object stub'
complete -c llvm-ifs15 -l output-ifs -d 'Specify the output file for text IFS'
complete -c llvm-ifs15 -l output-tbd -d 'Specify the output file for Apple TAPI tbd'
complete -c llvm-ifs15 -l arch -d 'This flag is optional and it should only be used when reading an IFS file whi…'
complete -c llvm-ifs15 -l endianness -d 'This flag is optional and it should only be used when reading an IFS file whi…'
complete -c llvm-ifs15 -l bitwidth -d 'This flag is optional and it should only be used when reading an IFS file whi…'
complete -c llvm-ifs15 -l target -d 'This flag is optional and should only be used when reading an IFS file which …'
complete -c llvm-ifs15 -l hint-ifs-target -d 'This flag is optional and should only be used when reading an ELF shared obje…'
complete -c llvm-ifs15 -l strip-ifs-endianness -d 'This flag is optional and should only be used when outputting an IFS file'
complete -c llvm-ifs15 -l strip-ifs-bitwidth -d 'This flag is optional and should only be used when outputting an IFS file'
complete -c llvm-ifs15 -l strip-ifs-target -d 'This flag is optional and should only be used when outputting an IFS file'
complete -c llvm-ifs15 -l write-if-changed -d 'When this flag is set, llvm-ifs will only write the output file if it does no…'
complete -c llvm-ifs15 -l strip-size -d 'When this flag is set, llvm-ifs will remove the size field from the output if…'
complete -c llvm-ifs15 -l - -d 'IFSVersion: 3. 0 SoName: libtest'

