# llvm-install-name-tool15
# Autogenerated from man page /usr/local/man/man1/llvm-install-name-tool15.1.gz
complete -c llvm-install-name-tool15 -o add_rpath -d 'Add an rpath named <rpath> to the specified binary'
complete -c llvm-install-name-tool15 -o change -d 'Change an install name <old_install_name> to <new_install_name> in the specif…'
complete -c llvm-install-name-tool15 -o delete_rpath -d 'Delete an rpath named <rpath> from the specified binary'
complete -c llvm-install-name-tool15 -o delete_all_rpaths -d 'Deletes all rpaths from the binary'
complete -c llvm-install-name-tool15 -l help -s h -d 'Print a summary of command line options'
complete -c llvm-install-name-tool15 -o id -d 'Change shared library\\(aqs identification name under LC_ID_DYLIB to <name> in…'
complete -c llvm-install-name-tool15 -o rpath -d 'Change an rpath named <old_rpath> to <new_rpath> in the specified binary'
complete -c llvm-install-name-tool15 -l version -s V -d 'Display the version of the llvm-install-name-tool executable'

