# llvm-extract15
# Autogenerated from man page /usr/local/man/man1/llvm-extract15.1.gz
complete -c llvm-extract15 -l alias -d 'Extract the alias named function-name from the LLVM bitcode'
complete -c llvm-extract15 -l ralias -d 'Extract the alias matching alias-regular-expr from the LLVM bitcode'
complete -c llvm-extract15 -l bb -d 'Extract basic blocks(s) specified in basic-block-specifier'
complete -c llvm-extract15 -l delete -d 'Delete specified Globals from Module'
complete -c llvm-extract15 -s f -d 'Enable binary output on terminals'
complete -c llvm-extract15 -l func -d 'Extract the function named function-name from the LLVM bitcode'
complete -c llvm-extract15 -l rfunc -d 'Extract the function(s) matching function-regular-expr from the LLVM bitcode'
complete -c llvm-extract15 -l glob -d 'Extract the global variable named global-name from the LLVM bitcode'
complete -c llvm-extract15 -l rglob -d 'Extract the global variable(s) matching global-regular-expr from the LLVM bit…'
complete -c llvm-extract15 -l keep-const-init -d 'Preserve the values of constant globals'
complete -c llvm-extract15 -l recursive -d 'Recursively extract all called functions'
complete -c llvm-extract15 -o help -d 'Print a summary of command line options'
complete -c llvm-extract15 -s o -d 'Specify the output filename'
complete -c llvm-extract15 -s S -d 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS'

