# ln
# Autogenerated from man page /usr/share/man/man1/ln.1.gz
complete -c ln -s F -d 'If the target file already exists and is a directory, then remove it so that …'
complete -c ln -s L -d 'When creating a hard link to a symbolic link, create a hard link to the targe…'
complete -c ln -s P -d 'When creating a hard link to a symbolic link, create a hard link to the symbo…'
complete -c ln -s f -d 'If the target file already exists, then unlink it so that the link may occur'
complete -c ln -s h -d 'If the target_file or target_dir is a symbolic link, do not follow it'
complete -c ln -s i -d 'Cause ln to write a prompt to standard error if the target file exists'
complete -c ln -s n -d 'Same as h, for compatibility with other ln implementations'
complete -c ln -s s -d 'Create a symbolic link'
complete -c ln -s v -d 'Cause ln to be verbose, showing files as they are processed'
complete -c ln -s w -d 'Warn if the source of a symbolic link does not currently exist'

