# loader.efi
# Autogenerated from man page /usr/share/man/man8/loader.efi.8.gz
complete -c 'loader.efi' -s a
complete -c 'loader.efi' -s c
complete -c 'loader.efi' -s d
complete -c 'loader.efi' -s r
complete -c 'loader.efi' -s D
complete -c 'loader.efi' -s m
complete -c 'loader.efi' -s g
complete -c 'loader.efi' -s h
complete -c 'loader.efi' -s p
complete -c 'loader.efi' -s P
complete -c 'loader.efi' -s s
complete -c 'loader.efi' -s v -d 'El And the following flags determine the primary console: -column -offset ind…'
complete -c 'loader.efi' -o RB_SERIAL -d 'El Pp loader'

