# local-unbound
# Autogenerated from man page /usr/share/man/man8/local-unbound.8.gz
complete -c local-unbound -s h -d 'Show the version number and commandline option help, and exit'
complete -c local-unbound -s c -d 'Set the config file with settings for Local-unbound to read instead of readin…'
complete -c local-unbound -s d -d 'Debug flag: do not fork into the background, but stay attached to the console'
complete -c local-unbound -s p -d 'Don\'t use a pidfile'
complete -c local-unbound -s v -d 'Increase verbosity.  If given multiple times, more information is logged'
complete -c local-unbound -s V -d 'Show the version number and build options, and exit.  SEE ALSO unbound'

