# local-unbound-checkconf
# Autogenerated from man page /usr/share/man/man8/local-unbound-checkconf.8.gz
complete -c local-unbound-checkconf -s h -d 'Show the version and commandline option help'
complete -c local-unbound-checkconf -s f -d 'Print full pathname, with chroot applied to it.   Use with the -o option'
complete -c local-unbound-checkconf -s o -d 'If given, after checking the config file the value of this option is printed …'

