# localedef
# Autogenerated from man page /usr/share/man/man1/localedef.1.gz
complete -c localedef -s b -d 'Use big-endian byte order for output'
complete -c localedef -s c -d 'Creates permanent output even if warning messages have been issued'
complete -c localedef -s D -d 'BSD-style output'
complete -c localedef -s f -d 'Specifies the pathname of a file containing a mapping of character symbols an…'
complete -c localedef -s i -d 'The path name of a file containing the source definitions'
complete -c localedef -s l -d 'Use little-endian byte order for output'
complete -c localedef -s u -d 'Specifies the name of a codeset used as the target mapping of character symbo…'
complete -c localedef -s U -d 'Ignore the presence of character symbols that have no matching character defi…'
complete -c localedef -s v -d 'Emit verbose debugging output on standard output'
complete -c localedef -s w -d 'The path name of the file containing character screen width definitions'
complete -c localedef -s V -d 'Specifies a version string describing the version of the locale definition'

