# locale
# Autogenerated from man page /usr/share/man/man1/locale.1.gz
complete -c locale -s a -d 'Print names of all available locales'
complete -c locale -s c -d 'Print the category name for all selected keywords'
complete -c locale -s k -d 'Print the names and values of all selected keywords'
complete -c locale -s m -d 'Print names of all available charmaps'

