# lock
# Autogenerated from man page /usr/share/man/man1/lock.1.gz
complete -c lock -s n -d 'Do not use a timeout value.  Terminal will be locked forever'
complete -c lock -s p -d 'A password is not requested, instead the user\'s current login password is used'
complete -c lock -s t -d 'The time limit (default 15 minutes) is changed to timeout minutes'
complete -c lock -s v -d 'Disable switching virtual terminals while this terminal is locked'

