# lockf
# Autogenerated from man page /usr/share/man/man1/lockf.1.gz
complete -c lockf -s k -d 'Causes the lock file to be kept (not removed) after the command completes'
complete -c lockf -s s -d 'Causes lockf to operate silently'
complete -c lockf -s n -d 'Causes lockf to fail if the specified lock file does not exist'
complete -c lockf -s t -d 'Specifies a timeout for waiting for the lock'
complete -c lockf -s w -d 'Causes lockf to open file for writing rather than reading'

