# logger
# Autogenerated from man page /usr/share/man/man1/logger.1.gz
complete -c logger -s 4 -d 'Force logger to use IPv4 addresses only'
complete -c logger -s 6 -d 'Force logger to use IPv6 addresses only'
complete -c logger -s A -d 'By default, logger tries to send the message to only one address, even if the…'
complete -c logger -s i -d 'Log the process id of the logger process with each line'
complete -c logger -s s -d 'Log the message to standard error, as well as the system log'
complete -c logger -s f -d 'Read the contents of the specified file into syslog'
complete -c logger -s H -d 'Set the hostname in the header of the message to specified value'
complete -c logger -s h -d 'Send the message to the remote system host instead of logging it locally'
complete -c logger -s P -d 'Send the message to the specified port number on a remote system, which can b…'
complete -c logger -s p -d 'Enter the message with the specified priority'
complete -c logger -s S -d 'Specify source address and/or source port when using h option'
complete -c logger -s t -d 'Mark every line in the log with the specified tag rather than the default of …'

