# logins
# Autogenerated from man page /usr/share/man/man1/logins.1.gz
complete -c logins -s a -d 'Display information about the password change and account expiration times fo…'
complete -c logins -s d -d 'Select accounts with duplicate UIDs'
complete -c logins -s g -d 'Select accounts that are members of the specified groups'
complete -c logins -s l -d 'Select accounts matching the specified login names'
complete -c logins -s m -d 'Show information about secondary groups'
complete -c logins -s o -d 'Display the information for each account on a single line of colon-separated …'
complete -c logins -s p -d 'Select accounts with no password'
complete -c logins -s s -d 'Select system accounts'
complete -c logins -s t -d 'Sort selected accounts by name rather than by UID'
complete -c logins -s u -d 'Select user accounts'
complete -c logins -s x -d 'Display information about each account\'s home directory and shell'

