# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
complete -c login -s f -d 'When a user name is specified, this option indicates that proper authenticati…'
complete -c login -s h -d 'Specify the host from which the connection was received'
complete -c login -s p -d 'By default, login discards any previous environment'

