# look
# Autogenerated from man page /usr/share/man/man1/look.1.gz
complete -c look -s d -d 'Dictionary character set and order, i. e'
complete -c look -s f -d 'Ignore the case of alphabetic characters'
complete -c look -s t -d 'Specify a string termination character, i. e'

