# lpr
# Autogenerated from man page /usr/share/man/man1/lpr.1.gz
complete -c lpr -s d -d 'The files are assumed to contain data in DVI format from the TeX typesetting …'
complete -c lpr -s f -d 'Use a filter which interprets the first character of each line as a standard …'
complete -c lpr -s c -d 'The files are assumed to contain data produced by cifplot 1'
complete -c lpr -s g -d 'The files are assumed to contain standard plot data as produced by the Ux plo…'
complete -c lpr -s n -d 'The files are assumed to contain data from ditroff (device independent troff)'
complete -c lpr -s t -d 'The files are assumed to contain C/A/T phototypesetter commands from ancient …'
complete -c lpr -s v -d 'The files are assumed to contain a raster image for devices like the Benson V…'
complete -c lpr -s s -d 'Use symbolic links.  Usually files are copied to the spool directory'
complete -c lpr -o '\\&#' -d 'The quantity num is the number of copies desired of each file named'
complete -c lpr -s L -d 'Use locale specified as argument instead of one found in environment'
complete -c lpr -s Z -d 'Some spoolers, such as LPRng, accept additional per-job options using a Z con…'
complete -c lpr -s i -d 'The output is indented by numcols'
complete -c lpr -s w -d 'Uses num as the page width for pr 1'

