# lptcontrol
# Autogenerated from man page /usr/share/man/man8/lptcontrol.8.gz
complete -c lptcontrol -s e -d 'Turn on extended mode'
complete -c lptcontrol -s i -d 'Turn on interrupt-driven mode'
complete -c lptcontrol -s p -d 'Turn on polled mode'
complete -c lptcontrol -s s -d 'Turn on standard mode, i. e. , turn off extended mode'
complete -c lptcontrol -s d -d 'Set the mode of the printer control device specified by control_device'

