# lsextattr
# Autogenerated from man page /usr/share/man/man8/lsextattr.8.gz
complete -c lsextattr -s f -d '(Force'
complete -c lsextattr -s h -d '(No follow'
complete -c lsextattr -s i -d '(From stdin. ) Read attribute data from stdin instead of as an argument'
complete -c lsextattr -s n -d '( NUL Ns -terminate. ) NUL Ns -terminate the extent content written out'
complete -c lsextattr -s q -d '(Quiet. ) Do not print out the pathname and suppress error messages'
complete -c lsextattr -s s -d '(Stringify. ) Escape nonprinting characters and put quotes around the output'
complete -c lsextattr -s x -d '(Hex. ) Print the output in hexadecimal'

