# lua53
# Autogenerated from man page /usr/local/man/man1/lua53.1.gz
complete -c lua53 -s e -d 'execute statement R stat '
complete -c lua53 -s i -d 'enter interactive mode after executing R script '
complete -c lua53 -s l -d 'execute the equivalent of B name =require(\' name \') before executing R script '
complete -c lua53 -s v -d 'show version information'
complete -c lua53 -s E -d 'ignore environment variables'

