# luac53
# Autogenerated from man page /usr/local/man/man1/luac53.1.gz
complete -c luac53 -s l -d 'produce a listing of the compiled bytecode for Lua\'s virtual machine'
complete -c luac53 -s o -d 'output to R file , instead of the default  luac. out '
complete -c luac53 -s p -d 'load files but do not generate any output file'
complete -c luac53 -s s -d 'strip debug information before writing the output file'
complete -c luac53 -s v -d 'show version information'

