# mailq
# Autogenerated from man page /usr/share/man/man1/mailq.1.gz
complete -c mailq -o Ac -d 'Show the mail submission queue specified in  /etc/mail/submit'
complete -c mailq -o qL -d 'Show the "lost" items in the mail queue instead of the normal queue items'
complete -c mailq -o qQ -d 'Show the quarantined items in the mail queue instead of the normal queue items'
complete -c mailq -o qI -d 'Limit processed jobs to those containing  substr as a substring of the queue …'
complete -c mailq -o qR -d 'Limit processed jobs to those containing  substr as a substring of one of the…'
complete -c mailq -o qS -d 'Limit processed jobs to those containing  substr as a substring of the sender…'
complete -c mailq -s v -d 'Print verbose information'
complete -c mailq -s q -d 'option is used to limit the processed jobs'

