# mail.local
# Autogenerated from man page /usr/share/man/man8/mail.local.8.gz
complete -c 'mail.local' -s B -d 'Turn off the attempts to notify the ``biff\'\' service'
complete -c 'mail.local' -s b -d 'Return a permanent error instead of a temporary error if a mailbox exceeds qu…'
complete -c 'mail.local' -s d -d 'Specify this is a delivery (for backward compatibility)'
complete -c 'mail.local' -s D -d 'Specify the name of the mailbox database which is used to look up local recip…'
complete -c 'mail.local' -s f -d 'Specify the sender\'s name'
complete -c 'mail.local' -s l -d 'Turn on LMTP mode'
complete -c 'mail.local' -s s -d 'Turn off the fsync(2) call that forces the mailbox to be committed to disk be…'
complete -c 'mail.local' -s r -d 'Specify the sender\'s name (for backward compatibility).  Same as -f'
complete -c 'mail.local' -s h -d 'Store incoming mail in filename in the user\'s home directory instead of a sys…'
complete -c 'mail.local' -s H -d 'Select hashed mail directories'
complete -c 'mail.local' -s p -d 'Specify an alternate mail spool path'
complete -c 'mail.local' -s 7 -d 'Do not advertise 8BITMIME support in LMTP mode'
complete -c 'mail.local' -s n -d 'Specify that the domain part of recipient addresses in LMTP mode should not b…'

