# mailstats
# Autogenerated from man page /usr/share/man/man8/mailstats.8.gz
complete -c mailstats -s C -d 'Read the specified file instead of the default  sendmail configuration file'
complete -c mailstats -s c -d 'Try to use submit. cf instead of the default  sendmail configuration file'
complete -c mailstats -s f -d 'Read the specified statistics file instead of the statistics file specified i…'
complete -c mailstats -s P -d 'Output information in program-readable mode without clearing statistics'
complete -c mailstats -s p -d 'Output information in program-readable mode and clear statistics'
complete -c mailstats -s o -d 'Don\'t display the name of the mailer in the output'

