# makemap
# Autogenerated from man page /usr/share/man/man8/makemap.8.gz
complete -c makemap -s C -d 'Use the specified  sendmail configuration file for looking up the TrustedUser…'
complete -c makemap -s N -d 'Include the null byte that terminates strings  in the map'
complete -c makemap -s c -d 'Use the specified hash and B-Tree cache size'
complete -c makemap -s D -d 'Use to specify the character to use to indicate a comment (which is ignored) …'
complete -c makemap -s d -d 'Allow duplicate keys in the map'
complete -c makemap -s e -d 'Allow empty value (right hand side)'
complete -c makemap -s f -d 'Normally all upper case letters in the key  are folded to lower case'
complete -c makemap -s l -d 'List supported map types'
complete -c makemap -s o -d 'Append to an old file.    This allows you to augment an existing file'
complete -c makemap -s r -d 'Allow replacement of existing keys'
complete -c makemap -s s -d 'Ignore safety checks on maps being created'
complete -c makemap -s t -d 'Use the specified delimiter instead of white space (also for dumping a map)'
complete -c makemap -s u -d 'dump (unmap) the content of the database to standard output'
complete -c makemap -s v -d 'Verbosely print what it is doing'

