# manctl
# Autogenerated from man page /usr/share/man/man8/manctl.8.gz
complete -c manctl -o help -d 'Print options and exit'
complete -c manctl -o compress -d 'Compress uncompressed man pages (eliminating . so\'s)'
complete -c manctl -o uncompress -d 'Uncompress compressed man pages.  El SEE ALSO man 1'

