# manpath
# Autogenerated from man page /usr/share/man/man1/manpath.1.gz
complete -c manpath -s L -d 'Output manual locales list instead of the manual path'
complete -c manpath -s d -d 'Print extra debugging information'
complete -c manpath -s q -d 'Suppresses warning messages'

