# mckey
# Autogenerated from man page /usr/share/man/man1/mckey.1.gz
complete -c mckey -s m -d 'IP multicast address to join'
complete -c mckey -s M -d 'RDMA transport specific multicast address to join'
complete -c mckey -s s -d 'Send datagrams to the multicast group'
complete -c mckey -s b -d 'The local network address to bind to'
complete -c mckey -s c -d 'The number of QPs to join the multicast group.   (default 1)'
complete -c mckey -s C -d 'The number of messages to transfer over each connection.   (default 10)'
complete -c mckey -s S -d 'The size of each message transferred, in bytes'

