# mdocml
# Autogenerated from man page /usr/share/man/man1/mdocml.1.gz
complete -c mdocml -s a -d 'If the standard output is a terminal device and c is not specified, use less …'
complete -c mdocml -s c -d 'Copy the formatted manual pages to the standard output without using less 1 t…'
complete -c mdocml -s I -d 'Override the default operating system name for the mdoc 7 \\&Os and for the ma…'
complete -c mdocml -s K -d 'Specify the input encoding'
complete -c mdocml -o mdoc -d 'With mdoc, all input files are interpreted as mdoc 7'
complete -c mdocml -s O -d 'Comma-separated output options'
complete -c mdocml -s T -d 'Select the output format'
complete -c mdocml -s W -d 'Specify the minimum message level to be reported on the standard error output…'

