# memcontrol
# Autogenerated from man page /usr/share/man/man8/memcontrol.8.gz
complete -c memcontrol -s a -d 'List all range slots, even those that are inactive'
complete -c memcontrol -s b -d 'Memory range base address'
complete -c memcontrol -s l -d 'Length of memory range in bytes, power of 2'
complete -c memcontrol -s o -d 'Text identifier for this setting (7 char max)'

