# mfiutil
# Autogenerated from man page /usr/share/man/man8/mfiutil.8.gz
complete -c mfiutil -s D -d 'device specifies the device node of the controller to use'
complete -c mfiutil -s t -d 'type specifies the type of the controller to work with either mfi 4 or mrsas 4'
complete -c mfiutil -s u -d 'unit specifies the unit of the controller to work with'
complete -c mfiutil -s d -d 'Print numeric device IDs as drive identifier.  This is the default'
complete -c mfiutil -s e -d 'Print drive identifiers in enclosure:slot form'

