# ministat
# Autogenerated from man page /usr/share/man/man1/ministat.1.gz
complete -c ministat -s A -d 'Just report the statistics of the input and relative comparisons, suppress th…'
complete -c ministat -s n -d 'Just report the raw statistics of the input, suppress the ASCII-art plot and …'
complete -c ministat -s q -d 'Suppress printing of summary statistics and data-set names; typically for use…'
complete -c ministat -s s -d 'Print the average/median/stddev bars on separate lines in the ASCII-art plot,…'
complete -c ministat -s C -d 'Specify which column of data to use'
complete -c ministat -s c -d 'Specify desired confidence level for Student\'s T analysis'
complete -c ministat -s d -d 'Specifies the column delimiter characters, default is SPACE and TAB'
complete -c ministat -s w -d 'Width of ASCII-art plot in characters'

