# mixer
# Autogenerated from man page /usr/share/man/man8/mixer.8.gz
complete -c mixer -s a -d 'Print the values for all mixer devices available in the system see Sx FILES'
complete -c mixer -s d -d 'Change the default audio card to unit.  The unit has to be an integer value'
complete -c mixer -s f -d 'Open device as the mixer device see Sx FILES'
complete -c mixer -s h -d 'Print a help message'
complete -c mixer -s o -d 'Print mixer values in a format suitable for use inside scripts'
complete -c mixer -s s -d 'Print only the recording source(s) of the mixer device'

