# mkcsmapper
# Autogenerated from man page /usr/share/man/man1/mkcsmapper.1.gz
complete -c mkcsmapper -s d -d 'Turns on debug mode'
complete -c mkcsmapper -s m -d 'Generate mapping data from infile'
complete -c mkcsmapper -s o -d 'Put generated binary data to outfile'
complete -c mkcsmapper -s p -d 'Generate pivot data from outfile'

