# mkdep
# Autogenerated from man page /usr/share/man/man1/mkdep.1.gz
complete -c mkdep -s a -d 'Append to the output file, so that multiple mkdep Ns \'s may be run from a sin…'
complete -c mkdep -s f -d 'Write the include file dependencies to file, instead of the default ``'
complete -c mkdep -s p -d 'Cause mkdep to produce dependencies of the form: -literal -offset indent prog…'

