# mkdir
# Autogenerated from man page /usr/share/man/man1/mkdir.1.gz
complete -c mkdir -s m -d 'Set the file permission bits of the final created directory to the specified …'
complete -c mkdir -s p -d 'Create intermediate directories as required'
complete -c mkdir -s v -d 'Be verbose when creating directories, listing them as they are created'

