# mkesdb
# Autogenerated from man page /usr/share/man/man1/mkesdb.1.gz
complete -c mkesdb -s d -d 'Turns on debug mode'
complete -c mkesdb -s m -d 'Process directory catalog or alias file'
complete -c mkesdb -s o -d 'Put generated binary data to outfile'

