# mknetid
# Autogenerated from man page /usr/share/man/man8/mknetid.8.gz
complete -c mknetid -s q -d 'Normally, mknetid prints a warning message when it encounters a duplicate net…'
complete -c mknetid -s g -d 'Specify the location of the group information file'
complete -c mknetid -s p -d 'Specify the location of the passwd information file'
complete -c mknetid -s h -d 'Specify the location of the hosts database file'
complete -c mknetid -s n -d 'Specify the location of the netid information file'
complete -c mknetid -s d -d 'By default, the mknetid utility uses the system domainname when generating ne…'

