# mktemp
# Autogenerated from man page /usr/share/man/man1/mktemp.1.gz
complete -c mktemp -s d -d 'Make a directory instead of a file'
complete -c mktemp -s p -d 'Use tmpdir for the t flag if the TMPDIR environment variable is not set'
complete -c mktemp -s q -d 'Fail silently if an error occurs'
complete -c mktemp -s t -d 'Generate a template (using the supplied prefix and TMPDIR if set) to create a…'
complete -c mktemp -s u -d 'Operate in unsafe mode.  The temp file will be unlinked before mktemp exits'

