# mkuzip
# Autogenerated from man page /usr/share/man/man8/mkuzip.8.gz
complete -c mkuzip -s A -d 'Select a specific compression algorithm'
complete -c mkuzip -s C -d 'Select the integer compression level used to parameterize the chosen compress…'
complete -c mkuzip -s d -d 'Enable de-duplication'
complete -c mkuzip -s j -d 'Specify the number of compression jobs that mkuzip runs in parallel to speed …'
complete -c mkuzip -s o -d 'Name of the output file outfile'
complete -c mkuzip -s S -d 'Print summary about the compression ratio as well as output file size after f…'
complete -c mkuzip -s s -d 'Split the image into clusters of cluster_size bytes, 16384 bytes by default'
complete -c mkuzip -s v -d 'Display verbose messages'
complete -c mkuzip -s Z -d 'Disable zero-block detection and elimination'

