# morse
# Autogenerated from man page /usr/share/man/man6/morse.6.gz
complete -c morse -s l -d 'The l option produces output suitable for led 4 devices'
complete -c morse -s s -d 'The s option produces dots and dashes rather than words'
complete -c morse -s p -d 'Send morse the real way'
complete -c morse -s w -d 'Set the sending speed in words per minute'
complete -c morse -s c -d 'Farnsworth support.  Set the spacing between characters in words per minute'
complete -c morse -s f -d 'Set the sidetone frequency to something other than the default 600 Hz'
complete -c morse -s d -d 'Similar to p, but use the RTS line of device (which must be a TTY device) in …'
complete -c morse -s e -d 'Echo each character before it is sent, used together with either p or d'
complete -c morse -s r -d 'Decode morse output consisting of dots and dashes (as generated by using the …'

