# mountd
# Autogenerated from man page /usr/share/man/man8/mountd.8.gz
complete -c mountd -s 2 -d 'Allow the administrator to force clients to use only the version 2 NFS protoc…'
complete -c mountd -s d -d 'Output debugging information'
complete -c mountd -s e -d 'Ignored; included for backward compatibility'
complete -c mountd -s h -d 'Specify specific IP addresses to bind to for TCP and UDP requests'
complete -c mountd -s l -d 'Cause all succeeded mountd requests to be logged'
complete -c mountd -s n -d 'Allow non-root mount requests to be served'
complete -c mountd -s p -d 'Force mountd to bind to the specified port, for both AF_INET and AF_INET6 add…'
complete -c mountd -s R -d 'Do not support the Mount protocol and do not register with rpcbind 8'
complete -c mountd -s r -d 'Allow mount RPCs requests for regular files to be served'
complete -c mountd -s S -d 'Tell mountd to suspend/resume execution of the nfsd threads whenever the expo…'

