# mount_msdosfs
# Autogenerated from man page /usr/share/man/man8/mount_msdosfs.8.gz
complete -c mount_msdosfs -s o -d 'Use the specified mount options, as described in mount 8'
complete -c mount_msdosfs -s u -d 'Set the owner of the files in the file system to uid'
complete -c mount_msdosfs -s g -d 'Set the group of the files in the file system to gid'
complete -c mount_msdosfs -s m -d 'Specify the maximum file permissions for files in the file system'
complete -c mount_msdosfs -s M -d 'Specify the maximum file permissions for directories in the file system'
complete -c mount_msdosfs -s s -d 'Force behaviour to ignore and not generate Win\'95 long filenames'
complete -c mount_msdosfs -s l -d 'Force listing and generation of Win\'95 long filenames and separate creation/m…'
complete -c mount_msdosfs -s 9 -d 'Ignore the special Win\'95 directory entries even if deleting or renaming a fi…'
complete -c mount_msdosfs -s L -d 'Specify locale name used for file name conversions for DOS and Win\'95 names'
complete -c mount_msdosfs -s D -d 'Specify the MS-DOS code page (aka IBM/OEM code page) name used for file name …'
complete -c mount_msdosfs -s W -d 'Em This option is preserved for backward compatibility purpose only, and will…'

