# mount_udf
# Autogenerated from man page /usr/share/man/man8/mount_udf.8.gz
complete -c mount_udf -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_udf -s v -d 'Be verbose about mounting the UDF file system'
complete -c mount_udf -s C -d 'Specify local charset to convert Unicode file names'

