# mount
# Autogenerated from man page /usr/share/man/man8/mount.8.gz
complete -c mount -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c mount -s a -d 'All the file systems described in fstab 5 are mounted'
complete -c mount -s d -d 'Causes everything to be done except for the actual system call'
complete -c mount -s F -d 'Specify the fstab file to use'
complete -c mount -s f -d 'Forces the revocation of write access when trying to downgrade a file system …'
complete -c mount -s L -d 'When used in conjunction with the a option, mount only those file systems whi…'
complete -c mount -s l -d 'When used in conjunction with the a option, also mount those file systems whi…'
complete -c mount -s n -d 'For compatibility with some other implementations, this flag is currently a n…'
complete -c mount -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount -s p -d 'Print mount information in fstab 5 format.  Implies also the v option'
complete -c mount -s r -d 'The file system is to be mounted read-only'
complete -c mount -s t -d 'The argument following the t is used to indicate the file system type'
complete -c mount -s u -d 'The u flag indicates that the status of an already mounted file system should…'
complete -c mount -s v -d 'Verbose mode'
complete -c mount -s w -d 'The file system object is to be read and write.  El ENVIRONMENT -tag -width "'

