# mount_cd9660
# Autogenerated from man page /usr/share/man/man8/mount_cd9660.8.gz
complete -c mount_cd9660 -s b -d 'Relax checking for Supplementary Volume Descriptor Flags field which is set t…'
complete -c mount_cd9660 -s e -d 'Enable the use of extended attributes'
complete -c mount_cd9660 -s g -d 'Do not strip version numbers on files'
complete -c mount_cd9660 -s j -d 'Do not use any Joliet extensions included in the file system'
complete -c mount_cd9660 -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_cd9660 -s r -d 'Do not use any Rockridge extensions included in the file system'
complete -c mount_cd9660 -s s -d 'Start the file system at startsector'
complete -c mount_cd9660 -s C -d 'Specify local charset to convert Unicode file names when using Joliet extensi…'
complete -c mount_cd9660 -s v -d 'Be verbose about the starting sector decisions made'

