# mount_fusefs
# Autogenerated from man page /usr/share/man/man8/mount_fusefs.8.gz
complete -c mount_fusefs -s A -d 'Prohibit the allow_other mount flag'
complete -c mount_fusefs -s S -d 'Run in safe mode (i. e. , reject invoking a filesystem daemon)'
complete -c mount_fusefs -s v -d 'Be verbose'
complete -c mount_fusefs -s D -d 'Call the specified daemon'
complete -c mount_fusefs -s O -d 'Add opts to the daemon\'s command line'
complete -c mount_fusefs -s s -d 'Use special as special'
complete -c mount_fusefs -s m -d 'Mount on node'
complete -c mount_fusefs -s h -d 'Show help'
complete -c mount_fusefs -s V -d 'Show version information'
complete -c mount_fusefs -s o -d 'Mount options are specified via o'

