# mount_unionfs
# Autogenerated from man page /usr/share/man/man8/mount_unionfs.8.gz
complete -c mount_unionfs -s b -d 'Deprecated.  Use o Cm below instead'
complete -c mount_unionfs -s o -d 'Options are specified with the o flag followed by an option'

