# msgs
# Autogenerated from man page /usr/share/man/man1/msgs.1.gz
complete -c msgs -s y -d 'Type the rest of the message.  RETURN Synonym for y'
complete -c msgs -s n -d 'Skip this message and go on to the next message'
complete -c msgs -s q -d 'Drop out of msgs ; the next time msgs will pick up where it last left off'
complete -c msgs -s s -d 'Append the current message to the file ``Messages\'\' in the current directory;…'
complete -c msgs -s m -d 'A copy of the specified message is placed in a temporary mailbox and mail 1 i…'
complete -c msgs -s f -d 'Do not say ``No new messages. \'\'.  This is useful in a '
complete -c msgs -s h -d 'Print the first part of messages only'
complete -c msgs -s l -d 'Cause only locally originated messages to be reported'
complete -c msgs -s p -d 'Pipe long messages through less 1'

