# mt
# Autogenerated from man page /usr/share/man/man1/mt.1.gz
complete -c mt -s v -d 'Print additional status information, such as the maximum supported I/O size'
complete -c mt -s x -d 'Print all available status data to stdout in XML format'
complete -c mt -s l -d 'List parameters, values and descriptions'
complete -c mt -s p -d 'Specify the parameter name to list (with l ) or set (with s )'
complete -c mt -s q -d 'Enable quiet mode for parameter listing'
complete -c mt -s s -d 'Specify the parameter value to set'
complete -c mt -s b -d 'Set the Recover Buffered Data Protected bit'
complete -c mt -s d -d 'Disable all protection information settings'
complete -c mt -s e -d 'Enable all protection information settings'
complete -c mt -s L -d 'Set the length of the protection information in bytes'
complete -c mt -s m -d 'Specify the numeric value for the protection method'
complete -c mt -s r -d 'Set the LBP_R parameter'
complete -c mt -s w -d 'Set the LBP_W parameter'
complete -c mt -s f -d 'Relocate to the given file number'

