# mv
# Autogenerated from man page /usr/share/man/man1/mv.1.gz
complete -c mv -s f -d 'Do not prompt for confirmation before overwriting the destination path'
complete -c mv -s h -d 'If the target operand is a symbolic link to a directory, do not follow it'
complete -c mv -s i -d 'Cause mv to write a prompt to standard error before moving a file that would …'
complete -c mv -s n -d 'Do not overwrite an existing file'
complete -c mv -s v -d 'Cause mv to be verbose, showing files after they are moved'

