# nanobsd.sh
# Autogenerated from man page /usr/share/man/man8/nanobsd.sh.8.gz
complete -c 'nanobsd.sh' -s b -d 'Skip the build stages (both for kernel and world)'
complete -c 'nanobsd.sh' -s c -d 'Specify the configuration file to use'
complete -c 'nanobsd.sh' -s f -d 'Skip the code slice extraction'
complete -c 'nanobsd.sh' -s h -d 'Display usage information'
complete -c 'nanobsd.sh' -s i -d 'Skip the disk image build stage'
complete -c 'nanobsd.sh' -s K -d 'Skip the installkernel stage of the build'
complete -c 'nanobsd.sh' -s k -d 'Skip the buildkernel stage of the build'
complete -c 'nanobsd.sh' -s n -d 'Do not cleanup before each build stage'
complete -c 'nanobsd.sh' -s q -d 'Make output more quiet'
complete -c 'nanobsd.sh' -s v -d 'Make output more verbose'
complete -c 'nanobsd.sh' -s w -d 'Skip the buildworld stage of the build'
complete -c 'nanobsd.sh' -s X -d 'Make native-xtools.  El Pp The features of nanobsd'

