# nanobsd
# Autogenerated from man page /usr/share/man/man8/nanobsd.8.gz
complete -c nanobsd -s b -d 'Skip the build stages (both for kernel and world)'
complete -c nanobsd -s c -d 'Specify the configuration file to use'
complete -c nanobsd -s f -d 'Skip the code slice extraction'
complete -c nanobsd -s h -d 'Display usage information'
complete -c nanobsd -s i -d 'Skip the disk image build stage'
complete -c nanobsd -s K -d 'Skip the installkernel stage of the build'
complete -c nanobsd -s k -d 'Skip the buildkernel stage of the build'
complete -c nanobsd -s n -d 'Do not cleanup before each build stage'
complete -c nanobsd -s q -d 'Make output more quiet'
complete -c nanobsd -s v -d 'Make output more verbose'
complete -c nanobsd -s w -d 'Skip the buildworld stage of the build'
complete -c nanobsd -s X -d 'Make native-xtools'

