# nawk
# Autogenerated from man page /usr/share/man/man1/nawk.1.gz
complete -c nawk -s d -d 'Debug mode.  Set debug level to n, or 1 if n is not specified'
complete -c nawk -s F -d 'Define the input field separator to be the regular expression fs'
complete -c nawk -s f -d 'Read program code from the specified file progfile instead of from the comman…'
complete -c nawk -o safe -d 'Disable file output ( Ic print No >, print No >> ), process creation Po cmd |…'
complete -c nawk -o version -d 'Print the version number of nawk to standard output and exit'
complete -c nawk -s v -d 'Assign value to variable var before prog is executed; any number of v options…'

