# ndp
# Autogenerated from man page /usr/share/man/man8/ndp.8.gz
complete -c ndp -s a -d 'Dump the currently existing NDP entries'
complete -c ndp -s A -d 'Repeat a (dump NDP entries) every wait seconds'
complete -c ndp -s c -d 'Erase all the NDP entries'
complete -c ndp -s d -d 'Delete specified NDP entry'
complete -c ndp -s f -d 'Cause the file filename to be read and multiple entries to be set in the NDP …'
complete -c ndp -s H -d 'Harmonize consistency between the routing table and the default router list; …'
complete -c ndp -s I -d 'Shows the default interface used as the default route when there is no defaul…'
complete -c ndp -s i -d 'View ND information for the specified interface'
complete -c ndp -s n -d 'Do not try to resolve numeric addresses to hostnames'
complete -c ndp -s p -d 'Show prefix list'
complete -c ndp -s P -d 'Flush all the entries in the prefix list'
complete -c ndp -s r -d 'Show default router list'
complete -c ndp -s R -d 'Flush all the entries in the default router list'
complete -c ndp -s s -d 'Register an NDP entry for a node'
complete -c ndp -s t -d 'Print timestamp for each entry, to make it possible to merge the output with …'

