# newkey
# Autogenerated from man page /usr/share/man/man8/newkey.8.gz
complete -c newkey -s h -d 'Create a new public key for the super-user at the given hostname'
complete -c newkey -s u -d 'Create a new public key for the given username'

