# newsyslog
# Autogenerated from man page /usr/share/man/man8/newsyslog.8.gz
complete -c newsyslog -s f -d 'Instruct newsyslog to use config_file instead of /etc/newsyslog'
complete -c newsyslog -s a -d 'Specify a directory into which archived log files will be written'
complete -c newsyslog -s d -d 'Specify a directory which all log files will be relative to'
complete -c newsyslog -s v -d 'Place newsyslog in verbose mode'
complete -c newsyslog -s n -d 'Cause newsyslog not to trim the logs, but to print out what it would do if th…'
complete -c newsyslog -s r -d 'Remove the restriction that newsyslog must be running as root'
complete -c newsyslog -s s -d 'Specify that newsyslog should not send any signals to any daemon processes th…'
complete -c newsyslog -s t -d 'If specified newsyslog will create the rotated logfiles using the specified t…'
complete -c newsyslog -s C -d 'If specified once, then newsyslog will create any log files which do not exis…'
complete -c newsyslog -s F -d 'Force newsyslog to trim the logs, even if the trim conditions have not been m…'
complete -c newsyslog -s N -d 'Do not perform any rotations'
complete -c newsyslog -s P -d 'Prevent further action if we should send signal but the pidfile is empty or d…'
complete -c newsyslog -s R -d 'Specify that newsyslog should rotate a given list of files, even if trim cond…'
complete -c newsyslog -s S -d 'Use pidfile as syslogd 8 Ns \'s pidfile'

