# nex
# Autogenerated from man page /usr/share/man/man1/nex.1.gz
complete -c nex -s c -d 'Execute cmd on the first file loaded'
complete -c nex -s e -d 'Start editing in ex mode, as if the command name were nex ex'
complete -c nex -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c nex -s R -d 'Start editing in read-only mode, as if the command name was nex view, or the …'
complete -c nex -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c nex -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c nex -s s -d 'Enter batch mode; applicable only to nex ex edit sessions'
complete -c nex -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c nex -s v -d 'Start editing in vi mode, as if the command name was nex vi'
complete -c nex -s w -d 'Set the initial window size to the specified number of lines'

