# nextboot
# Autogenerated from man page /usr/share/man/man8/nextboot.8.gz
complete -c nextboot -s a -d 'This option causes nextboot to append to an existing configuration in /boot/n…'
complete -c nextboot -s D -d 'Invoking nextboot with this option removes an existing nextboot configuration'
complete -c nextboot -s e -d 'This option adds the provided variable and value to the kernel environment'
complete -c nextboot -s f -d 'This option disables the sanity checking which checks if the kernel really ex…'
complete -c nextboot -s k -d 'This option specifies a kernel directory relative to /boot to load the kernel…'
complete -c nextboot -s o -d 'This option allows the passing of kernel flags for the next boot'

