# nfscbd
# Autogenerated from man page /usr/share/man/man8/nfscbd.8.gz
complete -c nfscbd -s p -d 'Specifies what port# the callback server should use'
complete -c nfscbd -s P -d 'Specifies the host based principal name to be used as the target for callback…'

