# nfsd
# Autogenerated from man page /usr/share/man/man8/nfsd.8.gz
complete -c nfsd -s r -d 'Register the NFS service with rpcbind 8 without creating any servers'
complete -c nfsd -s d -d 'Unregister the NFS service with rpcbind 8 without creating any servers'
complete -c nfsd -s V -d 'Specifies a hostname to be used as a principal name, instead of the default h…'
complete -c nfsd -s n -d 'Specifies how many servers to create'
complete -c nfsd -l maxthreads -d 'Specifies the maximum servers that will be kept around to service requests'
complete -c nfsd -l minthreads -d 'Specifies the minimum servers that will be kept around to service requests'
complete -c nfsd -s h -d 'Specifies which IP address or hostname to bind to on the local host'
complete -c nfsd -s a -d 'Specifies that nfsd should bind to the wildcard IP address'
complete -c nfsd -s p -d 'Enables pNFS support in the server and specifies the information that the dae…'
complete -c nfsd -s m -d 'This option is only meaningful when used with the p option'
complete -c nfsd -s t -d 'Serve TCP NFS clients'
complete -c nfsd -s u -d 'Serve UDP NFS clients'
complete -c nfsd -s e -d 'Ignored; included for backward compatibility'

