# nfsdumpstate
# Autogenerated from man page /usr/share/man/man8/nfsdumpstate.8.gz
complete -c nfsdumpstate -s o -d 'Displays a summary of Clients for NFSv4'
complete -c nfsdumpstate -s l -d 'Displays a list of all NFSv4 Opens and Locks on the file specified by the fil…'

