# nfsstat
# Autogenerated from man page /usr/share/man/man1/nfsstat.1.gz
complete -c nfsstat -s c -d 'Only display client side statistics'
complete -c nfsstat -s d -d 'Display statistics for the NFS server that are similar to those displayed by …'
complete -c nfsstat -s e -d 'Report the extra statistics collected by the NFS client and server for NFSv4'
complete -c nfsstat -s E -d 'Similar to e except that the statistics include NFSv4. 1 and NFSv4'
complete -c nfsstat -s M -d 'Deprecated and ignored'
complete -c nfsstat -s m -d 'Report the mount options for all NFS client mounts'
complete -c nfsstat -s N -d 'Deprecated and ignored'
complete -c nfsstat -s s -d 'Only display server side statistics'
complete -c nfsstat -s W -d 'Use wide format with interval short summary'
complete -c nfsstat -s w -d 'Display a shorter summary of NFS activity for both the client and server at w…'
complete -c nfsstat -s z -d 'Reset statistics after displaying them'
complete -c nfsstat -s q -d 'Do not print header'
complete -c nfsstat -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'

