# nfsuserd
# Autogenerated from man page /usr/share/man/man8/nfsuserd.8.gz
complete -c nfsuserd -o domain -d 'This option allows you to override the default DNS domain name, which is acqu…'
complete -c nfsuserd -o usertimeout -d 'Overrides the default timeout for cache entries, in minutes'
complete -c nfsuserd -o usermax -d 'Overrides the default upper bound on the cache size'
complete -c nfsuserd -o verbose -d 'When set, the server logs a bunch of information to syslog'
complete -c nfsuserd -o force -d 'This flag option must be set to restart the daemon after it has gone away abn…'
complete -c nfsuserd -o manage-gids -d 'This flag enables manage-gids for the NFS server nfsd 8'

