# nghook
# Autogenerated from man page /usr/share/man/man8/nghook.8.gz
complete -c nghook -s a -d 'Output each packet read in human-readable decoded ASCII form instead of raw b…'
complete -c nghook -s d -d 'Increase the debugging verbosity level'
complete -c nghook -s e -d 'Execute the program specified by the third argument'
complete -c nghook -s l -d 'Loops all received data back to the hook in addition to writing it to standar…'
complete -c nghook -s m -d 'Before executing the program (in e mode) send the given ASCII control message…'
complete -c nghook -s n -d 'Do not attempt to read any data from standard input'
complete -c nghook -s S -d 'Use file descriptor 0 for output instead of the default 1'
complete -c nghook -s s -d 'Use file descriptor 1 for input instead of the default 0'

