# nproc
# Autogenerated from man page /usr/share/man/man1/nproc.1.gz
complete -c nproc -l all -d 'Count all processors currently online'
complete -c nproc -l ignore -d 'The result is decreased by count, but never below 1'
complete -c nproc -l version -d 'Print the current program version and exit.  Do not use this option'
complete -c nproc -l help -d 'Print usage information and exit'

