# nscd
# Autogenerated from man page /usr/share/man/man8/nscd.8.gz
complete -c nscd -s n -d 'Do not daemonize; nscd will not fork or disconnect itself from the terminal'
complete -c nscd -s s -d 'Single-threaded mode'
complete -c nscd -s t -d 'Trace mode.  All trace messages will be written to stdout'
complete -c nscd -s i -d 'Invalidates personal cache'
complete -c nscd -s I -d 'Invalidates the cache for every user'

