# ntpd
# Autogenerated from man page /usr/share/man/man8/ntpd.8.gz
complete -c ntpd -o '\\&?' -d 'Display usage information and exit'
complete -c ntpd -o '\\&' -d 'Pass the extended usage information through a pager'
complete -c ntpd -o '\\-version' -d 'Output version of program and exit'

