# ntpdc
# Autogenerated from man page /usr/share/man/man8/ntpdc.8.gz
complete -c ntpdc -o '\\&?' -d 'Display usage information and exit'
complete -c ntpdc -o '\\&' -d 'Pass the extended usage information through a pager'
complete -c ntpdc -s '>' -d 'Save the option state to \\fIcfgfile\\fP'
complete -c ntpdc -s '<' -d 'Load options from \\fIcfgfile\\fP'
complete -c ntpdc -o '\\-version' -d 'Output version of program and exit'

