# ntptime
# Autogenerated from man page /usr/share/man/man8/ntptime.8.gz
complete -c ntptime -s c -d 'Display the execution time of ntptime itself'
complete -c ntptime -s e -d 'Specify estimated error, in microseconds'
complete -c ntptime -s f -d 'Specify frequency offset, in parts per million'
complete -c ntptime -s h -d 'Display help information'
complete -c ntptime -s m -d 'Specify max possible errors, in microseconds'
complete -c ntptime -s o -d 'Specify clock offset, in microseconds'
complete -c ntptime -s r -d 'Display Unix and NTP times in raw format'
complete -c ntptime -s s
complete -c ntptime -s t -d 'Specify time constant, an integer in the range 0-4'

