# nvi
# Autogenerated from man page /usr/share/man/man1/nvi.1.gz
complete -c nvi -s c -d 'Execute cmd on the first file loaded'
complete -c nvi -s e -d 'Start editing in ex mode, as if the command name were nvi ex'
complete -c nvi -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c nvi -s R -d 'Start editing in read-only mode, as if the command name was nvi view, or the …'
complete -c nvi -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c nvi -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c nvi -s s -d 'Enter batch mode; applicable only to nvi ex edit sessions'
complete -c nvi -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c nvi -s v -d 'Start editing in vi mode, as if the command name was nvi vi'
complete -c nvi -s w -d 'Set the initial window size to the specified number of lines'

