# nview
# Autogenerated from man page /usr/share/man/man1/nview.1.gz
complete -c nview -s c -d 'Execute cmd on the first file loaded'
complete -c nview -s e -d 'Start editing in ex mode, as if the command name were nview ex'
complete -c nview -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c nview -s R -d 'Start editing in read-only mode, as if the command name was nview view, or th…'
complete -c nview -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c nview -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c nview -s s -d 'Enter batch mode; applicable only to nview ex edit sessions'
complete -c nview -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c nview -s v -d 'Start editing in vi mode, as if the command name was nview vi'
complete -c nview -s w -d 'Set the initial window size to the specified number of lines'

