# nvram
# Autogenerated from man page /usr/share/man/man8/nvram.8.gz
complete -c nvram -s d -d 'Delete the variable selected by name from the EEPROM or NVRAM'
complete -c nvram -s p -d 'Print all available configuration variables and their current values'

