# openssl-format-options
# Autogenerated from man page /usr/share/openssl/man/man1/openssl-format-options.1.gz
complete -c openssl-format-options -o inform -o outform -d 'The format of the input or output streams'
complete -c openssl-format-options -o keyform -d 'Format of a private key input source'
complete -c openssl-format-options -o CRLform -d 'Format of a \\s-1CRL\\s0 input source'

