# pac
# Autogenerated from man page /usr/share/man/man8/pac.8.gz
complete -c pac -s P -d 'Accounting is done for the named printer'
complete -c pac -s c -d 'Cause the output to be sorted by cost; usually the output is sorted alphabeti…'
complete -c pac -s m -d 'Cause the host name to be ignored in the accounting file'
complete -c pac -s p -d 'The value price is used for the cost in dollars instead of the default value …'
complete -c pac -s r -d 'Reverse the sorting order'
complete -c pac -s s -d 'Accounting information is summarized on the summary accounting file; this sum…'

