# passwd
# Autogenerated from man page /usr/share/man/man1/passwd.1.gz
complete -c passwd -s l -d 'Cause the password to be updated only in the local password file, and not wit…'
complete -c passwd -s y -d 'Override passwd Ns \'s checking heuristics and forces it into NIS mode'
complete -c passwd -s d -d 'Specify what domain to use when changing an NIS password'
complete -c passwd -s h -d 'Specify the name of an NIS server'
complete -c passwd -s o -d 'Do not automatically override the password authentication checks for the supe…'

