# paste
# Autogenerated from man page /usr/share/man/man1/paste.1.gz
complete -c paste -s d -d 'Use one or more of the provided characters to replace the newline characters …'
complete -c paste -s s -d 'Concatenate all of the lines of each separate input file in command line order'

