# patch
# Autogenerated from man page /usr/share/man/man1/patch.1.gz
complete -c patch -s b -d 'Save a backup copy of the file before it is modified'
complete -c patch -s C -d 'Checks that the patch would apply cleanly, but does not modify anything'
complete -c patch -s c -d 'Forces patch to interpret the patch file as a context diff'
complete -c patch -s E -d 'Causes patch to remove output files that are empty after the patches have bee…'
complete -c patch -s e -d 'Forces patch to interpret the patch file as an ed 1 script'
complete -c patch -s f -d 'Forces patch to assume that the user knows exactly what he or she is doing, a…'
complete -c patch -s l -d 'Causes the pattern matching to be done loosely, in case the tabs and spaces h…'
complete -c patch -s N -d 'Causes patch to ignore patches that it thinks are reversed or already applied'
complete -c patch -s n -d 'Forces patch to interpret the patch file as a normal diff'
complete -c patch -s R -d 'Tells patch that this patch was created with the old and new files swapped'
complete -c patch -s t -d 'Similar to f, in that it suppresses questions, but makes some different assum…'
complete -c patch -s u -d 'Forces patch to interpret the patch file as a unified context diff (a unidiff)'
complete -c patch -s v -d 'Causes patch to print out its revision header and patch level'
complete -c patch -l posix -d 'Enables strict -p1003'

