# pflogd
# Autogenerated from man page /usr/share/man/man8/pflogd.8.gz
complete -c pflogd -s D -d 'Debugging mode.  pflogd does not disassociate from the controlling terminal'
complete -c pflogd -s d -d 'Time in seconds to delay between automatic flushes of the file'
complete -c pflogd -s f -d 'Log output filename.  Default is /var/log/pflog'
complete -c pflogd -s i -d 'Specifies the pflog 4 interface to use.  By default, pflogd will use pflog0'
complete -c pflogd -s p -d 'Writes a file containing the process ID of the program to /var/run'
complete -c pflogd -s s -d 'Analyze at most the first snaplen bytes of data from each packet rather than …'
complete -c pflogd -s x -d 'Check the integrity of an existing log file, and return'

