# pkg-which
# Autogenerated from man page /usr/local/man/man8/pkg-which.8.gz
complete -c pkg-which -s g -d 'Treat file Ac as a glob pattern'
complete -c pkg-which -s m -d 'Show files that matched the glob pattern (requires --glob)'
complete -c pkg-which -s o -d 'Show the origin of the package instead of name-version'
complete -c pkg-which -s p -d 'Search for the filename in PATH'
complete -c pkg-which -s q -d 'Be quiet'

