# pkg-create
# Autogenerated from man page /usr/local/man/man8/pkg-create.8.gz
complete -c pkg-create -s a -d 'Create package tarballs from all packages installed on your system'
complete -c pkg-create -s e -d 'The manifest contained in pkg will be expanded to readable UCL format'
complete -c pkg-create -s g -d 'Interpret pkg-name as a shell glob pattern and create package only for instal…'
complete -c pkg-create -s x -d 'Like g, but interpret pkg-name as a regular expression using the "modern" or …'
complete -c pkg-create -s f -d 'Set format as the package output format'
complete -c pkg-create -s l -d 'Set the compression level for created packages'
complete -c pkg-create -s m -d 'Specify the directory containing the package manifest, +MANIFEST and optional…'
complete -c pkg-create -s M -d 'Read all of the package metadata from the manifest file'
complete -c pkg-create -s t -d 'Set the timestamp of the files within the archive'
complete -c pkg-create -s n -d 'Do not overwrite already existing packages'
complete -c pkg-create -s o -d 'Set outdir as the output directory'
complete -c pkg-create -s p -d 'Specify some package metadata using the legacy plist format from pkg_add 1, c…'
complete -c pkg-create -s q -d 'Force quiet output'
complete -c pkg-create -s v -d 'Force verbose output, the opposite of --quiet'
complete -c pkg-create -s r -d 'rootdir specifies the top-level directory to be treated as the root of the fi…'

