# pkg-add
# Autogenerated from man page /usr/local/man/man8/pkg-add.8.gz
complete -c pkg-add -s A -d 'Mark the installed packages as automatic'
complete -c pkg-add -s f -d 'Force the reinstallation of the package if already installed'
complete -c pkg-add -s I -d 'If any installation scripts (pre-install or post-install) exist for given pac…'
complete -c pkg-add -s M -d 'Force the installation of the package with missing dependencies'
complete -c pkg-add -s q -d 'Force quiet output'

