# pkg-autoremove
# Autogenerated from man page /usr/local/man/man8/pkg-autoremove.8.gz
complete -c pkg-autoremove -s n -d 'Dry-run mode'
complete -c pkg-autoremove -s D -d 'If a deinstallation script exists for a given package, do not execute it'
complete -c pkg-autoremove -s q -d 'Force quiet output'
complete -c pkg-autoremove -s y -d 'Assume yes when asked for confirmation before package autoremoval'

