# pkg-repo
# Autogenerated from man page /usr/local/man/man8/pkg-repo.8.gz
complete -c pkg-repo -s l -d 'Generate list of all files in repo as filesite. txz archive'
complete -c pkg-repo -s m -d 'Use the specified file as repository meta file instead of the default settings'
complete -c pkg-repo -s o -d 'Create the repository in the specified directory instead of the package direc…'
complete -c pkg-repo -s q -d 'Force quiet output.  El FILES See pkg. conf 5'

