# pkg-fetch
# Autogenerated from man page /usr/local/man/man8/pkg-fetch.8.gz
complete -c pkg-fetch -s a -d 'Fetch all packages'
complete -c pkg-fetch -s o -d 'Place files in a sub-directory called All of the specified directory'
complete -c pkg-fetch -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-fetch -s d -d 'Fetch the package and its dependencies as well'
complete -c pkg-fetch -s g -d 'Treat pkg-name as a shell glob pattern'
complete -c pkg-fetch -s i -d 'Make the standard or regular expression ( x ) matching against pkg-name case …'
complete -c pkg-fetch -s q -d 'Quiet mode.  Show less output'
complete -c pkg-fetch -s r -d 'Fetches packages from the given reponame if multiple repo support is enabled'
complete -c pkg-fetch -s u -d 'Fetch all available updates for the currently installed packages'
complete -c pkg-fetch -s U -d 'Suppress the automatic update of the local copy of the repository catalogue f…'
complete -c pkg-fetch -s x -d 'Treat pkg-name as a regular expression according to the "modern" or "extended…'
complete -c pkg-fetch -s y -d 'Assume yes when asked for confirmation before fetching packages'

