# pkg-update
# Autogenerated from man page /usr/local/man/man8/pkg-update.8.gz
complete -c pkg-update -s q -d 'Force quiet output'
complete -c pkg-update -s f -d 'Force a full download of the repository catalogue without regard to the respe…'
complete -c pkg-update -s r -d 'Download the catalogue for the named repository only'

