# pkg-audit
# Autogenerated from man page /usr/local/man/man8/pkg-audit.8.gz
complete -c pkg-audit -s F -d 'Fetch the database before checking'
complete -c pkg-audit -s f -d 'Use filename as the local copy of the vulnerability database'
complete -c pkg-audit -s q -d 'Be quiet'
complete -c pkg-audit -s R -d 'Present the output in one of the following formats: Pp -bullet -compact It js…'
complete -c pkg-audit -s r -d 'Prints packages that depend on vulnerable packages and are thus potentially v…'

