# pkg-register
# Autogenerated from man page /usr/local/man/man8/pkg-register.8.gz
complete -c pkg-register -s A -d 'Mark the package to be automatically removed if no other packages depend on it'
complete -c pkg-register -s d -d 'Enable debugging output'
complete -c pkg-register -s N -d 'Disable registration in the package database, the files will be installed, th…'
complete -c pkg-register -s f -d 'Specifies a pkg-plist style packing list file'
complete -c pkg-register -s i -d 'Specifies the package input path or staging directory'

