# pkg-upgrade
# Autogenerated from man page /usr/local/man/man8/pkg-upgrade.8.gz
complete -c pkg-upgrade -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-upgrade -s F -d 'Do not perform installation of packages, merely fetch packages that should be…'
complete -c pkg-upgrade -s f -d 'Force the reinstallation or upgrade of the whole set of packages'
complete -c pkg-upgrade -s g -d 'Treat the package names as shell glob patterns'
complete -c pkg-upgrade -s I -d 'If any installation scripts (pre-install or post-install) or deinstallation s…'
complete -c pkg-upgrade -s i -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-upgrade -s n -d 'Dry-run mode: show what packages have updates available, but do not perform a…'
complete -c pkg-upgrade -s q -d 'Force quiet output, except when n is used, where a summary of the work list i…'
complete -c pkg-upgrade -s r -d 'Install packages from only the named repository, irrespective of the configur…'
complete -c pkg-upgrade -s U -d 'Suppress the automatic update of the local copy of the repository catalogue f…'
complete -c pkg-upgrade -s v -d 'Upgrade packages which are known to be vulnerable'
complete -c pkg-upgrade -s x -d 'Treat the package names as regular expressions according to the "modern" or "…'
complete -c pkg-upgrade -s y -d 'Assume yes when asked for confirmation before package installation'

