# pkg-unlock
# Autogenerated from man page /usr/local/man/man8/pkg-unlock.8.gz
complete -c pkg-unlock -s a -d 'Lock or unlock all installed packages'
complete -c pkg-unlock -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-unlock -s g -d 'Treat pkg-name as a shell glob pattern'
complete -c pkg-unlock -s i -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-unlock -s l -d 'Show a list of all locked packages'
complete -c pkg-unlock -s q -d 'Operate quietly: do not output anything other than confirmatory questions'
complete -c pkg-unlock -s x -d 'Treat pkg-name as a regular expression according to the "modern" or "extended…'
complete -c pkg-unlock -s y -d 'Assume "yes" as the answer to all questions'
complete -c pkg-unlock -l has-locked-packages -d 'Return 0 if at least one package is locked, 1 otherwise El ENVIRONMENT The fo…'

