# pkg-updating
# Autogenerated from man page /usr/local/man/man8/pkg-updating.8.gz
complete -c pkg-updating -s i -d 'Matching against pkg-name case insensitive'
complete -c pkg-updating -s d -d 'Only entries newer than date are shown.  Use a YYYYMMDD date format'
complete -c pkg-updating -s f -d 'Defines a alternative location of the UPDATING file'

