# pkg-set
# Autogenerated from man page /usr/local/man/man8/pkg-set.8.gz
complete -c pkg-set -s A -d 'Set automatic flag for the package: 0 is not automatic, 1 is automatic'
complete -c pkg-set -s a -d 'Match all installed packages'
complete -c pkg-set -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-set -s g -d 'Match pkg-name as a globbing expression'
complete -c pkg-set -s i -d 'Make the standard or regular expression ( x ) matching against pkg-name case …'
complete -c pkg-set -s n -d 'Change the package name of a given dependency from oldname to newname'
complete -c pkg-set -s o -d 'Change the port origin of a given dependency from oldorigin to neworigin'
complete -c pkg-set -s x -d 'Match pkg-name as a regular expression according to the "modern" or "extended…'
complete -c pkg-set -s v -d 'Set or unset the vital flag on the target package(s)'
complete -c pkg-set -s y -d 'Assume yes rather than asking for confirmation before modifying package infor…'

