# pkg-remove
# Autogenerated from man page /usr/local/man/man8/pkg-remove.8.gz
complete -c pkg-remove -s a -d 'Deletes all installed packages except for pkg 8 from the system and cleans th…'
complete -c pkg-remove -s C -d 'Make the standard or regular expression ( x ) matching against pkg-name case …'
complete -c pkg-remove -s D -d 'If a deinstallation script exists for a given package, do not execute it'
complete -c pkg-remove -s f -d 'Forces packages to be removed despite leaving unresolved dependencies'
complete -c pkg-remove -s g -d 'Treat the package names as shell glob patterns'
complete -c pkg-remove -s i -d 'Make the standard or regular expression ( x ) matching against pkg-name case …'
complete -c pkg-remove -s n -d 'Dry run mode'
complete -c pkg-remove -s q -d 'Force quiet output, except where n is also used, when pkg-remove will show th…'
complete -c pkg-remove -s R -d 'Delete all packages that require the listed packages as well'
complete -c pkg-remove -s x -d 'Treat the package names as regular expressions according to the "modern" or "…'
complete -c pkg-remove -s y -d 'Assume yes when asked for confirmation before package deletion'

