# pkg-clean
# Autogenerated from man page /usr/local/man/man8/pkg-clean.8.gz
complete -c pkg-clean -s a -d 'Delete all cached packages including those, which have not been superseded by…'
complete -c pkg-clean -s n -d 'Do not delete any package files from the cache, but show what would be done i…'
complete -c pkg-clean -s q -d 'Be quiet.  Suppress most output.  All output is suppressed if y is also used'
complete -c pkg-clean -s y -d 'Assume a yes answer instead of asking for confirmation before deleting any ou…'

