# pkg-annotate
# Autogenerated from man page /usr/local/man/man8/pkg-annotate.8.gz
complete -c pkg-annotate -s a -d 'Annotate all installed packages'
complete -c pkg-annotate -s A -d 'The operation is to add a new annotation'
complete -c pkg-annotate -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-annotate -s D -d 'The operation is to delete an annotation.  Only the tag needs to be specified'
complete -c pkg-annotate -s g -d 'Treat pkg-name as a shell glob pattern'
complete -c pkg-annotate -s i -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-annotate -s M -d 'The operation is to modify a previously existing annotation'
complete -c pkg-annotate -s q -d 'Operate quietly: do not output anything other than confirmatory questions'
complete -c pkg-annotate -s S -d 'Display the annotation identified by tag for each matched package'
complete -c pkg-annotate -s x -d 'Treat pkg-name as a regular expression according to the "modern" or "extended…'
complete -c pkg-annotate -s y -d 'Assume "yes" as the answer to all questions'

