# pkg-alias
# Autogenerated from man page /usr/local/man/man8/pkg-alias.8.gz
complete -c pkg-alias -s l -d 'Print all aliases, one alias per line, without their pkg 8 arguments'
complete -c pkg-alias -s q -d 'Force quiet output (suppress column headers).  El FILES pkg'

