# pkg-query
# Autogenerated from man page /usr/local/man/man8/pkg-query.8.gz
complete -c pkg-query -s a -d 'Match all packages from the database'
complete -c pkg-query -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name i…'
complete -c pkg-query -s e -d 'Match packages using the given evaluation-condition'
complete -c pkg-query -s F -d 'Display information only for the package file pkg-name'
complete -c pkg-query -s i -d 'Make the standard or regular expression ( x ) matching against pkg-name in pa…'
complete -c pkg-query -s g -d 'Treat pattern Ac as a glob pattern'
complete -c pkg-query -s x -d 'Treat pattern Ac as a regular expression according to the "modern" or "extend…'

