# pkg-shlib
# Autogenerated from man page /usr/local/man/man8/pkg-shlib.8.gz
complete -c pkg-shlib -s P -d 'Show only the installed packages which provide the named library'
complete -c pkg-shlib -s R -d 'Show only the installed packages which require library'
complete -c pkg-shlib -s q -d 'Force quiet output'

