# pkg-static
# Autogenerated from man page /usr/local/man/man8/pkg-static.8.gz
complete -c pkg-static -s v -d 'Display the current version of pkg-static'
complete -c pkg-static -s d -d 'Show debug information'
complete -c pkg-static -s l -d 'List all the available command names, and exit without performing any other a…'
complete -c pkg-static -s o -d 'Set configuration option for pkg-static from the command line'
complete -c pkg-static -s N -d 'Activation status check mode'
complete -c pkg-static -s j -d 'pkg-static will execute in the given jail name or id Ac, where name matches j…'
complete -c pkg-static -s c -d 'pkg-static will chroot in the chroot path Ac environment'
complete -c pkg-static -s r -d 'pkg-static will install all packages within the specified root directory Ac'
complete -c pkg-static -s C -d 'pkg-static will use the specified file as a configuration file'
complete -c pkg-static -s R -d 'pkg-static will search the directory for per-repository configuration files'
complete -c pkg-static -s 4 -d 'pkg-static will use IPv4 for fetching repository and packages'
complete -c pkg-static -s 6 -d 'pkg-static will use IPv6 for fetching repository and packages'

