# pkg-install
# Autogenerated from man page /usr/local/man/man8/pkg-install.8.gz
complete -c pkg-install -s A -d 'Mark the installed packages as automatic'
complete -c pkg-install -s C -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-install -s f -d 'Force the reinstallation of the package if already installed'
complete -c pkg-install -s g -d 'Treat the package names as shell glob patterns'
complete -c pkg-install -s I -d 'If any installation scripts (pre-install or post-install) exist for a given p…'
complete -c pkg-install -s i -d 'Make the standard or the regular expression ( x ) matching against pkg-name c…'
complete -c pkg-install -s M -d 'Force the installation of the package with missing dependencies'
complete -c pkg-install -s n -d 'Dry-run mode'
complete -c pkg-install -s F -d 'Do not perform actual installation of packages, merely fetch packages that sh…'
complete -c pkg-install -s q -d 'Force quiet output, except when n is used, where pkg-install will always show…'
complete -c pkg-install -s R -d 'When used with f, reinstalls any packages that require the given package'
complete -c pkg-install -s r -d 'Install packages from only the named repository, irrespective of the configur…'
complete -c pkg-install -s U -d 'Suppress the automatic update of the local copy of the repository catalogue f…'
complete -c pkg-install -s x -d 'Treat the package names as regular expressions according to the "modern" or "…'
complete -c pkg-install -s y -d 'Assume yes when asked for confirmation before package installation'

