# pkg-stats
# Autogenerated from man page /usr/local/man/man8/pkg-stats.8.gz
complete -c pkg-stats -s q -d 'Quiet mode.  Show less output'
complete -c pkg-stats -s l -d 'Display stats only for the local package database'
complete -c pkg-stats -s r -d 'Display stats only for the remote package database(s)'
complete -c pkg-stats -s b -d 'Display disk space usage in bytes only'

