# pkg
# Autogenerated from man page /usr/local/man/man8/pkg.8.gz
complete -c pkg -s v -d 'Display the current version of pkg'
complete -c pkg -s d -d 'Show debug information'
complete -c pkg -s l -d 'List all the available command names, and exit without performing any other a…'
complete -c pkg -s o -d 'Set configuration option for pkg from the command line'
complete -c pkg -s N -d 'Activation status check mode'
complete -c pkg -s j -d 'pkg will execute in the given jail name or id Ac, where name matches jls Ar n…'
complete -c pkg -s c -d 'pkg will chroot in the chroot path Ac environment'
complete -c pkg -s r -d 'pkg will install all packages within the specified root directory Ac'
complete -c pkg -s C -d 'pkg will use the specified file as a configuration file'
complete -c pkg -s R -d 'pkg will search the directory for per-repository configuration files'
complete -c pkg -s 4 -d 'pkg will use IPv4 for fetching repository and packages'
complete -c pkg -s 6 -d 'pkg will use IPv6 for fetching repository and packages'

