# plockstat
# Autogenerated from man page /usr/share/man/man1/plockstat.1.gz
complete -c plockstat -s v -d 'Be verbose'
complete -c plockstat -s A -d 'Print all statistics'
complete -c plockstat -s C -d 'Print commulative statistics (the default)'
complete -c plockstat -s H -d 'Print a histogram'
complete -c plockstat -s V -d 'Print the DTrace script about to be used to stderr'
complete -c plockstat -s n -d 'Set the aggregation count for the data set'
complete -c plockstat -s s -d 'Set the ustack (userland stack) caller depth'
complete -c plockstat -s e -d 'Does nothing at the moment'
complete -c plockstat -s x -d 'Specify DTrace options.  See the dtrace 1 man page for more details'

