# pmcannotate
# Autogenerated from man page /usr/share/man/man8/pmcannotate.8.gz
complete -c pmcannotate -s a -d 'Shows the program profiling inlined in the assembly code only'
complete -c pmcannotate -s h -d 'Prints out information about the usage of the tool'
complete -c pmcannotate -s l -d 'Changes the lower bound (expressed in percentage) for traced functions that w…'
complete -c pmcannotate -s k -d 'Set the pathname of the kernel directory to argument kerneldir'

