# pmccontrol
# Autogenerated from man page /usr/share/man/man8/pmccontrol.8.gz
complete -c pmccontrol -s c -d 'Subsequent enable and disable options affect the CPU denoted by argument cpu'
complete -c pmccontrol -s d -d 'Disable PMC number pmc on the CPU specified by c, preventing it from being us…'
complete -c pmccontrol -s e -d 'Enable PMC number pmc, on the CPU specified by c, allowing it to be used in t…'
complete -c pmccontrol -s l -d 'List available hardware performance counters and their current disposition'
complete -c pmccontrol -s L -d 'List available hardware performance counter classes and their supported event…'
complete -c pmccontrol -s s -d 'Print driver statistics maintained by hwpmc 4'

