# pmcstudy
# Autogenerated from man page /usr/share/man/man8/pmcstudy.8.gz
complete -c pmcstudy -s i -d 'If this option is supplied, instead of running a pmcstat 8 command to collect…'
complete -c pmcstudy -s H -d 'This option will display the complete list of canned formulas that can be run…'
complete -c pmcstudy -s e -d 'Execute the canned test name on the running kernel'
complete -c pmcstudy -s h -d 'If you add this option to the e option the test will not execute but instead …'
complete -c pmcstudy -s T -d 'This option will execute a test of every PMC to validate that they are workin…'
complete -c pmcstudy -s m -d 'This option can restrict the number of one second samples that will be collec…'
complete -c pmcstudy -s v -d 'The verbose option adds debugging output to the command'
complete -c pmcstudy -s E -d 'This option can be used by those that have their own ideas on what formulas t…'
complete -c pmcstudy -s L -d 'This option will list all known PMCs and their abbreviation (%NNN)'
complete -c pmcstudy -s A -d 'Run all canned tests'

