# pnfsdsfile
# Autogenerated from man page /usr/share/man/man8/pnfsdsfile.8.gz
complete -c pnfsdsfile -s q -d 'This option suppresses printing of the DS file\'s location(s)'
complete -c pnfsdsfile -s z -d 'This option specifies that the file handle field of the pnfsd'
complete -c pnfsdsfile -s s -d 'This option can be used with z so that the zeroing out of the file handle is …'
complete -c pnfsdsfile -s c -d 'This option allows a sysadmin to replace the host IP# for the DS in the pnfsd'
complete -c pnfsdsfile -s m -d 'This option adds entrie(s) to the extended attributes with IP address set to 0'
complete -c pnfsdsfile -s r -d 'This option sets the IP address of the extended attribute entry for the dshos…'

