# pnfsdscopymr
# Autogenerated from man page /usr/share/man/man8/pnfsdscopymr.8.gz
complete -c pnfsdscopymr -s r -d 'This option indicates that the data storage file should be created on the DS …'
complete -c pnfsdscopymr -s m -d 'This option indicates that the data storage file is to be migrated from the s…'

