# posixshmcontrol
# Autogenerated from man page /usr/share/man/man1/posixshmcontrol.1.gz
complete -c posixshmcontrol -s h -d 'If specified, requests human-readable display of size, see humanize_number 3'
complete -c posixshmcontrol -s n -d 'Prevent translation of owner and group into symbolic names using name-switch …'

