# powerd
# Autogenerated from man page /usr/share/man/man8/powerd.8.gz
complete -c powerd -s a -d 'Selects the mode to use while on AC power'
complete -c powerd -s b -d 'Selects the mode to use while on battery power'
complete -c powerd -s i -d 'Specifies the CPU load percent level when adaptive mode should begin to degra…'
complete -c powerd -s M -d 'Specifies the maximum frequency to throttle up to'
complete -c powerd -s m -d 'Specifies the minimum frequency to throttle down to'
complete -c powerd -s N -d 'Treat "nice" time as idle for the purpose of load calculation; i. e'
complete -c powerd -s n -d 'Selects the mode to use normally when the AC line state is unknown'
complete -c powerd -s P -d 'Specifies an alternative file in which the process ID should be stored'
complete -c powerd -s p -d 'Specifies a different polling interval (in milliseconds) for AC line state an…'
complete -c powerd -s r -d 'Specifies the CPU load percent level where adaptive mode should consider the …'
complete -c powerd -s s -d 'Enforces method for AC line state refresh; by default, it is chosen automatic…'
complete -c powerd -s v -d 'Verbose mode'

