# poweroff
# Autogenerated from man page /usr/share/man/man8/poweroff.8.gz
complete -c poweroff -s c -d 'The system is power cycled (power turned off and then back on) at the specifi…'
complete -c poweroff -s h -d 'The system is halted at the specified time'
complete -c poweroff -s p -d 'The system is halted and the power is turned off (hardware support required, …'
complete -c poweroff -s r -d 'The system is rebooted at the specified time'
complete -c poweroff -s k -d 'Kick everybody off'
complete -c poweroff -s o -d 'If one of the c, h, p or r options are specified, poweroff will execute halt …'
complete -c poweroff -s n -d 'If the o option is specified, prevent the file system cache from being flushe…'

