# ppp
# Autogenerated from man page /usr/share/man/man8/ppp.8.gz
complete -c ppp -o auto -d 'ppp opens the tun interface, configures it then goes into the background'
complete -c ppp -o background -d 'Here, ppp attempts to establish a connection with the peer immediately'
complete -c ppp -o foreground -d 'In foreground mode, ppp attempts to establish a connection with the peer imme…'
complete -c ppp -o direct -d 'This is used for communicating over an already established connection, usuall…'
complete -c ppp -o dedicated -d 'This option is designed for machines connected with a dedicated wire'
complete -c ppp -o ddial -d 'This mode is equivalent to auto mode except that ppp will bring the link back…'
complete -c ppp -o interactive -d 'This is a no-op, and gives the same behaviour as if none of the above modes h…'

