# pppctl
# Autogenerated from man page /usr/share/man/man8/pppctl.8.gz
complete -c pppctl -s v -d 'Display all data sent to and received from the pppctl ppp daemon'
complete -c pppctl -s t -d 'Use a timeout of n instead of the default 2 seconds when connecting'
complete -c pppctl -s p -d 'Specify the password required by the pppctl ppp daemon'

