# praliases
# Autogenerated from man page /usr/share/man/man8/praliases.8.gz
complete -c praliases -s C -d 'Read the specified sendmail configuration file instead of the default  sendma…'
complete -c praliases -s f -d 'Read the specified file instead of the configured sendmail system aliases fil…'

