# praudit
# Autogenerated from man page /usr/share/man/man1/praudit.1.gz
complete -c praudit -s d -d 'Specifies the delimiter.  The default delimiter is the comma'
complete -c praudit -s l -d 'Prints the entire record on the same line'
complete -c praudit -s n -d 'Do not convert user and group IDs to their names but leave in their numeric f…'
complete -c praudit -s p -d 'Specify this option if input to praudit is piped from the tail 1 utility'
complete -c praudit -s r -d 'Prints the records in their raw, numeric form'
complete -c praudit -s s -d 'Prints the tokens in their short form'
complete -c praudit -s x -d 'Print audit records in the XML output format'

