# prometheus_sysctl_exporter
# Autogenerated from man page /usr/share/man/man8/prometheus_sysctl_exporter.8.gz
complete -c prometheus_sysctl_exporter -s d -d 'Print descriptions of metrics when available'
complete -c prometheus_sysctl_exporter -s e -d 'Same as i, except exclude metrics that match pattern'
complete -c prometheus_sysctl_exporter -s g -d 'Gzip compresses the HTTP response body'
complete -c prometheus_sysctl_exporter -s h -d 'Precede the output with a HTTP response header'
complete -c prometheus_sysctl_exporter -s i -d 'If specified, include metrics that match pattern'

