# protect
# Autogenerated from man page /usr/share/man/man1/protect.1.gz
complete -c protect -s c -d 'Remove protection from the specified processes'
complete -c protect -s d -d 'Apply the operation to all current children of the specified processes'
complete -c protect -s i -d 'Apply the operation to all future children of the specified processes'
complete -c protect -s g -d 'Apply the operation to all processes in the specified process group'
complete -c protect -s p -d 'Apply the operation to the specified process'

