# pstat
# Autogenerated from man page /usr/share/man/man8/pstat.8.gz
complete -c pstat -s n -d 'Print devices out by major/minor instead of name'
complete -c pstat -s h -d 'Human-readable output'
complete -c pstat -s k -d 'Print sizes in kilobytes, regardless of the setting of the BLOCKSIZE environm…'
complete -c pstat -s m -d 'Print sizes in megabytes, regardless of the setting of the BLOCKSIZE environm…'
complete -c pstat -s g -d 'Print sizes in gigabytes, regardless of the setting of the BLOCKSIZE environm…'
complete -c pstat -s T -d 'Print the number of used and free slots in several system tables'
complete -c pstat -s f -d 'Print the open file table with these headings: -tag -width indent LOC The cor…'
complete -c pstat -s s -d 'Print information about swap space usage on all the swap areas compiled into …'
complete -c pstat -s t -d 'Print table for terminals with these headings: -tag -width indent LINE Device…'
complete -c pstat -s M -d 'Extract values associated with the name list from the specified core'
complete -c pstat -s N -d 'If M is also specified, extract the name list from the specified system inste…'

