# pwd_mkdb
# Autogenerated from man page /usr/share/man/man8/pwd_mkdb.8.gz
complete -c pwd_mkdb -s C -d 'Check if the password file is in the correct format'
complete -c pwd_mkdb -s d -d 'Store databases into specified destination directory instead of /etc'
complete -c pwd_mkdb -s i -d 'Ignore locking failure of the master. passwd file'
complete -c pwd_mkdb -s N -d 'Tell pwd_mkdb to exit with an error if it cannot obtain a lock on the file'
complete -c pwd_mkdb -s p -d 'Create a Version 7 style password file and install it into /etc/passwd'
complete -c pwd_mkdb -s s -d 'Specify in megabytes the size of the memory cache used by the hashing library'
complete -c pwd_mkdb -s u -d 'Only update the record for the specified user'

