# pwm
# Autogenerated from man page /usr/share/man/man8/pwm.8.gz
complete -c pwm -s f -d 'Device to operate on.  If not specified, /dev/pwm/pwmc0. 0 is used'
complete -c pwm -s C -d 'Show the configuration of the PWM channel'
complete -c pwm -s D -d 'Disable the PWM channel'
complete -c pwm -s d -d 'Configure the duty cycle (in nanoseconds or percentage) of the PWM channel'
complete -c pwm -s E -d 'Enable the PWM channel'
complete -c pwm -s p -d 'Configure the period (in nanoseconds) of the PWM channel'
complete -c pwm -s I -d 'Invert PWM signal polarity El EXAMPLES -bullet It Show the configuration of t…'

