# quot
# Autogenerated from man page /usr/share/man/man8/quot.8.gz
complete -c quot -s a -d 'Include statistics for all mounted file systems'
complete -c quot -s c -d 'Display three columns containing number of blocks per file, number of files i…'
complete -c quot -s f -d 'For each user, display count of files and space occupied'
complete -c quot -s h -d 'Estimate the number of blocks in each file based on its size'
complete -c quot -s k -d 'Force the numbers to be reported in kilobyte counts'
complete -c quot -s n -d 'Given a list of inodes (plus some optional data on each line) in the standard…'
complete -c quot -s v -d 'In addition to the default output, display the number of files not accessed w…'

