# quotacheck
# Autogenerated from man page /usr/share/man/man8/quotacheck.8.gz
complete -c quotacheck -s a -d 'If supplied in place of any file system names, quotacheck will check all the …'
complete -c quotacheck -s c -d 'Before performing its checks, quotacheck will convert the quota file to the s…'
complete -c quotacheck -s g -d 'Only group quotas listed in /etc/fstab are to be checked'
complete -c quotacheck -s l -d 'Specifies the maximum number of concurrent file systems to check in parallel'
complete -c quotacheck -s u -d 'Only user quotas listed in /etc/fstab are to be checked'
complete -c quotacheck -s v -d 'Report discrepancies between the calculated and recorded disk quotas and othe…'

