# quota
# Autogenerated from man page /usr/share/man/man1/quota.1.gz
complete -c quota -s f -d 'Only display quota information for the file system that contains the specifie…'
complete -c quota -s g -d 'Print group quotas for the group of which the user is a member'
complete -c quota -s h -d '"Human-readable" output'
complete -c quota -s l -d 'Do not report quotas on NFS file systems'
complete -c quota -s q -d 'Print a more terse message, containing only information on file systems where…'
complete -c quota -s r -d 'Display the raw quota information as it appears in the quota structure'
complete -c quota -s u -d 'Print the user quotas.  This is the default unless g is specified'
complete -c quota -s v -d 'Display quotas on file systems where no storage is allocated'

