# quotaoff
# Autogenerated from man page /usr/share/man/man8/quotaoff.8.gz
complete -c quotaoff -s a -d 'If supplied in place of any file system names, quotaoff Ns / Ns Nm quotaoff w…'
complete -c quotaoff -s g -d 'Only group quotas listed in /etc/fstab should be enabled/disabled'
complete -c quotaoff -s u -d 'Only user quotas listed in /etc/fstab should be enabled/disabled'
complete -c quotaoff -s v -d 'Cause quotaoff and quotaoff quotaoff to print a message for each file system …'

