# random
# Autogenerated from man page /usr/share/man/man6/random.6.gz
complete -c random -s e -d 'If the e option is specified, random does not read or write anything, and sim…'
complete -c random -s f -d 'The f option is used to specify the filename to read from'
complete -c random -s l -d 'Randomize the input via newlines (the default)'
complete -c random -s r -d 'Do not buffer output'
complete -c random -s U -d 'Reuse any given line or word when creating a randomized output'
complete -c random -s u -d 'Do not select the same line or word from a file more than once (the default)'
complete -c random -s w -d 'Randomize words separated by isspace 3 instead of newlines'

