# rarpd
# Autogenerated from man page /usr/share/man/man8/rarpd.8.gz
complete -c rarpd -s a -d 'Listen on all the Ethernets attached to the system'
complete -c rarpd -s d -d 'If f is also specified, rarpd logs messages to stdout and stderr instead of v…'
complete -c rarpd -s f -d 'Run in the foreground'
complete -c rarpd -s P -d 'Specify the pathname of the PID file.  If not specified, /var/run/rarpd'
complete -c rarpd -s s -d 'Supply a response to any RARP request for which an ethernet to IP address map…'
complete -c rarpd -s t -d 'Supply an alternate tftp root directory to /tftpboot, similar to the s option…'
complete -c rarpd -s v -d 'Enable verbose syslogging'

