# rcorder
# Autogenerated from man page /usr/share/man/man8/rcorder.8.gz
complete -c rcorder -s g -d 'Produce a GraphViz ('
complete -c rcorder -s k -d 'Add the specified keyword to the "keep list"'
complete -c rcorder -s p -d 'Generate ordering suitable for parallel startup, placing files that can be ex…'
complete -c rcorder -s s -d 'Add the specified keyword to the "skip list"'

