# rctl
# Autogenerated from man page /usr/share/man/man8/rctl.8.gz
complete -c rctl -s a -d 'Add rule to the RCTL database'
complete -c rctl -s l -d 'Display rules applicable to the process defined by filter'
complete -c rctl -s r -d 'Remove rules matching filter from the RCTL database'
complete -c rctl -s u -d 'Display resource utilization for a subject Po process, user, loginclass or ja…'
complete -c rctl -s h -d '"Human-readable" output'
complete -c rctl -s n -d 'Display user IDs numerically rather than converting them to a user name'

