# rdump
# Autogenerated from man page /usr/share/man/man8/rdump.8.gz
complete -c rdump -o 0-9 -d 'Dump levels'
complete -c rdump -s a -d auto-size
complete -c rdump -s B -d 'The number of kilobytes per output volume, except that if it is not an intege…'
complete -c rdump -s b -d 'The number of kilobytes per output block.  The default block size is 10'
complete -c rdump -s C -d 'Specify the cache size in megabytes'
complete -c rdump -s c -d 'Change the defaults for use with a cartridge tape drive, with a density of 80…'
complete -c rdump -s D -d 'Specify an alternate path to the dumpdates file'
complete -c rdump -s d -d 'Set tape density to density.  The default is 1600BPI'
complete -c rdump -s f -d 'Write the backup to file ; file may be a special device file like /dev/sa0 (a…'
complete -c rdump -s P -d 'Use popen 3 to execute the sh 1 script string defined by pipecommand for the …'
complete -c rdump -s h -d 'Honor the user nodump flag UF_NODUMP only for dumps at or above the given lev…'
complete -c rdump -s L -d 'This option is to notify rdump that it is dumping a live file system'
complete -c rdump -s n -d 'Whenever rdump requires operator attention, notify all operators in the group…'
complete -c rdump -s r -d 'Be rsync-friendly'
complete -c rdump -s R -d 'Be even more rsync-friendly'
complete -c rdump -s S -d 'Display an estimate of the backup size and the number of tapes required, and …'
complete -c rdump -s s -d 'Attempt to calculate the amount of tape needed at a particular density'
complete -c rdump -s T -d 'Use the specified date as the starting time for the dump instead of the time …'
complete -c rdump -s u -d 'Update the dumpdates file after a successful dump'
complete -c rdump -s W -d 'Tell the operator what file systems need to be dumped'
complete -c rdump -s w -d 'Is like W, but prints only those file systems which need to be dumped'

