# red
# Autogenerated from man page /usr/share/man/man1/red.1.gz
complete -c red -s s -d 'Suppress diagnostics'
complete -c red -s p -d 'Specify a command prompt.  This may be toggled on and off with the P command'

