# ree
# Autogenerated from man page /usr/share/man/man1/ree.1.gz
complete -c ree -s i -d 'Turns off display of information window at top of terminal'
complete -c ree -s h -d 'Turns off highlighting of borders of windows and menus (improves performance …'
complete -c ree -s e -d 'Turns off expansion of tab character to spaces'

