# renice
# Autogenerated from man page /usr/share/man/man8/renice.8.gz
complete -c renice -s n -d 'Instead of changing the specified processes to the given priority, interpret …'
complete -c renice -s g -d 'Interpret target parameters as process group ID\'s'
complete -c renice -s p -d 'Interpret target parameters as process ID\'s (the default)'
complete -c renice -s u -d 'Interpret target parameters as user names or user ID\'s'

