# resolvconf
# Autogenerated from man page /usr/share/man/man8/resolvconf.8.gz
complete -c resolvconf -s f -d 'Ignore non existent interfaces.  Only really useful for deleting interfaces'
complete -c resolvconf -s m -d 'Set the metric of the interface when adding it, default of 0'
complete -c resolvconf -s p -d 'Marks the interface resolv. conf as private'
complete -c resolvconf -s x -d 'Mark the interface resolv'
complete -c resolvconf -s i -d 'List the interfaces and protocols, optionally matching pattern, we have resolv'
complete -c resolvconf -s l -d 'List the resolv. conf files we have'
complete -c resolvconf -s u -d 'Force resolvconf to update all its subscribers'
complete -c resolvconf -l version -d 'Echo the resolvconf version to stdout'
complete -c resolvconf -s I -d 'Initialise the state directory /var/run/resolvconf'
complete -c resolvconf -s R -d 'Echo the command used to restart a service'
complete -c resolvconf -s r -d 'If the service is running then restart it'
complete -c resolvconf -s v -d 'Echo variables DOMAINS, SEARCH and NAMESERVERS so that the subscriber can con…'
complete -c resolvconf -s V -d 'Same as v except that only the information configured in resolvconf'

