# rfcomm_sppd
# Autogenerated from man page /usr/share/man/man1/rfcomm_sppd.1.gz
complete -c rfcomm_sppd -s a -d 'In client mode, this required option specifies the address of the remote RFCO…'
complete -c rfcomm_sppd -s b -d 'Detach from the controlling terminal, i. e. , run in background'
complete -c rfcomm_sppd -s c -d 'In both client and server mode, this option specifies the RFCOMM channel to c…'
complete -c rfcomm_sppd -s h -d 'Display usage message and exit'
complete -c rfcomm_sppd -s S -d 'Server mode; see DESCRIPTION'
complete -c rfcomm_sppd -s t -d 'Use slave pseudo tty.  If not set stdin/stdout will be used'

