# rfcomm_pppd
# Autogenerated from man page /usr/share/man/man8/rfcomm_pppd.8.gz
complete -c rfcomm_pppd -s a -d 'In client mode, this required option specifies the address of the remote RFCO…'
complete -c rfcomm_pppd -s C -d 'In both client and server mode, this required option specifies the RFCOMM cha…'
complete -c rfcomm_pppd -s c -d 'Act as an RFCOMM client.  This is the default mode'
complete -c rfcomm_pppd -s d -d 'Do not detach from the controlling terminal, i. e. , run in foreground'
complete -c rfcomm_pppd -s D -d 'In server mode, register the DUN (Dial-Up Networking) service in addition to …'
complete -c rfcomm_pppd -s h -d 'Display usage message and exit'
complete -c rfcomm_pppd -s l -d 'In both client and server mode, this required option specifies which ppp 8 la…'
complete -c rfcomm_pppd -s S -d 'In server mode, register the SP (Serial Port) service in addition to the LAN …'
complete -c rfcomm_pppd -s s -d 'Act as an RFCOMM server'
complete -c rfcomm_pppd -s u -d 'This option maps directly to the unit ppp 8 command-line option and tells rfc…'

