# rmail
# Autogenerated from man page /usr/share/man/man8/rmail.8.gz
complete -c rmail -s D -d 'Use the specified  domain instead of the default domain of ``UUCP\'\''
complete -c rmail -s T -d 'Turn on debugging.  SEE ALSO uucp(1), mail'

