# rmuser
# Autogenerated from man page /usr/share/man/man8/rmuser.8.gz
complete -c rmuser -s f -d 'The rmuser utility will get a list of users to be removed from file, which wi…'
complete -c rmuser -s y -d 'Implicitly answer yes to any and all prompts'
complete -c rmuser -s v -d 'Enable verbose mode'

