# route
# Autogenerated from man page /usr/share/man/man8/route.8.gz
complete -c route -s 4 -d 'Specify inet address family as family hint for subcommands'
complete -c route -s 6 -d 'Specify inet6 address family as family hint for subcommands'
complete -c route -s d -d 'Run in debug-only mode, i. e. , do not actually modify the routing table'
complete -c route -s n -d 'Bypass attempts to print host and network names symbolically when reporting a…'
complete -c route -s t -d 'Run in test-only mode.  /dev/null is used instead of a socket'
complete -c route -s v -d '(verbose) Print additional details'
complete -c route -s q -d 'Suppress all output from the add , change , delete, and flush commands'
complete -c route -s j -d 'Run inside a jail'

