# routed
# Autogenerated from man page /usr/share/man/man8/routed.8.gz
complete -c routed -s i -d 'allow routed to accept a RIP request from non-router node'
complete -c routed -s s -d 'force routed to supply routing information'
complete -c routed -s q -d 'is the opposite of the s option'
complete -c routed -s d -d 'do not run in the background.  This option is meant for interactive use'
complete -c routed -s g -d 'used on internetwork routers to offer a route to the "default" destination'
complete -c routed -s h -d 'cause host or point-to-point routes to not be advertised, provided there is a…'
complete -c routed -s m -d 'cause the machine to advertise a host or point-to-point route to its primary …'
complete -c routed -s A -d 'do not ignore RIPv2 authentication if we do not care about RIPv2 authenticati…'
complete -c routed -s t -d 'increase the debugging level, which causes more information to be logged on t…'
complete -c routed -s T -d 'increases the debugging level to at least 1 and causes debugging information …'
complete -c routed -s v -d 'display and logs the version of daemon'
complete -c routed -s F -d 'minimize routes in transmissions via interfaces with addresses that match net…'
complete -c routed -s P -d 'is equivalent to adding the parameter line parms to the /etc/gateways file'

