# rpc.statd
# Autogenerated from man page /usr/share/man/man8/rpc.statd.8.gz
complete -c 'rpc.statd' -s d -d 'Cause debugging information to be written to syslog, recording all RPC transa…'
complete -c 'rpc.statd' -s F -d 'Run rpc. statd in the foreground, rather than going into daemon mode'
complete -c 'rpc.statd' -s h -d 'Specify specific IP addresses to bind to'
complete -c 'rpc.statd' -s p -d 'The p option allow to force the daemon to bind to the specified port, for bot…'

