# rpc.tlsclntd
# Autogenerated from man page /usr/share/man/man8/rpc.tlsclntd.8.gz
complete -c 'rpc.tlsclntd' -s 2 -d 'Specify the use of TLS version 1. 2'
complete -c 'rpc.tlsclntd' -s C -d 'Specify which ciphers are available during TLS handshake'
complete -c 'rpc.tlsclntd' -s D -d 'Use certdir instead of /etc/rpc. tlsclntd for the m option'
complete -c 'rpc.tlsclntd' -s d -d 'Run in debug mode.  In this mode, rpc. tlsclntd will not fork when it starts'
complete -c 'rpc.tlsclntd' -s l -d 'This specifies the path name of a CAfile which holds the information for serv…'
complete -c 'rpc.tlsclntd' -s m -d 'Enable support for mutual authentication'
complete -c 'rpc.tlsclntd' -s p -d 'This option is similar to the l option, but specifies the path of a directory…'
complete -c 'rpc.tlsclntd' -s r -d 'This option specifies a Certificate Revocation List (CRL) file that is to be …'
complete -c 'rpc.tlsclntd' -s v -d 'Run in verbose mode.  In this mode, rpc'

