# rpc.lockd
# Autogenerated from man page /usr/share/man/man8/rpc.lockd.8.gz
complete -c 'rpc.lockd' -s d -d 'The d option causes debugging information to be written to syslog, recording …'
complete -c 'rpc.lockd' -s F -d 'Run rpc. lockd in the foreground, rather than going into daemon mode'
complete -c 'rpc.lockd' -s g -d 'The g option allow to specify the grace period, in seconds'
complete -c 'rpc.lockd' -s h -d 'Specify specific IP addresses to bind to'
complete -c 'rpc.lockd' -s p -d 'The p option allow to force the daemon to bind to the specified port, for bot…'

