# rpc.umntall
# Autogenerated from man page /usr/share/man/man8/rpc.umntall.8.gz
complete -c 'rpc.umntall' -s e -d 'All entries which are not actually mounted or older than expire (seconds) are…'
complete -c 'rpc.umntall' -s h -d 'Only remove the specific hostname.  Send a UMNTALL RPC to the NFS server'
complete -c 'rpc.umntall' -s k -d 'Keep entries for existing NFS file systems'
complete -c 'rpc.umntall' -s p -d 'Only remove the specific mount-path.  Send a UMOUNT RPC to the NFS server'
complete -c 'rpc.umntall' -s v -d 'Verbose, additional information is printed for each processed mounttab entry'

