# rpc.tlsservd
# Autogenerated from man page /usr/share/man/man8/rpc.tlsservd.8.gz
complete -c 'rpc.tlsservd' -s 2 -d 'Permit clients to mount using TLS version 1. 2'
complete -c 'rpc.tlsservd' -s C -d 'Specify which ciphers are available during TLS handshake'
complete -c 'rpc.tlsservd' -s D -d 'Use certdir instead of /etc/rpc'
complete -c 'rpc.tlsservd' -s d -d 'Run in debug mode.  In this mode, rpc. tlsservd will not fork when it starts'
complete -c 'rpc.tlsservd' -s h -d 'This option specifies that the client must provide a certificate that both ve…'
complete -c 'rpc.tlsservd' -s l -d 'This option specifies the path name of a CA certificate(s) file in pem format…'
complete -c 'rpc.tlsservd' -s m -d 'This option specifies that the server is to request a certificate from the cl…'
complete -c 'rpc.tlsservd' -s N -d 'For a server with a large number of NFS-over-TLS client mounts, this daemon m…'
complete -c 'rpc.tlsservd' -s n -d 'This option specifies what the domain is for use with the u option, overridin…'
complete -c 'rpc.tlsservd' -s p -d 'This option is similar to the l option, but specifies the path of a directory…'
complete -c 'rpc.tlsservd' -s r -d 'This option specifies a Certificate Revocation List (CRL) file that is to be …'
complete -c 'rpc.tlsservd' -s u -d 'This option specifies that if the client provides a certificate that both ver…'
complete -c 'rpc.tlsservd' -s v -d 'Run in verbose mode.  In this mode, rpc'
complete -c 'rpc.tlsservd' -s W -d 'This option is used with the h option to allow use of a wildcard * that match…'
complete -c 'rpc.tlsservd' -s w -d 'Similar to W but allows the wildcard * to match a single component of the rev…'

