# rpc.yppasswdd
# Autogenerated from man page /usr/share/man/man8/rpc.yppasswdd.8.gz
complete -c 'rpc.yppasswdd' -s t -d 'By default, rpc'
complete -c 'rpc.yppasswdd' -s d -d 'The rpc'
complete -c 'rpc.yppasswdd' -s p -d 'This option can be used to override the default path to the location of the N…'
complete -c 'rpc.yppasswdd' -s s -d 'Disallow changing of shell information'
complete -c 'rpc.yppasswdd' -s f -d 'Disallow changing of full name (\'GECOS\') information'
complete -c 'rpc.yppasswdd' -s a -d 'Allow additions to be made to the NIS passwd databases'
complete -c 'rpc.yppasswdd' -s m -d 'Turn on multi-domain mode'
complete -c 'rpc.yppasswdd' -s i -d 'If rpc'
complete -c 'rpc.yppasswdd' -s v -d 'Turn on verbose logging mode'
complete -c 'rpc.yppasswdd' -s u -d 'Many commercial yppasswd 1 clients do not use a reserved port when sending re…'
complete -c 'rpc.yppasswdd' -s h -d 'Display the list of flags and options understood by rpc. yppasswdd'

