# rpcbind
# Autogenerated from man page /usr/share/man/man8/rpcbind.8.gz
complete -c rpcbind -s 6 -d 'Bind to AF_INET6 (IPv6) addresses only'
complete -c rpcbind -s a -d 'When debugging d, do an abort on errors'
complete -c rpcbind -s d -d 'Run in debug mode'
complete -c rpcbind -s h -d 'IP addresses to bind to when servicing TCP and UDP requests'
complete -c rpcbind -s i -d 'Insecure mode.  Allow calls to SET and UNSET from any host'
complete -c rpcbind -s L -d 'Allow old-style local connections over the loopback interface'
complete -c rpcbind -s l -d 'Turn on libwrap connection logging'
complete -c rpcbind -s s -d 'Cause rpcbind to change to the user daemon as soon as possible'
complete -c rpcbind -s W -d 'Enable libwrap (TCP wrappers) support'
complete -c rpcbind -s w -d 'Enable the warmstart feature'

