# rpcinfo
# Autogenerated from man page /usr/share/man/man8/rpcinfo.8.gz
complete -c rpcinfo -s T -d 'Specify the transport on which the service is required'
complete -c rpcinfo -s a -d 'Use serv_address as the (universal) address for the service on transport to p…'
complete -c rpcinfo -s b -d 'Make an RPC broadcast to procedure 0 of the specified prognum and versnum and…'
complete -c rpcinfo -s d -d 'Delete registration for the RPC service of the specified prognum and versnum'
complete -c rpcinfo -s l -d 'Display a list of entries with a given prognum and versnum on the specified h…'
complete -c rpcinfo -s m -d 'Display a table of statistics of rpcinfo rpcbind operations on the given host'
complete -c rpcinfo -s n -d 'Use portnum as the port number for the t and u options instead of the port nu…'
complete -c rpcinfo -s p -d 'Probe rpcinfo rpcbind on host using version 2 of the rpcinfo rpcbind protocol…'
complete -c rpcinfo -s s -d 'Display a concise list of all registered RPC programs on host'
complete -c rpcinfo -s t -d 'Make an RPC call to procedure 0 of prognum on the specified host using TCP, a…'
complete -c rpcinfo -s u -d 'Make an RPC call to procedure 0 of prognum on the specified host using UDP, a…'

