# rping
# Autogenerated from man page /usr/share/man/man1/rping.1.gz
complete -c rping -s s -d 'Run as the server'
complete -c rping -s c -d 'Run as the client'
complete -c rping -s a -d 'On the server, specifies the network address to bind the connection to'
complete -c rping -s I -d 'The address to bind to as the source IP address to use'
complete -c rping -s p -d 'Port number for listening server'
complete -c rping -s v -d 'Display ping data'
complete -c rping -s V -d 'Validate ping data'
complete -c rping -s d -d 'Display debug information'
complete -c rping -s C -d 'The number of messages to transfer over each connection.   (default infinite)'
complete -c rping -s S -d 'The size of each message transferred, in bytes.   (default 100)'

