# rrenumd
# Autogenerated from man page /usr/share/man/man8/rrenumd.8.gz
complete -c rrenumd -s d -d 'Debug mode'
complete -c rrenumd -s f -d 'Foreground mode.  Do not become daemon'
complete -c rrenumd -s s -d 'Script mode.  Configuration information is obtained from standard input'
complete -c rrenumd -s c -d 'Specify a configuration file where configuration information is kept'

