# rtquery
# Autogenerated from man page /usr/share/man/man8/rtquery.8.gz
complete -c rtquery -s n -d 'displays only the numeric network and host numbers instead of both numeric an…'
complete -c rtquery -s p -d 'uses the poll command to request full routing information from rtquery gated'
complete -c rtquery -s 1 -d 'queries using RIP version 1 instead of RIP version 2'
complete -c rtquery -s w -d 'changes the delay for an answer from each host'
complete -c rtquery -s r -d 'asks about the route to destination addr'
complete -c rtquery -s a
complete -c rtquery -s t -d 'changes tracing, where op is one of the following'

