# rtsold
# Autogenerated from man page /usr/share/man/man8/rtsold.8.gz
complete -c rtsold -s a -d 'Autoprobe outgoing interfaces'
complete -c rtsold -s d -d 'Enable debugging'
complete -c rtsold -s D -d 'Enable more debugging including the printing of internal timer information'
complete -c rtsold -s f -d 'Prevent rtsold from becoming a daemon (foreground mode)'
complete -c rtsold -s F -d 'Explicitly configure the kernel to accept Router Advertisements and disable I…'
complete -c rtsold -s i -d 'Transmit Router Solicitation packets immediately, without waiting the normal …'
complete -c rtsold -s m -d 'Enable mobility support'
complete -c rtsold -s 1 -d 'Perform only one probe'
complete -c rtsold -s M -d 'Specifies a supplement script file to handle the Managed Configuration flag o…'
complete -c rtsold -s O -d 'Specifies a supplement script file to handle the Other Configuration flag of …'
complete -c rtsold -s A -d 'Specifies a supplement script file to always be called for the router adverti…'
complete -c rtsold -s p -d 'Writes the process ID of rtsold to pidfile instead of the default PID file /v…'
complete -c rtsold -s R -d 'Specifies a script to run when router advertisement options RDNSS Pq Recursiv…'
complete -c rtsold -s u -d 'Specifies whether to add the source address of Router Advertisement messages …'

