# rusers
# Autogenerated from man page /usr/share/man/man1/rusers.1.gz
complete -c rusers -s a -d 'Print all machines responding even if no one is currently logged in'
complete -c rusers -s l -d 'Print a long format listing'

