# savecore
# Autogenerated from man page /usr/share/man/man8/savecore.8.gz
complete -c savecore -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c savecore -s C -d 'Check to see if a dump exists, and display a brief message to indicate the st…'
complete -c savecore -s c -d 'Clear the dump, so that future invocations of savecore will ignore it'
complete -c savecore -s f -d 'Force a dump to be taken even if either the dump was cleared or if the dump h…'
complete -c savecore -s k -d 'Do not clear the dump after saving it'
complete -c savecore -s L -d 'Instruct savecore to generate and save a kernel dump of the running system, r…'
complete -c savecore -s m -d 'Maximum number of dumps to store'
complete -c savecore -s u -d 'Uncompress the dump in case it was compressed by the kernel'
complete -c savecore -s v -d 'Print out some additional debugging information'
complete -c savecore -s Z -d 'Compress the dump (see zstd 1 )'
complete -c savecore -s z -d 'Compress the dump (see gzip 1 )'

