# script
# Autogenerated from man page /usr/share/man/man1/script.1.gz
complete -c script -s a -d 'Append the output to file or typescript, retaining the prior contents'
complete -c script -s d -d 'When playing back a session with the p flag, do not sleep between records whe…'
complete -c script -s e -d 'Accepted for compatibility with util-linux script'
complete -c script -s F -d 'Immediately flush output after each write'
complete -c script -s f -d 'Create file. filemon or typescript. filemon using filemon 4'
complete -c script -s k -d 'Log keys sent to the program as well as output'
complete -c script -s p -d 'Play back a session recorded with the r flag in real time'
complete -c script -s q -d 'Run in quiet mode, omit the start, stop and command status messages'
complete -c script -s r -d 'Record a session with input, output, and timestamping'
complete -c script -s t -d 'Specify the interval at which the script output file will be flushed to disk,…'
complete -c script -s T -d 'Implies p, but just reports the time-stamp of each output'

