# sdpcontrol
# Autogenerated from man page /usr/share/man/man8/sdpcontrol.8.gz
complete -c sdpcontrol -s a -d 'Connect to the remote device with the specified address'
complete -c sdpcontrol -s c -d 'Specify path to the control socket.  The default path is /var/run/sdp'
complete -c sdpcontrol -s h -d 'Display usage message and exit'
complete -c sdpcontrol -s l -d 'Query the local SDP server via the control socket'

