# sdpd
# Autogenerated from man page /usr/share/man/man8/sdpd.8.gz
complete -c sdpd -s d -d 'Do not detach from the controlling terminal'
complete -c sdpd -s c -d 'Specify path to the control socket.  The default path is /var/run/sdp'
complete -c sdpd -s g -d 'Specifies the group the sdpd should run as after it initializes'
complete -c sdpd -s h -d 'Display usage message and exit'
complete -c sdpd -s u -d 'Specifies the user the sdpd should run as after it initializes'

