# sed
# Autogenerated from man page /usr/share/man/man1/sed.1.gz
complete -c sed -s E -d 'Interpret regular expressions as extended (modern) regular expressions rather…'
complete -c sed -s a -d 'The files listed as parameters for the w functions are created (or truncated)…'
complete -c sed -s e -d 'Append the editing commands specified by the command argument to the list of …'
complete -c sed -s f -d 'Append the editing commands found in the file command_file to the list of com…'
complete -c sed -s I -d 'Edit files in-place, saving backups with the specified extension'
complete -c sed -s i -d 'Edit files in-place similarly to I, but treat each file independently from ot…'
complete -c sed -s l -d 'Make output line buffered'
complete -c sed -s n -d 'By default, each line of input is echoed to the standard output after all of …'
complete -c sed -s r -d 'Same as E for compatibility with GNU sed'
complete -c sed -s u -d 'Make output unbuffered'

