# seq
# Autogenerated from man page /usr/share/man/man1/seq.1.gz
complete -c seq -s f -d 'Use a printf 3 style format to print each number'
complete -c seq -s s -d 'Use string to separate numbers'
complete -c seq -s t -d 'Use string to terminate sequence of numbers'
complete -c seq -s w -d 'Equalize the widths of all numbers by padding with zeros as necessary'

