# services_mkdb
# Autogenerated from man page /usr/share/man/man8/services_mkdb.8.gz
complete -c services_mkdb -s b -d 'Use big-endian byte order for database metadata'
complete -c services_mkdb -s l -d 'Use little-endian byte order for database metadata'
complete -c services_mkdb -s o -d 'Put the output databases in the named file'
complete -c services_mkdb -s q -d 'Do not warn about duplicate services'
complete -c services_mkdb -s u -d 'Print the services file to stdout, omitting duplicate entries and comments'

