# service
# Autogenerated from man page /usr/share/man/man8/service.8.gz
complete -c service -s E -d 'Set the environment variable var to the specified value before starting the s…'
complete -c service -s e -d 'List services that are enabled'
complete -c service -s j -d 'Perform the given actions under the named jail'
complete -c service -s l -d 'List all files in /etc/rc. d and the local startup directories'
complete -c service -s R -d 'Restart all enabled local services'
complete -c service -s r -d 'Generate the rcorder 8 as in e above, but list all of the files, not just wha…'
complete -c service -s v -d 'Be slightly more verbose.  El ENVIRONMENT When used to run rc'

