# setfmac
# Autogenerated from man page /usr/share/man/man8/setfmac.8.gz
complete -c setfmac -s R -d 'Set the labels on the file hierarchies rooted in the files instead of just th…'
complete -c setfmac -s h -d 'If the file is a symbolic link, change the label of the link rather than the …'
complete -c setfmac -s q -d 'Do not print non-fatal warnings during execution'

