# setfacl
# Autogenerated from man page /usr/share/man/man1/setfacl.1.gz
complete -c setfacl -s a -d 'Modify the ACL on the specified files by inserting new ACL entries specified …'
complete -c setfacl -s b -d 'Remove all ACL entries except for the ones synthesized from the file mode - t…'
complete -c setfacl -s d -d 'The operations apply to the default ACL entries instead of access ACL entries'
complete -c setfacl -s h -d 'If the target of the operation is a symbolic link, perform the operation on t…'
complete -c setfacl -s H -d 'If the R option is specified, symbolic links on the command line are followed…'
complete -c setfacl -s k -d 'Delete any default ACL entries on the specified files'
complete -c setfacl -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c setfacl -s m -d 'Modify the ACL on the specified file'
complete -c setfacl -s M -d 'Modify the ACL entries on the specified files by adding new ACL entries and m…'
complete -c setfacl -s n -d 'Do not recalculate the permissions associated with the ACL mask entry'
complete -c setfacl -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c setfacl -s R -d 'Perform the action recursively on any specified directories'
complete -c setfacl -s x -d 'If entries is specified, remove the ACL entries specified there from the acce…'
complete -c setfacl -s X -d 'Remove the ACL entries specified in the file file from the access or default …'

