# setfsmac
# Autogenerated from man page /usr/share/man/man8/setfsmac.8.gz
complete -c setfsmac -s e -d 'Treat any file systems encountered which do not support MAC labelling as erro…'
complete -c setfsmac -s f -d 'Apply the specifications in specfile to the specified paths'
complete -c setfsmac -s h -d 'When a symbolic link is encountered, change the label of the link rather than…'
complete -c setfsmac -s q -d 'Do not print non-fatal warnings during execution'
complete -c setfsmac -s s -d 'Apply the specifications in specfile, but assume the specification format is …'
complete -c setfsmac -s v -d 'Increase the degree of verbosity'
complete -c setfsmac -s x -d 'Do not recurse into new file systems when traversing them'

