# setkey
# Autogenerated from man page /usr/share/man/man8/setkey.8.gz
complete -c setkey -s D -d 'Dump the SAD entries.  If with P, the SPD entries are dumped'
complete -c setkey -s F -d 'Flush the SAD entries.  If with P, the SPD entries are flushed'
complete -c setkey -s g -d 'Only SPD entries with global scope are dumped with D and P flags'
complete -c setkey -s t -d 'Only SPD entries with ifnet scope are dumped with D and P flags'
complete -c setkey -s h -d 'Add hexadecimal dump on x mode'
complete -c setkey -s l -d 'Loop forever with short output on D'
complete -c setkey -s v -d 'Be verbose'
complete -c setkey -s x -d 'Loop forever and dump all the messages transmitted to PF_KEY socket'
complete -c setkey -s m -d 'Specify a security protocol mode for use'
complete -c setkey -s r -d 'Specify the bitmap size in octets of the anti-replay window'
complete -c setkey -s u -d 'Specify the identifier of the policy entry in SPD.  See policy'
complete -c setkey -s f -d 'defines the content of the ESP padding'
complete -c setkey -o lh
complete -c setkey -o ls -d 'Specify hard/soft life time duration of the SA'
complete -c setkey -o natt -d 'Manually configure NAT-T for the SA, by specifying initiator oai and requesto…'
complete -c setkey -o natt_mtu -d 'Configure NAT-T fragment size.  El Pp algorithm -tag -width Fl -compact'
complete -c setkey -s E -d 'Specify an encryption or Authenticated Encryption with Associated Data (AEAD)…'
complete -c setkey -s A -d 'Specify an authentication algorithm for AH'
complete -c setkey -s C -d 'Specify a compression algorithm for IPComp'
complete -c setkey -s P

