# showmount
# Autogenerated from man page /usr/share/man/man8/showmount.8.gz
complete -c showmount -s a -d 'List all mount points in the form: -ragged -offset indent -compact host : Ns …'
complete -c showmount -s d -d 'List directory paths of mount points instead of hosts'
complete -c showmount -s E -d 'Show the host Ns \'s exports list in a script-friendly format'
complete -c showmount -s e -d 'Show the host Ns \'s exports list'
complete -c showmount -s 1 -d 'Use mount protocol Version 1, compatible with legacy servers'
complete -c showmount -s 3 -d 'Ignored for backwards compatibility'

