# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8.gz
complete -c shutdown -s c -d 'The system is power cycled (power turned off and then back on) at the specifi…'
complete -c shutdown -s h -d 'The system is halted at the specified time'
complete -c shutdown -s p -d 'The system is halted and the power is turned off (hardware support required, …'
complete -c shutdown -s r -d 'The system is rebooted at the specified time'
complete -c shutdown -s k -d 'Kick everybody off'
complete -c shutdown -s o -d 'If one of the c, h, p or r options are specified, shutdown will execute halt …'
complete -c shutdown -s n -d 'If the o option is specified, prevent the file system cache from being flushe…'

