# size
# Autogenerated from man page /usr/share/man/man1/size.1.gz
complete -c size -l format -d 'Display output using the format specified by argument format'
complete -c size -l help -d 'Display a help message and exit'
complete -c size -l radix -d 'Display numeric values using the radix specified by argument radix'
complete -c size -l totals -d 'Shows cumulative totals of section sizes from all objects'
complete -c size -l version -d 'Display a version identifier and exit'
complete -c size -s A -d 'Equivalent to specifying option -format= Ns Ar sysv'
complete -c size -s B -d 'Equivalent to specifying option -format= Ns Ar berkeley'
complete -c size -s V -d 'Equivalent to specifying option -version'
complete -c size -s d -d 'Equivalent to specifying option -radix= Ns Ar 10'
complete -c size -s h -d 'Equivalent to specifying option -help'
complete -c size -s o -d 'Equivalent to specifying option -radix= Ns Ar 8'
complete -c size -s t -d 'Equivalent to specifying option -totals'
complete -c size -s x -d 'Equivalent to specifying option -radix= Ns Ar 16'

