# slurp
# Autogenerated from man page /usr/local/man/man1/slurp.1.gz
complete -c slurp -s h -d 'Show help message and quit'
complete -c slurp -s d -d 'Display dimensions of selection'
complete -c slurp -s b -d 'Set background color.  See COLORS for more detail'
complete -c slurp -s c -d 'Set border color.  See COLORS for more detail'
complete -c slurp -s s -d 'Set selection color.  See COLORS for more detail'
complete -c slurp -s B -d 'Set color for highlighting predefined rectangles from standard input when not'
complete -c slurp -s F -d 'Set the font family name when displaying the dimensions box.  Only useful'
complete -c slurp -s w -d 'Set border weight'
complete -c slurp -s f -d 'Set format.  See FORMAT for more detail'
complete -c slurp -s p -d 'Select a single pixel instead of a rectangle.  This mode ignores any'
complete -c slurp -s o -d 'Add predefined rectangles for all outputs, as if provided on standard input'
complete -c slurp -s r -d 'Require the user to select one of the predefined rectangles.  These can come'
complete -c slurp -s a -d 'Force selections to have the given aspect ratio.  This constraint is not'

