# smbmsg
# Autogenerated from man page /usr/share/man/man8/smbmsg.8.gz
complete -c smbmsg -s F -d 'Specify the printf 3 format to be used for displaying input data'
complete -c smbmsg -s c -d 'This is the value of the command byte to be issued as part of the SMBus messa…'
complete -c smbmsg -s f -d 'This specifies that dev should be used as the connection to the SMBus, rather…'
complete -c smbmsg -s i -d 'An SMBus message should be generated to read incnt bytes from the device'
complete -c smbmsg -s o -d 'An SMBus message should be generated to write outcnt bytes to the device'
complete -c smbmsg -s p -d 'This selects the probe bus modus of operation'
complete -c smbmsg -s s -d 'The slave parameter specifies which SMBus device to connect to'
complete -c smbmsg -s w -d 'This option specifies that IO operations are word operations, rather than byt…'

