# snapinfo
# Autogenerated from man page /usr/share/man/man8/snapinfo.8.gz
complete -c snapinfo -s a -d 'Search for snapshots on all mounted UFS file systems'
complete -c snapinfo -s v -d 'Verbose mode.  mountpoint Search the file system mounted on this mountpoint'

