# soelim
# Autogenerated from man page /usr/share/man/man1/soelim.1.gz
complete -c soelim -s C -d 'Recognise . so when it is not followed by a space character'
complete -c soelim -s r -d 'Compatibility with groff\'s soelim 1 (does nothing)'
complete -c soelim -s t -d 'Compatibility with groff\'s soelim 1 (does nothing)'
complete -c soelim -s v -d 'Compatibility with groff\'s soelim 1 (does nothing)'
complete -c soelim -s I -d 'This option specifies directories where soelim searches for files (both those…'

