# spi
# Autogenerated from man page /usr/share/man/man8/spi.8.gz
complete -c spi -s A -d 'Specifies ASCII mode'
complete -c spi -s b -d 'Binary output mode.  Only has an effect when A has been specified'
complete -c spi -s C -d 'Sends one or more command bytes, skipping any bytes read-in during the transf…'
complete -c spi -s c -d 'The total number of bytes to transfer as a decimal integer'
complete -c spi -s d -d 'Transfer direction: Use r for read, w for write, and rw for simultaneous read…'
complete -c spi -s f -d 'SPI device to use default is Pa /dev/spigen0'
complete -c spi -s h -d 'Print help text to stderr, explaining the command line options'
complete -c spi -s i -d 'Displays information about the SPI device to stderr'
complete -c spi -s L -d 'LSB bit order.  The default is MSB, i. e'
complete -c spi -s m -d 'SPI mode, 0 through 3'
complete -c spi -s s -d 'Specify the maximum speed, in Hz, for the SPI clock'
complete -c spi -s v -d 'Specifies Verbose mode.  Diagnostics and information are written to stderr'

