# ssh-copy-id
# Autogenerated from man page /usr/share/man/man1/ssh-copy-id.1.gz
complete -c ssh-copy-id -s i -d 'Copy the public key contained in file'
complete -c ssh-copy-id -s l -d 'Copy the keys currently held by ssh-agent 1'
complete -c ssh-copy-id -s o -d 'Pass this option directly to ssh 1'
complete -c ssh-copy-id -s p -d 'Connect to the specified port on the remote host instead of the default'
complete -c ssh-copy-id -s v -d 'Pass -v to ssh 1'

