# stat
# Autogenerated from man page /usr/share/man/man1/stat.1.gz
complete -c stat -s F -d 'As in ls 1, display a slash / immediately after each pathname that is a direc…'
complete -c stat -s H -d 'Treat each argument as the hexadecimal representation of an NFS file handle, …'
complete -c stat -s L -d 'Use stat 2 instead of lstat 2'
complete -c stat -s n -d 'Do not force a newline to appear at the end of each piece of output'
complete -c stat -s q -d 'Suppress failure messages if calls to stat 2 or lstat 2 fail'
complete -c stat -s f -d 'Display information using the specified format'
complete -c stat -s l -d 'Display output in stat ls Fl lT format'
complete -c stat -s r -d 'Display raw information'
complete -c stat -s s -d 'Display information in shell output format, suitable for initializing variabl…'
complete -c stat -s t -d 'Display timestamps using the specified format'
complete -c stat -s x -d 'Display information in a more verbose way as known from some Linux distributi…'

