# stdbuf
# Autogenerated from man page /usr/share/man/man1/stdbuf.1.gz
complete -c stdbuf -s e -d 'Set initial buffering of the standard error stream for command as defined by …'
complete -c stdbuf -s i -d 'Set initial buffering of the standard input stream for command as defined by …'
complete -c stdbuf -s o -d 'Set initial buffering of the standard output stream for command as defined by…'

