# strings
# Autogenerated from man page /usr/share/man/man1/strings.1.gz
complete -c strings -s a -d 'For ELF objects, scan the entire file for printable strings'
complete -c strings -s e -d 'Select the character encoding to be used while searching for strings'
complete -c strings -s f -d 'Print the name of the file before each string'
complete -c strings -s h -d 'Print a usage summary and exit'
complete -c strings -s o -d 'Equivalent to specifying t Ar o'
complete -c strings -s t -d 'Print the offset from the start of the file before each string using the spec…'
complete -c strings -s v -d 'Display a version identifier and exit'

