# string2key
# Autogenerated from man page /usr/share/man/man8/string2key.8.gz
complete -c string2key -s 5 -d 'Output Kerberos v5 string-to-key'
complete -c string2key -s 4 -d 'Output Kerberos v4 string-to-key'
complete -c string2key -s a -d 'Output AFS string-to-key'
complete -c string2key -s c -d 'AFS cell to use'
complete -c string2key -s w -d 'Password to use'
complete -c string2key -s p -d 'Kerberos v5 principal to use'
complete -c string2key -s k -d Keytype
complete -c string2key -l version -d 'print version'
complete -c string2key -l help -d El

