# strip
# Autogenerated from man page /usr/share/man/man1/strip.1.gz
complete -c strip -s d -d 'Remove debugging symbols only'
complete -c strip -s h -d 'Print a help message and exit'
complete -c strip -l only-keep-debug -d 'Remove all content except that which would be used for debugging'
complete -c strip -s o -d 'Write the stripped object to file outputfile instead of modifying the input i…'
complete -c strip -s p -d 'Preserve the object\'s access and modification times'
complete -c strip -s s -d 'Remove all symbols'
complete -c strip -l strip-unneeded -d 'Remove all symbols not needed for further relocation processing'
complete -c strip -s w -d 'Use shell-style patterns to name symbols'
complete -c strip -s x -d 'Discard all non-global symbols'
complete -c strip -s I -d 'These options are accepted, but are ignored'
complete -c strip -s K -d 'Keep the symbol symbol even if it would otherwise be stripped'
complete -c strip -s N -d 'Remove the symbol symbol even if it would otherwise have been kept'
complete -c strip -s O -d 'Set the output file format to format'
complete -c strip -s R -d 'Remove the section named by the argument sectionname'
complete -c strip -s V -d 'Print a version identifier and exit'
complete -c strip -s X -d 'Remove compiler-generated local symbols'

