# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
complete -c su -s c -d 'Use the settings of the specified login class'
complete -c su -s f -d 'If the invoked shell is csh 1, this option prevents it from reading the '
complete -c su -s l -d 'Simulate a full login'
complete -c su -s m -d 'Leave the environment unmodified'
complete -c su -s s -d 'Set the MAC label to the user\'s default label as part of the user credential …'

