# swapoff
# Autogenerated from man page /usr/share/man/man8/swapoff.8.gz
complete -c swapoff -s F -d 'Specify the fstab file to use (in conjunction with a Ns )'
complete -c swapoff -s h -d 'Output values in human-readable form'
complete -c swapoff -s g -d 'Output values in gigabytes'
complete -c swapoff -s k -d 'Output values in kilobytes'
complete -c swapoff -s m -d 'Output values in megabytes'
complete -c swapoff -s l -d 'List the devices making up system swap'
complete -c swapoff -s s -d 'Print a summary line for system swap'

