# swapctl
# Autogenerated from man page /usr/share/man/man8/swapctl.8.gz
complete -c swapctl -s F -d 'Specify the fstab file to use (in conjunction with a Ns )'
complete -c swapctl -s h -d 'Output values in human-readable form'
complete -c swapctl -s g -d 'Output values in gigabytes'
complete -c swapctl -s k -d 'Output values in kilobytes'
complete -c swapctl -s m -d 'Output values in megabytes'
complete -c swapctl -s l -d 'List the devices making up system swap'
complete -c swapctl -s s -d 'Print a summary line for system swap'

