# tabs
# Autogenerated from man page /usr/share/man/man1/tabs.1.gz
complete -c tabs -s T -d 'Tell tabs which terminal type to use'
complete -c tabs -s d -d 'The debugging option shows a ruler line, followed by two data lines'
complete -c tabs -s n -d 'This option tells tabs to check the options and run any debugging option, but…'
complete -c tabs -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c tabs -s a -d 'Assembler, IBM S/370, first format'
complete -c tabs -o a2 -d 'Assembler, IBM S/370, second format'
complete -c tabs -s c -d 'COBOL, normal format'
complete -c tabs -o c2 -d 'COBOL compact format'
complete -c tabs -o c3 -d 'COBOL compact format extended'
complete -c tabs -s f -d FORTRAN
complete -c tabs -s p -d PL/I
complete -c tabs -s s -d SNOBOL
complete -c tabs -s u -d 'UNIVAC 1100 Assembler PORTABILITY'

