# tail
# Autogenerated from man page /usr/share/man/man1/tail.1.gz
complete -c tail -s b -d 'The location is number 512-byte blocks'
complete -c tail -s c -d 'The location is number bytes'
complete -c tail -s f -d 'The f option causes tail to not stop when end of file is reached, but rather …'
complete -c tail -s F -d 'The F option implies the f option, but tail will also check to see if the fil…'
complete -c tail -s n -d 'The location is number lines'
complete -c tail -s q -d 'Suppresses printing of headers when multiple files are being examined'
complete -c tail -s r -d 'The r option causes the input to be displayed in reverse order, by line'
complete -c tail -s v -d 'Prepend each file with a header'

