# tcopy
# Autogenerated from man page /usr/share/man/man1/tcopy.1.gz
complete -c tcopy -s c -d 'Copy src to dest and then verify that the two tapes are identical'
complete -c tcopy -s s -d 'Specify a maximum block size, maxblk'
complete -c tcopy -s v -d 'Given the two tapes src and dest, verify that they are identical'
complete -c tcopy -s x -d 'Output all informational messages to the standard error instead of the standa…'

