# tcpdmatch
# Autogenerated from man page /usr/share/man/man8/tcpdmatch.8.gz
complete -c tcpdmatch -s d -d 'Examine hosts. allow and hosts'
complete -c tcpdmatch -s i -d 'Specify this option when tcpdmatch is unable to find your inetd. conf or tlid'

