# tcpdchk
# Autogenerated from man page /usr/share/man/man8/tcpdchk.8.gz
complete -c tcpdchk -s a -d 'Report access control rules that permit access without an explicit ALLOW keyw…'
complete -c tcpdchk -s d -d 'Examine hosts. allow and hosts'
complete -c tcpdchk -s i -d 'Specify this option when tcpdchk is unable to find your inetd. conf or tlid'
complete -c tcpdchk -s v -d 'Display the contents of each access control rule'

