# tee
# Autogenerated from man page /usr/share/man/man1/tee.1.gz
complete -c tee -s a -d 'Append the output to the files rather than overwriting them'
complete -c tee -s i -d 'Ignore the SIGINT signal'

