# tftpd
# Autogenerated from man page /usr/share/man/man8/tftpd.8.gz
complete -c tftpd -s c -d 'Changes the default root directory of a connecting host via chroot 2 based on…'
complete -c tftpd -s C -d 'Operates the same as c except it falls back to directory specified via s if a…'
complete -c tftpd -s F -d 'Use this strftime 3 compatible format string for the creation of the suffix i…'
complete -c tftpd -s d -d 'Enables debug output'
complete -c tftpd -s l -d 'Log all requests using syslog 3 with the facility of LOG_FTP'
complete -c tftpd -s n -d 'Suppress negative acknowledgement of requests for nonexistent relative filena…'
complete -c tftpd -s o -d 'Disable support for RFC2347 style TFTP Options'
complete -c tftpd -s s -d 'Cause tftpd to change its root directory to directory'
complete -c tftpd -s S -d 'If tftpd runs chrooted, the option allows write requests according to generic…'
complete -c tftpd -s u -d 'Switch credentials to user (default nobody ) when the s option is used'
complete -c tftpd -s U -d 'Set the umask for newly created files.  The default is 022 S_IWGRP | S_IWOTH'
complete -c tftpd -s w -d 'Allow write requests to create new files'
complete -c tftpd -s W -d 'As w but append a YYYYMMDD. nn sequence number to the end of the filename'

