# tftp-proxy
# Autogenerated from man page /usr/share/man/man8/tftp-proxy.8.gz
complete -c tftp-proxy -s v -d 'Log the connection and request information to syslogd 8'
complete -c tftp-proxy -s w -d 'Number of seconds to wait for the data transmission to begin before removing …'

