# tiff2bw
# Autogenerated from man page /usr/local/man/man1/tiff2bw.1.gz
complete -c tiff2bw -s c -d 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c tiff2bw -s r -d 'Write data with a specified number of rows per strip; by default the number o…'
complete -c tiff2bw -s R -d 'Specify the percentage of the red channel to use (default 28)'
complete -c tiff2bw -s G -d 'Specify the percentage of the green channel to use (default 59)'
complete -c tiff2bw -s B -d 'options may be used.  OPTIONS'

