# tiffset
# Autogenerated from man page /usr/local/man/man1/tiffset.1.gz
complete -c tiffset -s d -d 'change the current directory (starting at 0)'
complete -c tiffset -s s -d 'Set the value of the named tag to the value or values specified'
complete -c tiffset -o sd -d 'change the current directory by offset'
complete -c tiffset -o sf -d 'Set the value of the tag to the contents of filename'
complete -c tiffset -s u -d 'Unset the tag'

