# timeout
# Autogenerated from man page /usr/share/man/man1/timeout.1.gz
complete -c timeout -l preserve-status -d 'Exit with the same status as command, even if it times out and is killed'
complete -c timeout -l foreground -d 'Do not propagate timeout to the children of command'
complete -c timeout -s s -d 'Specify the signal to send on timeout.  By default, SIGTERM is sent'
complete -c timeout -s k -d 'Send a SIGKILL signal if command is still running after time after the first …'

