# time
# Autogenerated from man page /usr/share/man/man1/time.1.gz
complete -c time -s a -d 'If the o flag is used, append to the specified file rather than overwriting it'
complete -c time -s h -d 'Print times in a human friendly format'
complete -c time -s l -d 'The contents of the rusage structure are printed as well'
complete -c time -s o -d 'Write the output to file instead of stderr'
complete -c time -s p -d 'Makes time output POSIX. 2 compliant (each time is printed on its own line)'

