# touch
# Autogenerated from man page /usr/share/man/man1/touch.1.gz
complete -c touch -s A -d 'Adjust the access and modification time stamps for the file by the specified …'
complete -c touch -s a -d 'Change the access time of the file'
complete -c touch -s c -d 'Do not create the file if it does not exist'
complete -c touch -s d -d 'Change the access and modification times to the specified date time instead o…'
complete -c touch -s h -d 'If the file is a symbolic link, change the times of the link itself rather th…'
complete -c touch -s m -d 'Change the modification time of the file'
complete -c touch -s r -d 'Use the access and modifications times from the specified file instead of the…'
complete -c touch -s t -d 'Change the access and modification times to the specified time instead of the…'

