# trim
# Autogenerated from man page /usr/share/man/man8/trim.8.gz
complete -c trim -s N -d 'Do not actually erase anything but show what it would do (dry run)'
complete -c trim -s f -d 'Perform the operation.  Overrides N'
complete -c trim -s l -d 'off offset K | k | M | m | G | g | T | t on Xc'
complete -c trim -s o -d 'off offset K | k | M | m | G | g | T | t on Xc Specify the length l of the re…'
complete -c trim -s q -d 'Do not output anything except of possible error messages (quiet mode)'
complete -c trim -s r -d 'Uses the length of given rfile as length of the region to erase'
complete -c trim -s v -d 'Show offset and length of actual region being erased, in bytes'

