# truss
# Autogenerated from man page /usr/share/man/man1/truss.1.gz
complete -c truss -s f -d 'Trace descendants of the original traced process created by fork 2, vfork 2, …'
complete -c truss -s a -d 'Show the argument strings that are passed in each execve 2 system call'
complete -c truss -s c -d 'Do not display individual system calls or signals'
complete -c truss -s e -d 'Show the environment strings that are passed in each execve 2 system call'
complete -c truss -s d -d 'Include timestamps in the output showing the time elapsed since the trace was…'
complete -c truss -s D -d 'Include timestamps in the output showing the time elapsed since the last reco…'
complete -c truss -s H -d 'Include the thread ID of in the output of each event'
complete -c truss -s S -d 'Do not display information about signals received by the process'
complete -c truss -s o -d 'Print the output to the specified file instead of standard error'
complete -c truss -s s -d 'Display strings using at most strsize characters.  If the buffer is larger, '
complete -c truss -s p -d 'Follow the process specified by pid instead of a new command'

