# tzsetup
# Autogenerated from man page /usr/share/man/man8/tzsetup.8.gz
complete -c tzsetup -s C -d 'Open all files and directories relative to chroot_directory'
complete -c tzsetup -s n -d 'Do not create or copy files'
complete -c tzsetup -s r -d 'Reinstall the zoneinfo file installed last time'
complete -c tzsetup -s s -d 'Skip the initial question about adjusting the clock if not set to UTC'

