# udaddy
# Autogenerated from man page /usr/share/man/man1/udaddy.1.gz
complete -c udaddy -s s -d 'The network name or IP address of the server system listening for communicati…'
complete -c udaddy -s b -d 'The local network address to bind to'
complete -c udaddy -s c -d 'The number of communication paths to establish between the client and server'
complete -c udaddy -s C -d 'The number of messages to transfer over each connection.   (default 10)'
complete -c udaddy -s S -d 'The size of each message transferred, in bytes'
complete -c udaddy -s t -d 'Indicates the type of service used for the communication'

