# uhsoctl
# Autogenerated from man page /usr/share/man/man1/uhsoctl.1.gz
complete -c uhsoctl -s a -d 'Specify APN to connect to'
complete -c uhsoctl -s c -d 'Specify CID (Context ID) to use, by default CID 1 is used'
complete -c uhsoctl -s p -d 'Specify SIM PIN'
complete -c uhsoctl -s u -d 'Specify username'
complete -c uhsoctl -s k -d 'Specify username'
complete -c uhsoctl -s r -d 'Path to resolv. conf, default /etc/resolv. conf'
complete -c uhsoctl -s f -d 'Explicitly set the serial port to use as controlling terminal'
complete -c uhsoctl -s b -d 'Fork into background directly, before a connection has been established'
complete -c uhsoctl -s n -d 'Never fork into background, run entirely in foreground'

