# umount
# Autogenerated from man page /usr/share/man/man8/umount.8.gz
complete -c umount -s a -d 'All the file systems described in fstab 5 are unmounted'
complete -c umount -s A -d 'All the currently mounted file systems are unmounted, except for those mounte…'
complete -c umount -s F -d 'Specify the fstab file to use'
complete -c umount -s f -d 'The file system is forcibly unmounted'
complete -c umount -s h -d 'Only file systems mounted from the specified host will be unmounted'
complete -c umount -s N -d 'Do a forced dismount of an NFS mount point without checking the mount path'
complete -c umount -s n -d 'Unless the f is used, the umount will not unmount an active file system'
complete -c umount -s t -d 'Is used to indicate the actions should only be taken on file systems of the s…'
complete -c umount -s v -d 'Verbose, additional information is printed out as each file system is unmount…'

