# unexpand
# Autogenerated from man page /usr/share/man/man1/unexpand.1.gz
complete -c unexpand -s a -d 'unexpand ( unexpand only'
complete -c unexpand -s t -d 'Set tab stops at column positions tab1 , tab2 , .  , tabn'

