# uniq
# Autogenerated from man page /usr/share/man/man1/uniq.1.gz
complete -c uniq -s c -d 'Precede each output line with the count of the number of times the line occur…'
complete -c uniq -s d -d 'Output a single copy of each line that is repeated in the input'
complete -c uniq -s D -d 'Output all lines that are repeated (like d, but each copy of the repeated lin…'
complete -c uniq -s f -d 'Ignore the first num fields in each input line when doing comparisons'
complete -c uniq -s i -d 'Case insensitive comparison of lines'
complete -c uniq -s s -d 'Ignore the first chars characters in each input line when doing comparisons'
complete -c uniq -s u -d 'Only output lines that are not repeated in the input'

