# units
# Autogenerated from man page /usr/share/man/man1/units.1.gz
complete -c units -s e -d 'Same as o %6e (see the description of the o flag)'
complete -c units -s f -d 'Specify the name of the units data file to load'
complete -c units -s H -d 'Ignored, for compatibility with GNU units'
complete -c units -s h -d 'Show an overview of options'
complete -c units -s o -d 'Select the output format string by which numbers are printed.  Defaults to %'
complete -c units -s q -d 'Suppress prompting of the user for units and the display of statistics about …'
complete -c units -s t -d 'Only print the result'
complete -c units -s U -d 'Print the location of the default unit file if it exists'
complete -c units -s V -d 'Print the version number which is fixed at Dq Fx units, the path to the units…'
complete -c units -s v -d 'Print the units in the conversion output.  Be more verbose in general'

