# unstr
# Autogenerated from man page /usr/share/man/man8/unstr.8.gz
complete -c unstr -s C -d 'Flag the file as containing comments'
complete -c unstr -s c -d 'Change the delimiting character from the percent sign to char'
complete -c unstr -s i -d 'Ignore case when ordering the strings'
complete -c unstr -s o -d 'Order the strings in alphabetical order'
complete -c unstr -s r -d 'Randomize access to the strings'
complete -c unstr -s s -d 'Run silently; do not give a summary message when finished'
complete -c unstr -s x -d 'Note that each alphabetic character in the groups of lines is rotated 13 posi…'

