# unvis
# Autogenerated from man page /usr/share/man/man1/unvis.1.gz
complete -c unvis -s e -d 'Don\'t decode \\e escaped sequences'
complete -c unvis -s H -d 'Decode entity references and numeric character references from RFC 1866'
complete -c unvis -s h -d 'Decode using the URI encoding from RFC 1808.  VIS_HTTP1808'
complete -c unvis -s m -d 'Decode using mime style'

