# unzip
# Autogenerated from man page /usr/share/man/man1/unzip.1.gz
complete -c unzip -s a -d 'When extracting a text file, convert DOS-style line endings to Unix-style lin…'
complete -c unzip -s C -d 'Match file names case-insensitively'
complete -c unzip -s c -d 'Extract to stdout/screen'
complete -c unzip -s d -d 'Extract files into the specified directory rather than the current directory'
complete -c unzip -s f -d 'Update existing'
complete -c unzip -s I
complete -c unzip -s O -d 'Convert filenames from the specified encoding'
complete -c unzip -s j -d 'Ignore directories stored in the zipfile; instead, extract all files directly…'
complete -c unzip -s L -d 'Convert the names of the extracted files and directories to lowercase'
complete -c unzip -s l -d 'List, rather than extract, the contents of the zipfile'
complete -c unzip -s n -d 'No overwrite'
complete -c unzip -s o -d Overwrite
complete -c unzip -s p -d 'Extract to stdout'
complete -c unzip -s P -d 'Extract encrypted files using a password'
complete -c unzip -s q -d 'Quiet: print less information while extracting'
complete -c unzip -s t -d 'Test: do not extract anything, but verify the checksum of every file in the a…'
complete -c unzip -s u -d Update
complete -c unzip -s v -d 'List verbosely, rather than extract, the contents of the zipfile'
complete -c unzip -s x -d 'Exclude files matching the pattern pattern'
complete -c unzip -s y -d 'Print four digit years in listings instead of two'
complete -c unzip -s Z -d 'Emulate zipinfo 1L mode'

