# unzstd
# Autogenerated from man page /usr/share/man/man1/unzstd.1.gz
complete -c unzstd -s '#'
complete -c unzstd -l ultra
complete -c unzstd -l fast -l fast
complete -c unzstd -o 'T#' -l threads
complete -c unzstd -l single-thread -o T1 -o T1
complete -c unzstd -l auto-threads -o T0
complete -c unzstd -l adapt -s v -l long -l adapt
complete -c unzstd -s D
complete -c unzstd -l patch-from
complete -c unzstd -l rsyncable
complete -c unzstd -s C -l check
complete -c unzstd -l content-size -l content-size
complete -c unzstd -l no-dictID
complete -c unzstd -o 'M#' -l memory
complete -c unzstd -l stream-size
complete -c unzstd -l size-hint
complete -c unzstd -s o
complete -c unzstd -s f -l force
complete -c unzstd -s c -l stdout
complete -c unzstd -l sparse
complete -c unzstd -l rm
complete -c unzstd -s k -l keep
complete -c unzstd -s r
complete -c unzstd -l filelist
complete -c unzstd -l output-dir-flat
complete -c unzstd -l output-dir-mirror
complete -c unzstd -l format
complete -c unzstd -o h/-H -l help
complete -c unzstd -s V -l version -o vV -o vvV -s q
complete -c unzstd -l verbose
complete -c unzstd -l quiet
complete -c unzstd -l no-progress
complete -c unzstd -l show-default-cparams
complete -c unzstd -l train-fastcover -l train-legacy -l train-cover -l train-fastcover
complete -c unzstd -l maxdict -d 'Limit dictionary to specified size (default: 112640)'
complete -c unzstd -o 'B#' -d 'Split input files into blocks of size # (default: no split)'
complete -c unzstd -l dictID -d 'A dictionary ID is a locally unique ID that a decoder can use to verify it is…'
complete -c unzstd -o 'e#' -d 'benchmark file(s) using multiple compression levels, from -b# to -e# (inclusi…'
complete -c unzstd -o 'i#' -d 'minimum evaluation time, in seconds (default: 3s), benchmark mode only'
complete -c unzstd -l block-size -d 'cut file(s) into independent blocks of size # (default: no block)'
complete -c unzstd -l priority -d 'set process priority to real-time Output Format: CompressionLevel#Filename : …'
complete -c unzstd -l zstd -d 'zstd provides 22 predefined compression levels'

