# usbconfig
# Autogenerated from man page /usr/share/man/man8/usbconfig.8.gz
complete -c usbconfig -s a -d 'Limit device range to the given USB device index'
complete -c usbconfig -s h -d 'Show help and available commands'
complete -c usbconfig -s i -d 'Specify interface index as indicated by the command description'
complete -c usbconfig -s u -d 'Limit device range to USB devices connected to the given USBUS unit'
complete -c usbconfig -s v -d 'Activate the dump_device_desc, dump_curr_config_desc, and show_ifdrv commands…'

