# usbdump
# Autogenerated from man page /usr/share/man/man8/usbdump.8.gz
complete -c usbdump -s d -d 'Shortcut for i option.  The argument may be prefixed by "ugen"'
complete -c usbdump -s b -d 'Store data part of the USB trace in binary format to the given file'
complete -c usbdump -s i -d 'Listen on USB bus interface ifname'
complete -c usbdump -s r -d 'Read the raw packets from file.  This option also works with the -f option'
complete -c usbdump -s s -d 'Snapshot snaplen bytes from each packet'
complete -c usbdump -s v -d 'Enable debugging messages'
complete -c usbdump -s w -d 'Write the raw packets to file'
complete -c usbdump -s f -d 'The filter argument consists of either one or two numbers separated by a dot'
complete -c usbdump -s h -d 'This option displays a summary of the command line options'

