# usbhidctl
# Autogenerated from man page /usr/share/man/man1/usbhidctl.1.gz
complete -c usbhidctl -s a -d 'Show all items and their current values if device returns'
complete -c usbhidctl -s f -d 'Specify a path name for the device to operate on'
complete -c usbhidctl -s l -d 'Loop and dump the device data every time it changes'
complete -c usbhidctl -s n -d 'Suppress printing of the item name'
complete -c usbhidctl -s r -d 'Dump the report descriptor'
complete -c usbhidctl -s t -d 'Specify a path name for the HID usage table file'
complete -c usbhidctl -s v -d 'Be verbose'
complete -c usbhidctl -s w -d 'Change item values'
complete -c usbhidctl -s x -d 'Dump data in hexadecimal as well as decimal'
complete -c usbhidctl -s z -d 'Reset reports to zero before processing other arguments'

