# uudecode
# Autogenerated from man page /usr/share/man/man1/uudecode.1.gz
complete -c uudecode -s m -d 'Use the Base64 method of encoding, rather than the traditional uudecode uuenc…'
complete -c uudecode -s r -d 'Produce raw output by excluding the initial and final framing lines'
complete -c uudecode -s o -d 'Output to output_file instead of standard output'
complete -c uudecode -s c -d 'Decode more than one uuencoded file from file if possible'
complete -c uudecode -s i -d 'Do not overwrite files'
complete -c uudecode -s p -d 'Decode file and write output to standard output'
complete -c uudecode -s s -d 'Do not strip output pathname to base filename'
complete -c uudecode -s w -d 'Wrap encoded output after column'
complete -c uudecode -s u -d Decode

