# uuidgen
# Autogenerated from man page /usr/share/man/man1/uuidgen.1.gz
complete -c uuidgen -s 1 -d 'This option only has effect if multiple identifiers are to be generated and i…'
complete -c uuidgen -s r -d 'This option controls creation of random UUID (version 4)'
complete -c uuidgen -s c -d 'This option controls creation of compact UUID (without hyphen)'
complete -c uuidgen -s n -d 'This option controls the number of identifiers generated'
complete -c uuidgen -s o -d 'Redirect output to filename instead of stdout'

