# vacation
# Autogenerated from man page /usr/share/man/man1/vacation.1.gz
complete -c vacation -s a -d 'Handle messages for  alias in the same manner as those received for the user\'…'
complete -c vacation -s C -d 'Specify pathname of the sendmail configuration file'
complete -c vacation -s d -d 'Send error/debug messages to stderr instead of syslog'
complete -c vacation -s f -d 'Use  filename as name of the database instead of R ~/. vacation. db or R ~/'
complete -c vacation -s i -d 'Initialize the vacation database files'
complete -c vacation -s I -d 'Same as  -i (for backwards compatibility)'
complete -c vacation -s j -d 'Respond to the message regardless of whether the login is listed as a recipie…'
complete -c vacation -s l -d 'List the content of the vacation database file including the address and the …'
complete -c vacation -s m -d 'Use  filename as name of the file containing the message to send instead of R…'
complete -c vacation -s R -d 'Set the reply envelope sender address'
complete -c vacation -s r -d 'Set the reply interval to  interval days.   The default is one week'
complete -c vacation -s s -d 'Use  address instead of the incoming message sender address on the  From line…'
complete -c vacation -s t -d 'Ignored, available only for compatibility with Sun\'s vacation program'
complete -c vacation -s U -d 'Do not attempt to lookup  login in the password file'
complete -c vacation -s x -d 'Reads an exclusion list from stdin (one address per line)'
complete -c vacation -s z -d 'Set the sender of the vacation message to ``<>\'\' instead of the user'
complete -c vacation -l eric

