# valectl
# Autogenerated from man page /usr/share/man/man8/valectl.8.gz
complete -c valectl -s g -d 'Print the number of receive rings of valeSSS:PPP'
complete -c valectl -s a -d 'Attach interface (which must be an existing network interface) to valeSSS and…'
complete -c valectl -s h -d 'Attach interface (which must be an existing network interface) to valeSSS whi…'
complete -c valectl -s d -d 'Detach interface from valeSSS'
complete -c valectl -s n -d 'Create a new persistent VALE port with name interface'
complete -c valectl -s r -d 'Destroy the persistent VALE port with name interface'
complete -c valectl -s l -d 'Show the internal bridge number and port number of the given switch port'
complete -c valectl -s p -d 'Enable polling mode for valeSSS:PPP'
complete -c valectl -s P -d 'Disable polling mode for valeSSS:PPP'
complete -c valectl -s C -d 'When used in conjunction with n it supplies the number of tx and rx rings and…'
complete -c valectl -s m -d 'Used in conjunction with n supplies the netmap memory region identifier to us…'

