# vi
# Autogenerated from man page /usr/share/man/man1/vi.1.gz
complete -c vi -s c -d 'Execute cmd on the first file loaded'
complete -c vi -s e -d 'Start editing in ex mode, as if the command name were vi ex'
complete -c vi -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c vi -s R -d 'Start editing in read-only mode, as if the command name was vi view, or the r…'
complete -c vi -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c vi -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c vi -s s -d 'Enter batch mode; applicable only to vi ex edit sessions'
complete -c vi -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c vi -s v -d 'Start editing in vi mode, as if the command name was vi vi'
complete -c vi -s w -d 'Set the initial window size to the specified number of lines'

