# vidfont
# Autogenerated from man page /usr/share/man/man1/vidfont.1.gz
complete -c vidfont -s K -d 'Run as command vidfont'
complete -c vidfont -s V -d 'Run as command vidfont vidfont'
complete -c vidfont -s d -d 'Use default language.  Ignore LANG environment variable'
complete -c vidfont -s h -d 'Print options and exit'
complete -c vidfont -s l -d 'Use language for description and menu'
complete -c vidfont -s p -d 'Print description of available keymaps or fonts to stdout and exit'
complete -c vidfont -s r -d 'Load default font from /etc/rc. conf'
complete -c vidfont -s s -d 'Show currently supported languages and exit'
complete -c vidfont -s v -d 'More warnings'

