# view
# Autogenerated from man page /usr/share/man/man1/view.1.gz
complete -c view -s c -d 'Execute cmd on the first file loaded'
complete -c view -s e -d 'Start editing in ex mode, as if the command name were view ex'
complete -c view -s F -d 'Don\'t copy the entire file when first starting to edit'
complete -c view -s R -d 'Start editing in read-only mode, as if the command name was view view, or the…'
complete -c view -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c view -s S -d 'Run with the secure edit option set, disallowing all access to external progr…'
complete -c view -s s -d 'Enter batch mode; applicable only to view ex edit sessions'
complete -c view -s t -d 'Start editing at the specified tag see Xr ctags 1'
complete -c view -s v -d 'Start editing in vi mode, as if the command name was view vi'
complete -c view -s w -d 'Set the initial window size to the specified number of lines'

