# vtfontcvt
# Autogenerated from man page /usr/share/man/man8/vtfontcvt.8.gz
complete -c vtfontcvt -s f -d 'Specify the output format'
complete -c vtfontcvt -s h -d 'Set font height.  The default is 16'
complete -c vtfontcvt -s n -d 'Do not apply output filtering with C source output'
complete -c vtfontcvt -s o -d 'Specify the name for the output file'
complete -c vtfontcvt -s v -d 'Display verbose statistics about the converted font'
complete -c vtfontcvt -s w -d 'Set font width.  The default is 8'

