# w
# Autogenerated from man page /usr/share/man/man1/w.1.gz
complete -c w -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c w -s d -d 'dumps out the entire process list on a per controlling tty basis, instead of …'
complete -c w -s h -d 'Suppress the heading'
complete -c w -s i -d 'Output is sorted by idle time'
complete -c w -s M -d 'Extract values associated with the name list from the specified core instead …'
complete -c w -s N -d 'Extract the name list from the specified system instead of the default /boot/…'
complete -c w -s n -d 'Do not attempt to resolve network addresses (normally w interprets addresses …'

