# watchdogd
# Autogenerated from man page /usr/share/man/man8/watchdogd.8.gz
complete -c watchdogd -s I -d 'Write the process ID of the watchdogd utility in the specified file'
complete -c watchdogd -s d -d 'Do not fork'
complete -c watchdogd -s S -d 'Do not send a message to the system logger when the watchdog command takes lo…'
complete -c watchdogd -s w -d 'Complain when the watchdog script takes too long'
complete -c watchdogd -l pretimeout -d 'Set a "pretimeout" watchdog'
complete -c watchdogd -l pretimeout-action -d 'Set the timeout action for the pretimeout.  See the section Timeout Actions'
complete -c watchdogd -l softtimeout -d 'Instead of arming the various hardware watchdogs, only use a basic software w…'
complete -c watchdogd -l softtimeout-action -d 'Set the timeout action for the softtimeout.  See the section Timeout Actions'

