# wc
# Autogenerated from man page /usr/share/man/man1/wc.1.gz
complete -c wc -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c wc -s L -d 'Write the length of the line containing the most bytes (default) or character…'
complete -c wc -s c -d 'The number of bytes in each input file is written to the standard output'
complete -c wc -s l -d 'The number of lines in each input file is written to the standard output'
complete -c wc -s m -d 'The number of characters in each input file is written to the standard output'
complete -c wc -s w -d 'The number of words in each input file is written to the standard output'

