# what
# Autogenerated from man page /usr/share/man/man1/what.1.gz
complete -c what -s q -d 'Only output the match text, rather than formatting it'
complete -c what -s s -d 'Stop searching each file after the first match'

