# whatis
# Autogenerated from man page /usr/share/man/man1/whatis.1.gz
complete -c whatis -s a -d 'Instead of showing only the title lines, show the complete manual pages, just…'
complete -c whatis -s C -d 'Specify an alternative configuration file in man. conf 5 format'
complete -c whatis -s f -d 'Search for all words in expression in manual page names only'
complete -c whatis -s k -d 'Support the full expression syntax.  It is the default for whatis'
complete -c whatis -s M -d 'Use the colon-separated path instead of the default list of paths searched fo…'
complete -c whatis -s m -d 'Prepend the colon-separated paths to the list of paths searched for makewhati…'
complete -c whatis -s O -d 'Show the values associated with the key outkey instead of the manual descript…'
complete -c whatis -s S -d 'Restrict the search to pages for the specified machine 1 architecture'
complete -c whatis -s s -d 'Restrict the search to the specified section of the manual'
complete -c whatis -s i -d 'If term is a regular expression, it is evaluated case-insensitively'

