# which
# Autogenerated from man page /usr/share/man/man1/which.1.gz
complete -c which -s a -d 'List all instances of executables found (instead of just the first one of eac…'
complete -c which -s s -d 'No output, just return 0 if all of the executables are found, or 1 if some we…'

