# who
# Autogenerated from man page /usr/share/man/man1/who.1.gz
complete -c who -s a -d 'Equivalent to bTu, with the exception that output is not restricted to the ti…'
complete -c who -s b -d 'Write the time and date of the last system reboot'
complete -c who -s H -d 'Write column headings above the output'
complete -c who -s m -d 'Show information about the terminal attached to standard input only'
complete -c who -s q -d '"Quick mode" : List the names and number of logged in users in columns'
complete -c who -s s -d 'Show the name, line and time fields only.  This is the default'
complete -c who -s T -d 'Indicate whether each user is accepting messages'
complete -c who -s u -d 'Show idle time for each user in hours and minutes as hh : Ns Ar mm, \\&'

