# wpa_cli
# Autogenerated from man page /usr/share/man/man8/wpa_cli.8.gz
complete -c wpa_cli -s p -d 'Control sockets path.  This should match the ctrl_interface in wpa_supplicant'
complete -c wpa_cli -s i -d 'Interface to be configured'
complete -c wpa_cli -s h -d 'Show help'
complete -c wpa_cli -s v -d 'Show version information'
complete -c wpa_cli -s B -d 'Run the daemon in the background'
complete -c wpa_cli -s a -d 'Run in daemon mode, executing the action file based on events from wpa_suppli…'
complete -c wpa_cli -s P -d 'PID file location'
complete -c wpa_cli -s g -d 'Use a global control interface to wpa_supplicant 8 rather than the default Un…'
complete -c wpa_cli -s G -d 'Wait ping_interval seconds before sending each ping to wpa_supplicant 8'

