# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1.gz
complete -c xargs -s 0 -d 'Change xargs to expect NUL (``\\\\0\'\') characters as separators, instead of spa…'
complete -c xargs -s E -d 'Use eofstr as a logical EOF marker'
complete -c xargs -s I -d 'Execute utility for each input line, replacing one or more occurrences of rep…'
complete -c xargs -s J -d 'If this option is specified, xargs will use the data read from standard input…'
complete -c xargs -s L -d 'Call utility for every number lines read'
complete -c xargs -s n -d 'Set the maximum number of arguments taken from standard input for each invoca…'
complete -c xargs -s o -d 'Reopen stdin as /dev/tty in the child process before executing the command'
complete -c xargs -s P -d 'Parallel mode: run at most maxprocs invocations of utility at once'
complete -c xargs -s p -d 'Echo each command to be executed and ask the user whether it should be execut…'
complete -c xargs -s r -d 'Compatibility with GNU xargs'
complete -c xargs -s R -d 'Specify the maximum number of arguments that I will do replacement in'
complete -c xargs -s S -d 'Specify the amount of space (in bytes) that I can use for replacements'
complete -c xargs -s s -d 'Set the maximum number of bytes for the command line length provided to utili…'
complete -c xargs -s t -d 'Echo the command to be executed to standard error immediately before it is ex…'
complete -c xargs -s x -d 'Force xargs to terminate immediately if a command line containing number argu…'

