# xdg-desktop-menu
# Autogenerated from man page /usr/local/man/man1/xdg-desktop-menu.1.gz
complete -c xdg-desktop-menu -l noupdate -d 'Postpone updating the menu system'
complete -c xdg-desktop-menu -l novendor -d 'Normally, xdg-desktop-menu checks to ensure that any *. directory and *'
complete -c xdg-desktop-menu -l mode -d 'mode can be user or system'
complete -c xdg-desktop-menu -l help -d 'Show command synopsis'
complete -c xdg-desktop-menu -l manual -d 'Show this manual page'
complete -c xdg-desktop-menu -l version -d 'Show the xdg-utils version information'
complete -c xdg-desktop-menu -s 1 -d 'Error in command line syntax'
complete -c xdg-desktop-menu -s 2 -d 'One of the files passed on the command line did not exist'
complete -c xdg-desktop-menu -s 3 -d 'A required tool could not be found'
complete -c xdg-desktop-menu -s 4 -d 'The action failed'
complete -c xdg-desktop-menu -s 5 -d 'No permission to read one of the files passed on the command line'

