# xdg-mime
# Autogenerated from man page /usr/local/man/man1/xdg-mime.1.gz
complete -c xdg-mime -l mode -d 'mode can be user or system'
complete -c xdg-mime -l novendor -d 'Normally, xdg-mime checks to ensure that the mimetypes-file to be installed h…'
complete -c xdg-mime -l help -d 'Show command synopsis'
complete -c xdg-mime -l manual -d 'Show this manual page'
complete -c xdg-mime -l version -d 'Show the xdg-utils version information'
complete -c xdg-mime -s 1 -d 'Error in command line syntax'
complete -c xdg-mime -s 2 -d 'One of the files passed on the command line did not exist'
complete -c xdg-mime -s 3 -d 'A required tool could not be found'
complete -c xdg-mime -s 4 -d 'The action failed'
complete -c xdg-mime -s 5 -d 'No permission to read one of the files passed on the command line'

