# xdg-email
# Autogenerated from man page /usr/local/man/man1/xdg-email.1.gz
complete -c xdg-email -l utf8 -d 'Indicates that all command line options that follow are in utf8'
complete -c xdg-email -l cc -d 'Specify a recipient to be copied on the e-mail'
complete -c xdg-email -l bcc -d 'Specify a recipient to be blindly copied on the e-mail'
complete -c xdg-email -l subject -d 'Specify a subject for the e-mail'
complete -c xdg-email -l body -d 'Specify a body for the e-mail'
complete -c xdg-email -l attach -d 'Specify an attachment for the e-mail.  file must point to an existing file'
complete -c xdg-email -l help -d 'Show command synopsis'
complete -c xdg-email -l manual -d 'Show this manual page'
complete -c xdg-email -l version -d 'Show the xdg-utils version information'
complete -c xdg-email -s 1 -d 'Error in command line syntax'
complete -c xdg-email -s 2 -d 'One of the files passed on the command line did not exist'
complete -c xdg-email -s 3 -d 'A required tool could not be found'
complete -c xdg-email -s 4 -d 'The action failed'
complete -c xdg-email -s 5 -d 'No permission to read one of the files passed on the command line'

