# xdg-screensaver
# Autogenerated from man page /usr/local/man/man1/xdg-screensaver.1.gz
complete -c xdg-screensaver -o suspend -d 'Suspends the screensaver and monitor power management'
complete -c xdg-screensaver -o resume -d 'Resume the screensaver and monitor power management after being suspended'
complete -c xdg-screensaver -o activate -d 'Turns the screensaver on immediately'
complete -c xdg-screensaver -o lock -d 'Lock the screen immediately'
complete -c xdg-screensaver -o reset -d 'Turns the screensaver off immediately'
complete -c xdg-screensaver -o status -d 'Prints enabled to stdout if the screensaver is enabled to turn on after a per…'
complete -c xdg-screensaver -l help -d 'Show command synopsis'
complete -c xdg-screensaver -l manual -d 'Show this manual page'
complete -c xdg-screensaver -l version -d 'Show the xdg-utils version information'
complete -c xdg-screensaver -s 1 -d 'Error in command line syntax'
complete -c xdg-screensaver -s 3 -d 'A required tool could not be found'
complete -c xdg-screensaver -s 4 -d 'The action failed'

