# xdg-desktop-icon
# Autogenerated from man page /usr/local/man/man1/xdg-desktop-icon.1.gz
complete -c xdg-desktop-icon -l novendor -d 'Normally, xdg-desktop-icon checks to ensure that a *'
complete -c xdg-desktop-icon -l help -d 'Show command synopsis'
complete -c xdg-desktop-icon -l manual -d 'Show this manual page'
complete -c xdg-desktop-icon -l version -d 'Show the xdg-utils version information'
complete -c xdg-desktop-icon -s 1 -d 'Error in command line syntax'
complete -c xdg-desktop-icon -s 2 -d 'One of the files passed on the command line did not exist'
complete -c xdg-desktop-icon -s 3 -d 'A required tool could not be found'
complete -c xdg-desktop-icon -s 4 -d 'The action failed'
complete -c xdg-desktop-icon -s 5 -d 'No permission to read one of the files passed on the command line'

