# xdg-open
# Autogenerated from man page /usr/local/man/man1/xdg-open.1.gz
complete -c xdg-open -l help -d 'Show command synopsis'
complete -c xdg-open -l manual -d 'Show this manual page'
complete -c xdg-open -l version -d 'Show the xdg-utils version information'
complete -c xdg-open -s 1 -d 'Error in command line syntax'
complete -c xdg-open -s 2 -d 'One of the files passed on the command line did not exist'
complete -c xdg-open -s 3 -d 'A required tool could not be found'
complete -c xdg-open -s 4 -d 'The action failed.  El SEE ALSO xdg-mime 1, xdg-settings 1, http://www'

