# xstr
# Autogenerated from man page /usr/share/man/man1/xstr.1.gz
complete -c xstr -s c -d 'Extract the strings from the C source file or the standard input , replacing …'
complete -c xstr -s v -d 'Verbose mode'

