# yacc
# Autogenerated from man page /usr/share/man/man1/yacc.1.gz
complete -c yacc -s B -d 'create a backtracking parser (compile-time configuration for btyacc)'
complete -c yacc -s d -d 'causes the header file  y. tab. h to be written'
complete -c yacc -s h -d 'print a usage message to the standard error'
complete -c yacc -s H -d 'causes #define\'s for the token identifiers to be written to the given defines…'
complete -c yacc -s g -d 'The  -g option causes a graphical description of the generated LALR(1) parser…'
complete -c yacc -s i -d 'The -i option causes a supplementary header file  y. tab. i to be written'
complete -c yacc -s l -d 'If the  -l option is not specified,  \\*n will insert #line directives in the …'
complete -c yacc -s L -d 'enable position processing, e. g'
complete -c yacc -s o -d 'specify the filename for the parser file'
complete -c yacc -s p -d 'The  -p option changes the prefix prepended to yacc-generated symbols to the …'
complete -c yacc -s P -d 'create a reentrant parser, e. g. , \\*(``%pure-parser\\*(\'\''
complete -c yacc -s r -d 'The  -r option causes  \\*n to produce separate files for code and tables'
complete -c yacc -s s -d 'suppress \\*(``#define\\*(\'\' statements generated for string literals in a \\*(`…'
complete -c yacc -s t -d 'The  -t option changes the preprocessor directives generated by  \\*n so that …'
complete -c yacc -s v -d 'The  -v option causes a human-readable description of the generated parser to…'
complete -c yacc -s V -d 'print the version number to the standard output'
complete -c yacc -s b -d The
complete -c yacc -s y -d 'yaccwhich bison supports for ostensible POSIX compatibility'

