# yp_mkdb
# Autogenerated from man page /usr/share/man/man8/yp_mkdb.8.gz
complete -c yp_mkdb -s c -d 'Cause yp_mkdb to send a YPPROC_CLEAR request to ypserv 8 on the local host'
complete -c yp_mkdb -s b -d 'Cause yp_mkdb to add a special entry to the database with a key of YP_INTERDO…'
complete -c yp_mkdb -s s -d 'This flag is used to add a special entry to the database with a key of YP_SEC…'
complete -c yp_mkdb -s f -d 'This flag is used to turn on filtering of lines in the source file input that…'
complete -c yp_mkdb -s u -d 'Dump (or \'unwind\') an NIS database'
complete -c yp_mkdb -s i -d 'When generating an NIS map, encode inputfile as a special entry in the databa…'
complete -c yp_mkdb -s o -d 'When generating an NIS map, encode outputfile as a special entry in the datab…'
complete -c yp_mkdb -s d -d 'When generating an NIS map, encode domainname as a special entry in the datab…'
complete -c yp_mkdb -s m -d 'When generating an NIS map, encode mastername as a special entry in the datab…'

