# ypbind
# Autogenerated from man page /usr/share/man/man8/ypbind.8.gz
complete -c ypbind -o ypset -d 'It is possible to force ypbind to bind to a particular NIS server host for a …'
complete -c ypbind -o ypsetme -d 'This is similar to the ypset flag, except that it only permits YPBINDPROC_SET…'
complete -c ypbind -s s -d 'Cause ypbind to run in secure mode: it will refuse to bind to any NIS server …'
complete -c ypbind -s S -d 'off domainname , server1 , server2 , server3 , '
complete -c ypbind -s m -d 'Cause ypbind to use a \'many-cast\' rather than a broadcast for choosing a serv…'

