# ypcat
# Autogenerated from man page /usr/share/man/man1/ypcat.1.gz
complete -c ypcat -s d -d 'Specify a domain other than the default domain'
complete -c ypcat -s k -d 'Display map keys'
complete -c ypcat -s t -d 'Inhibit translation of map nicknames to their corresponding map names'
complete -c ypcat -s x -d 'Display the map nickname table'

