# ypchpass
# Autogenerated from man page /usr/share/man/man1/ypchpass.1.gz
complete -c ypchpass -s a -d 'The super-user is allowed to directly supply a user database entry, in the fo…'
complete -c ypchpass -s e -d 'Change the account expire time'
complete -c ypchpass -s p -d 'The super-user is allowed to directly supply an encrypted password field, in …'
complete -c ypchpass -s s -d 'Attempt to change the user\'s shell to newshell'
complete -c ypchpass -s d -d 'Specify a particular NIS domain'
complete -c ypchpass -s h -d 'Specify the name or address of an NIS server to query'
complete -c ypchpass -s l -d 'Force ypchpass to modify the local copy of a user\'s password information in t…'
complete -c ypchpass -s o -d 'Force the use of RPC-based updates when communicating with rpc'
complete -c ypchpass -s y -d 'Opposite effect of l'

