# ypchsh
# Autogenerated from man page /usr/share/man/man1/ypchsh.1.gz
complete -c ypchsh -s a -d 'The super-user is allowed to directly supply a user database entry, in the fo…'
complete -c ypchsh -s e -d 'Change the account expire time'
complete -c ypchsh -s p -d 'The super-user is allowed to directly supply an encrypted password field, in …'
complete -c ypchsh -s s -d 'Attempt to change the user\'s shell to newshell'
complete -c ypchsh -s d -d 'Specify a particular NIS domain'
complete -c ypchsh -s h -d 'Specify the name or address of an NIS server to query'
complete -c ypchsh -s l -d 'Force ypchsh to modify the local copy of a user\'s password information in the…'
complete -c ypchsh -s o -d 'Force the use of RPC-based updates when communicating with rpc'
complete -c ypchsh -s y -d 'Opposite effect of l'

