# ypmatch
# Autogenerated from man page /usr/share/man/man1/ypmatch.1.gz
complete -c ypmatch -s d -d 'Specify a domain other than the default domain'
complete -c ypmatch -s k -d 'Display map keys'
complete -c ypmatch -s t -d 'Inhibit translation of map nicknames to their corresponding map names'
complete -c ypmatch -s x -d 'Display the map nickname table'

