# yppoll
# Autogenerated from man page /usr/share/man/man8/yppoll.8.gz
complete -c yppoll -s d -d 'Use the NIS domain domain instead of the default domain as returned by domain…'
complete -c yppoll -s h -d 'Ask the NIS server process running on host for information about mapname'

