# yppush
# Autogenerated from man page /usr/share/man/man8/yppush.8.gz
complete -c yppush -s d -d 'Specify a particular domain'
complete -c yppush -s t -d 'Specify a timeout value in seconds'
complete -c yppush -s j -d 'The yppush utility normally performs transfers serially, meaning that it will…'
complete -c yppush -s h -d 'Can be used to transfer a map to a user-specified machine or group of machine…'
complete -c yppush -s p -d 'By default, yppush expects all the local NIS maps to be stored under /var/yp'
complete -c yppush -s v -d 'Verbose mode: it causes yppush to print debugging messages as it runs'

