# ypset
# Autogenerated from man page /usr/share/man/man8/ypset.8.gz
complete -c ypset -s d -d 'Use the NIS domain domain instead of the default domain as returned by domain…'
complete -c ypset -s h -d 'Set the NIS binding on host instead of the local machine'

