# ypserv
# Autogenerated from man page /usr/share/man/man8/ypserv.8.gz
complete -c ypserv -s n -d 'This option affects the way ypserv handles yp_match requests for the hosts'
complete -c ypserv -s d -d 'Cause the server to run in debugging mode'
complete -c ypserv -s h -d 'Specify a specific address to bind to for requests'
complete -c ypserv -s P -d 'Force ypserv to bind to a specific TCP/UDP port, rather than selecting its own'
complete -c ypserv -s p -d 'Normally, ypserv assumes that all NIS maps are stored under /var/yp'

