# ypwhich
# Autogenerated from man page /usr/share/man/man1/ypwhich.1.gz
complete -c ypwhich -s d -d 'Specify a domain other than the default domain'
complete -c ypwhich -s t -d 'Inhibit translation of map nicknames to their corresponding map names'
complete -c ypwhich -s m -d 'Find the master NIS server for the named map'
complete -c ypwhich -s x -d 'Display the map nickname table'

