# zcat
# Autogenerated from man page /usr/share/man/man1/zcat.1.gz
complete -c zcat -s 1
complete -c zcat -s 2
complete -c zcat -s 9 -d 'These options change the compression level used, with the 1 option being the …'
complete -c zcat -s c -d 'This option specifies that output will go to the standard output stream, leav…'
complete -c zcat -s d -d 'This option selects decompression rather than compression'
complete -c zcat -s f -d 'This option turns on force mode'
complete -c zcat -s h -d 'This option prints a usage summary and exits'
complete -c zcat -s k -d 'This option prevents zcat from deleting input files after (de)compression'
complete -c zcat -s L -d 'This option prints zcat license'
complete -c zcat -s l -d 'This option displays information about the file\'s compressed and uncompressed…'
complete -c zcat -s N -d 'This option causes the stored filename in the input file to be used as the ou…'
complete -c zcat -s n -d 'This option stops the filename and timestamp from being stored in the output …'
complete -c zcat -s q -d 'With this option, no warnings or errors are printed'
complete -c zcat -s r -d 'This option is used to zcat the files in a directory tree individually, using…'
complete -c zcat -s S -d 'This option changes the default suffix from . gz to suffix'
complete -c zcat -s t -d 'This option will test compressed files for integrity'
complete -c zcat -s V -d 'This option prints the version of the zcat program'
complete -c zcat -s v -d 'This option turns on verbose mode, which prints the compression ratio for eac…'

