# zdump
# Autogenerated from man page /usr/share/man/man8/zdump.8.gz
complete -c zdump -l version -d 'Output version information and exit'
complete -c zdump -l help -d 'Output short usage message and exit'
complete -c zdump -s i -d 'Output a description of time intervals'
complete -c zdump -s v -d 'Output a verbose description of time intervals'
complete -c zdump -s V -d 'Like v, except omit output concerning extreme time and year values'
complete -c zdump -s c -d 'Cut off interval output at the given year(s)'
complete -c zdump -s t -d 'Cut off interval output at the given time(s), given in decimal seconds since …'

