# zfs-upgrade
# Autogenerated from man page /usr/share/man/man8/zfs-upgrade.8.gz
complete -c zfs-upgrade -s V -d 'Upgrade to version.  If not specified, upgrade to the most recent version'
complete -c zfs-upgrade -s a -d 'Upgrade all file systems on all imported pools'
complete -c zfs-upgrade -s r -d 'Upgrade the specified file system and all descendent file systems'

