# zfs-destroy
# Autogenerated from man page /usr/share/man/man8/zfs-destroy.8.gz
complete -c zfs-destroy -s R -d 'Recursively destroy all dependents, including cloned file systems outside the…'
complete -c zfs-destroy -s f -d 'Forcibly unmount file systems'
complete -c zfs-destroy -s n -d 'Do a dry-run No-op deletion.  No data will be deleted'
complete -c zfs-destroy -s p -d 'Print machine-parsable verbose information about the deleted data'
complete -c zfs-destroy -s r -d 'Recursively destroy all children'
complete -c zfs-destroy -s v -d 'Print verbose information about the deleted data'
complete -c zfs-destroy -s d -d 'Destroy immediately'

