# zfs-snapshot
# Autogenerated from man page /usr/share/man/man8/zfs-snapshot.8.gz
complete -c zfs-snapshot -s o -d 'Set the specified property; see zfs-snapshot zfs Cm create for details'
complete -c zfs-snapshot -s r -d 'Recursively create snapshots of all descendent datasets El EXAMPLES Example 1…'

