# zfs-set
# Autogenerated from man page /usr/share/man/man8/zfs-set.8.gz
complete -c zfs-set -s u -d 'Update mountpoint, sharenfs, sharesmb property but do not mount or share the …'
complete -c zfs-set -s H -d 'Display output in a form more easily parsed by scripts'
complete -c zfs-set -s d -d 'Recursively display any children of the dataset, limiting the recursion to de…'
complete -c zfs-set -s o -d 'A comma-separated list of columns to display, defaults to name , Ns Sy proper…'
complete -c zfs-set -s p -d 'Display numbers in parsable exact values'
complete -c zfs-set -s r -d 'Recursively display properties for any children'
complete -c zfs-set -s s -d 'A comma-separated list of sources to display'
complete -c zfs-set -s t -d 'A comma-separated list of types to display, where type is one of filesystem ,…'
complete -c zfs-set -s S -d 'Revert the property to the received value, if one exists; otherwise, for non-…'

