# zfs-rename
# Autogenerated from man page /usr/share/man/man8/zfs-rename.8.gz
complete -c zfs-rename -s f -d 'Force unmount any file systems that need to be unmounted in the process'
complete -c zfs-rename -s p -d 'Creates all the nonexistent parent datasets'
complete -c zfs-rename -s u -d 'Do not remount file systems during rename'

