# zfs-share
# Autogenerated from man page /usr/share/man/man8/zfs-share.8.gz
complete -c zfs-share -s l -d 'Load keys for encrypted filesystems as they are being mounted'
complete -c zfs-share -s a -d 'Share all available ZFS file systems'

