# zfs-allow
# Autogenerated from man page /usr/share/man/man8/zfs-allow.8.gz
complete -c zfs-allow -s d -d 'Allow only for the descendent file systems'
complete -c zfs-allow -s e -d 'Specifies that the permissions be delegated to everyone'
complete -c zfs-allow -s g -d 'Explicitly specify that permissions are delegated to the group'
complete -c zfs-allow -s l -d 'Allow locally only for the specified file system'
complete -c zfs-allow -s u -d 'Explicitly specify that permissions are delegated to the user'
complete -c zfs-allow -s r -d 'Recursively remove the permissions from this file system and all descendents'

