# zfs-change-key
# Autogenerated from man page /usr/share/man/man8/zfs-change-key.8.gz
complete -c zfs-change-key -s r -d 'Recursively loads the keys for the specified filesystem and all descendent en…'
complete -c zfs-change-key -s a -d 'Loads the keys for all encryption roots in all imported pools'
complete -c zfs-change-key -s n -d 'Do a dry-run No-op load-key'
complete -c zfs-change-key -s L -d 'Use keylocation instead of the keylocation property'
complete -c zfs-change-key -s l -d 'Ensures the key is loaded before attempting to change the key'
complete -c zfs-change-key -s o -d 'Allows the user to set encryption key properties keyformat , keylocation , No…'
complete -c zfs-change-key -s i -d 'Indicates that zfs should make filesystem inherit the key of its parent'

