# zfs-project
# Autogenerated from man page /usr/share/man/man8/zfs-project.8.gz
complete -c zfs-project -s d -d 'Show the directory project ID and inherit flag, not its children'
complete -c zfs-project -s r -d 'List subdirectories recursively'
complete -c zfs-project -s k -d 'Keep the project ID unchanged'
complete -c zfs-project -s 0 -d 'Delimit filenames with a NUL byte instead of newline, don\'t output diagnoses'
complete -c zfs-project -s p -d 'Compare to id instead of the target files and directories\' project IDs'
complete -c zfs-project -s s -d 'Set project inherit flag on the given files and directories'

