# zfs-diff
# Autogenerated from man page /usr/share/man/man8/zfs-diff.8.gz
complete -c zfs-diff -s F -d 'Display an indication of the type of file, in a manner similar to the F optio…'
complete -c zfs-diff -s H -d 'Give more parsable tab-separated output, without header lines and without arr…'
complete -c zfs-diff -s t -d 'Display the path\'s inode change time as the first column of output'
complete -c zfs-diff -s h -d 'Do not \\e0 Ns Ar ooo Ns -escape non-ASCII paths'

