# zfs-receive
# Autogenerated from man page /usr/share/man/man8/zfs-receive.8.gz
complete -c zfs-receive -s F -d 'Force a rollback of the file system to the most recent snapshot before perfor…'
complete -c zfs-receive -s d -d 'Discard the first element of the sent snapshot\'s file system name, using the …'
complete -c zfs-receive -s e -d 'Discard all but the last element of the sent snapshot\'s file system name, usi…'
complete -c zfs-receive -s h -d 'Skip the receive of holds.  There is no effect if holds are not sent'
complete -c zfs-receive -s M -d 'Force an unmount of the file system while receiving a snapshot'
complete -c zfs-receive -s n -d 'Do not actually receive the stream'
complete -c zfs-receive -s o -d 'Forces the stream to be received as a clone of the given snapshot'
complete -c zfs-receive -s s -d 'If the receive is interrupted, save the partially received state, rather than…'
complete -c zfs-receive -s u -d 'File system that is associated with the received stream is not mounted'
complete -c zfs-receive -s v -d 'Print verbose information about the stream and the time required to perform t…'
complete -c zfs-receive -s x -d 'Ensures that the effective value of the specified property after the receive …'

