# zfs-hold
# Autogenerated from man page /usr/share/man/man8/zfs-hold.8.gz
complete -c zfs-hold -s r -d 'Specifies that a hold with the given tag is applied recursively to the snapsh…'
complete -c zfs-hold -s H -d 'Do not print headers, use tab-delimited output'
complete -c zfs-hold -s p -d 'Prints holds timestamps as unix epoch timestamps'

