# zfs-clone
# Autogenerated from man page /usr/share/man/man8/zfs-clone.8.gz
complete -c zfs-clone -s o -d 'Sets the specified property; see zfs-clone zfs Cm create for details'
complete -c zfs-clone -s p -d 'Creates all the non-existing parent datasets'

