# zfs-userspace
# Autogenerated from man page /usr/share/man/man8/zfs-userspace.8.gz
complete -c zfs-userspace -s H -d 'Do not print headers, use tab-delimited output'
complete -c zfs-userspace -s S -d 'Sort by this field in reverse order.  See s'
complete -c zfs-userspace -s i -d 'Translate SID to POSIX ID'
complete -c zfs-userspace -s n -d 'Print numeric ID instead of user/group name'
complete -c zfs-userspace -s o -d 'Display only the specified fields from the following set: type, name, used, q…'
complete -c zfs-userspace -s p -d 'Use exact parsable numeric output'
complete -c zfs-userspace -s s -d 'Sort output by this field'
complete -c zfs-userspace -s t -d 'Print only the specified types from the following set: all, posixuser, smbuse…'

