# zfs-rollback
# Autogenerated from man page /usr/share/man/man8/zfs-rollback.8.gz
complete -c zfs-rollback -s R -d 'Destroy any more recent snapshots and bookmarks, as well as any clones of tho…'
complete -c zfs-rollback -s f -d 'Used with the R option to force an unmount of any clone file systems that are…'
complete -c zfs-rollback -s r -d 'Destroy any snapshots and bookmarks more recent than the one specified'

