# zfs-create
# Autogenerated from man page /usr/share/man/man8/zfs-create.8.gz
complete -c zfs-create -s o -d 'Sets the specified property as if the command zfs-create zfs Cm set Ar proper…'
complete -c zfs-create -s p -d 'Creates all the non-existing parent datasets'
complete -c zfs-create -s n -d 'Do a dry-run No-op creation.  No datasets will be created'
complete -c zfs-create -s P -d 'Print machine-parsable verbose information about the created dataset'
complete -c zfs-create -s u -d 'Do not mount the newly created file system'
complete -c zfs-create -s v -d 'Print verbose information about the created dataset'
complete -c zfs-create -s b -d 'Equivalent to o Sy volblocksize Ns = Ns Ar blocksize'
complete -c zfs-create -s s -d 'Creates a sparse volume with no reservation'

