# zfsbootcfg
# Autogenerated from man page /usr/share/man/man8/zfsbootcfg.8.gz
complete -c zfsbootcfg -s k -d 'Define key for key , value Ac pair'
complete -c zfsbootcfg -s n -d 'Update nvlist name'
complete -c zfsbootcfg -s p -d 'Print all information stored in ZFS pool bootenv area'
complete -c zfsbootcfg -s t -d 'Set type of value used in key , value Ac pair'
complete -c zfsbootcfg -s v -d 'Define value for key , value Ac pair'
complete -c zfsbootcfg -s z -d 'Operate on pool.  El ENVIRONMENT -tag -width vfs. root'

