# zic
# Autogenerated from man page /usr/share/man/man8/zic.8.gz
complete -c zic -l version -d 'Output version information and exit'
complete -c zic -l help -d 'Output short usage message and exit'
complete -c zic -s b -d 'Output backward-compatibility data as specified by bloat'
complete -c zic -s D -d 'Do not create directories'
complete -c zic -s d -d 'Create time conversion information files in the named directory rather than i…'
complete -c zic -s l -d 'Use timezone as local time'
complete -c zic -s L -d 'Read leap second information from the file with the given name'
complete -c zic -s p -d 'Use timezone \'s rules when handling nonstandard TZ strings like "EET\\-2EEST" …'
complete -c zic -s r -d 'Limit the applicability of output files to timestamps in the range from lo (i…'
complete -c zic -s R -d 'Generate redundant trailing explicit transitions for timestamps that occur le…'
complete -c zic -s t -d 'When creating local time information, put the configuration link in the named…'
complete -c zic -s v -d 'Be more verbose, and complain about the following situations: -bullet It The …'

