# znew
# Autogenerated from man page /usr/share/man/man1/znew.1.gz
complete -c znew -s f -d 'Overwrite existing . gz files'
complete -c znew -s t -d 'Test integrity of the gzipped file before deleting the original file'
complete -c znew -s v -d 'Print a report specifying the achieved compression ratios'
complete -c znew -s 9 -d 'Use the -9 mode of gzip 1, achieving better compression at the cost of slower…'
complete -c znew -s K -d 'Keep the original . Z file if it uses less disk blocks than the gzipped one'

