# zonectl
# Autogenerated from man page /usr/share/man/man8/zonectl.8.gz
complete -c zonectl -s c -d 'Specify the zone subcommand: -tag -width 6n params Display device parameters,…'
complete -c zonectl -s a -d 'For the Open, Close, Finish, and Reset Write Pointer operations, apply the op…'
complete -c zonectl -s l -d 'Specify the starting LBA'
complete -c zonectl -s o -d 'For the Report Zones command, specify a subset of zones to report'
complete -c zonectl -s P -d 'Specify a printing option for Report Zones: -tag -width 7n normal Normal Repo…'

