# zpool-checkpoint
# Autogenerated from man page /usr/share/man/man8/zpool-checkpoint.8.gz
complete -c zpool-checkpoint -s d -d 'Discards an existing checkpoint from pool'
complete -c zpool-checkpoint -s w -d 'Waits until the checkpoint has finished being discarded before returning'

