# zpool-history
# Autogenerated from man page /usr/share/man/man8/zpool-history.8.gz
complete -c zpool-history -s i -d 'Displays internally logged ZFS events in addition to user initiated events'
complete -c zpool-history -s l -d 'Displays log records in long format, which in addition to standard format inc…'

