# zpool-status
# Autogenerated from man page /usr/share/man/man8/zpool-status.8.gz
complete -c zpool-status -s c -d 'Run a script (or scripts) on each vdev and include the output as a new column…'
complete -c zpool-status -s i -d 'Display vdev initialization status'
complete -c zpool-status -s g -d 'Display vdev GUIDs instead of the normal device names These GUIDs can be used…'
complete -c zpool-status -s L -d 'Display real paths for vdevs resolving all symbolic links'
complete -c zpool-status -s p -d 'Display numbers in parsable (exact) values'
complete -c zpool-status -s P -d 'Display full paths for vdevs instead of only the last component of the path'
complete -c zpool-status -s D -d 'Display a histogram of deduplication statistics, showing the allocated physic…'
complete -c zpool-status -s s -d 'Display the number of leaf vdev slow I/O operations'
complete -c zpool-status -s t -d 'Display vdev TRIM status'
complete -c zpool-status -s T -d 'Display a time stamp'
complete -c zpool-status -s v -d 'Displays verbose data error information, printing out a complete list of all …'
complete -c zpool-status -s x -d 'Only display status for pools that are exhibiting errors or are otherwise una…'

