# zpool-wait
# Autogenerated from man page /usr/share/man/man8/zpool-wait.8.gz
complete -c zpool-wait -s H -d 'Scripted mode'
complete -c zpool-wait -s p -d 'Display numbers in parsable (exact) values'
complete -c zpool-wait -s T -d 'Display a time stamp'

