# zpool-trim
# Autogenerated from man page /usr/share/man/man8/zpool-trim.8.gz
complete -c zpool-trim -s d -d 'Causes a secure TRIM to be initiated'
complete -c zpool-trim -s r -d 'Controls the rate at which the TRIM operation progresses'
complete -c zpool-trim -s c -d 'Cancel trimming on the specified devices, or all eligible devices if none are…'
complete -c zpool-trim -s s -d 'Suspend trimming on the specified devices, or all eligible devices if none ar…'
complete -c zpool-trim -s w -d 'Wait until the devices are done being trimmed before returning'

