# zpool-list
# Autogenerated from man page /usr/share/man/man8/zpool-list.8.gz
complete -c zpool-list -s g -d 'Display vdev GUIDs instead of the normal device names'
complete -c zpool-list -s H -d 'Scripted mode'
complete -c zpool-list -s o -d 'Comma-separated list of properties to display'
complete -c zpool-list -s L -d 'Display real paths for vdevs resolving all symbolic links'
complete -c zpool-list -s p -d 'Display numbers in parsable exact values'
complete -c zpool-list -s P -d 'Display full paths for vdevs instead of only the last component of the path'
complete -c zpool-list -s T -d 'Display a time stamp'
complete -c zpool-list -s v -d 'Verbose statistics'

