# zpool-get
# Autogenerated from man page /usr/share/man/man8/zpool-get.8.gz
complete -c zpool-get -s H -d 'Scripted mode'
complete -c zpool-get -s o -d 'A comma-separated list of columns to display, defaults to name , Ns Sy proper…'
complete -c zpool-get -s p -d 'Display numbers in parsable (exact) values'

