# zpool-upgrade
# Autogenerated from man page /usr/share/man/man8/zpool-upgrade.8.gz
complete -c zpool-upgrade -s a -d 'Enables all supported features (from specified compatibility sets, if any) on…'
complete -c zpool-upgrade -s V -d 'Upgrade to the specified legacy version'

