# zpool-events
# Autogenerated from man page /usr/share/man/man8/zpool-events.8.gz
complete -c zpool-events -s c -d 'Clear all previous events'
complete -c zpool-events -s f -d 'Follow mode'
complete -c zpool-events -s H -d 'Scripted mode'
complete -c zpool-events -s v -d 'Print the entire payload for each event'

