# zpool-scrub
# Autogenerated from man page /usr/share/man/man8/zpool-scrub.8.gz
complete -c zpool-scrub -s s -d 'Stop scrubbing'
complete -c zpool-scrub -s p -d 'Pause scrubbing'
complete -c zpool-scrub -s w -d 'Wait until scrub has completed before returning'
complete -c zpool-scrub -s e -d 'Only scrub files with known data errors as reported by zpool-scrub zpool Cm s…'

