# zpool-split
# Autogenerated from man page /usr/share/man/man8/zpool-split.8.gz
complete -c zpool-split -s g -d 'Display vdev GUIDs instead of the normal device names'
complete -c zpool-split -s L -d 'Display real paths for vdevs resolving all symbolic links'
complete -c zpool-split -s l -d 'Indicates that this command will request encryption keys for all encrypted da…'
complete -c zpool-split -s n -d 'Do a dry-run No-op split: do not actually perform it'
complete -c zpool-split -s P -d 'Display full paths for vdevs instead of only the last component of the path'
complete -c zpool-split -s o -d 'Sets the specified property for newpool'
complete -c zpool-split -s R -d 'Set altroot for newpool to root and automatically import it'

