# zpool-add
# Autogenerated from man page /usr/share/man/man8/zpool-add.8.gz
complete -c zpool-add -s f -d 'Forces use of vdev Ns s, even if they appear in use or specify a conflicting …'
complete -c zpool-add -s g -d 'Display vdev, GUIDs instead of the normal device names'
complete -c zpool-add -s L -d 'Display real paths for vdev Ns s resolving all symbolic links'
complete -c zpool-add -s n -d 'Displays the configuration that would be used without actually adding the vde…'
complete -c zpool-add -s P -d 'Display real paths for vdev Ns s instead of only the last component of the pa…'
complete -c zpool-add -s o -d 'Sets the given pool properties'

