# zpool-replace
# Autogenerated from man page /usr/share/man/man8/zpool-replace.8.gz
complete -c zpool-replace -s f -d 'Forces use of new-device, even if it appears to be in use'
complete -c zpool-replace -s o -d 'Sets the given pool properties'
complete -c zpool-replace -s s -d 'The new-device is reconstructed sequentially to restore redundancy as quickly…'
complete -c zpool-replace -s w -d 'Waits until the replacement has completed before returning'

