# zpool-iostat
# Autogenerated from man page /usr/share/man/man8/zpool-iostat.8.gz
complete -c zpool-iostat -s c -d 'Run a script (or scripts) on each vdev and include the output as a new column…'
complete -c zpool-iostat -s T -d 'Display a time stamp'
complete -c zpool-iostat -s g -d 'Display vdev GUIDs instead of the normal device names'
complete -c zpool-iostat -s H -d 'Scripted mode'
complete -c zpool-iostat -s L -d 'Display real paths for vdevs resolving all symbolic links'
complete -c zpool-iostat -s n -d 'Print headers only once when passed'
complete -c zpool-iostat -s p -d 'Display numbers in parsable (exact) values.  Time values are in nanoseconds'
complete -c zpool-iostat -s P -d 'Display full paths for vdevs instead of only the last component of the path'
complete -c zpool-iostat -s r -d 'Print request size histograms for the leaf vdev\'s I/O'
complete -c zpool-iostat -s v -d 'Verbose statistics Reports usage statistics for individual vdevs within the p…'
complete -c zpool-iostat -s y -d 'Normally the first line of output reports the statistics since boot: suppress…'
complete -c zpool-iostat -s w -d 'Display latency histograms: -tag -compact -width "asyncq_read/write" total_wa…'
complete -c zpool-iostat -s l -d 'Include average latency statistics: -tag -compact -width "asyncq_read/write" …'
complete -c zpool-iostat -s q -d 'Include active queue statistics'

