# zpool-export
# Autogenerated from man page /usr/share/man/man8/zpool-export.8.gz
complete -c zpool-export -s a -d 'Exports all pools imported on the system'
complete -c zpool-export -s f -d 'Forcefully unmount all datasets, and allow export of pools with active shared…'

