# zpool-initialize
# Autogenerated from man page /usr/share/man/man8/zpool-initialize.8.gz
complete -c zpool-initialize -s c -d 'Cancel initializing on the specified devices, or all eligible devices if none…'
complete -c zpool-initialize -s s -d 'Suspend initializing on the specified devices, or all eligible devices if non…'
complete -c zpool-initialize -s u -d 'Clears the initialization state on the specified devices, or all eligible dev…'
complete -c zpool-initialize -s w -d 'Wait until the devices have finished initializing before returning'

