# zpool-set
# Autogenerated from man page /usr/share/man/man8/zpool-set.8.gz
complete -c zpool-set -s H -d 'Scripted mode'
complete -c zpool-set -s o -d 'A comma-separated list of columns to display, defaults to name , Ns Sy proper…'
complete -c zpool-set -s p -d 'Display numbers in parsable (exact) values'

