# zstdcat
# Autogenerated from man page /usr/share/man/man1/zstdcat.1.gz
complete -c zstdcat -s '#'
complete -c zstdcat -l ultra
complete -c zstdcat -l fast -l fast
complete -c zstdcat -o 'T#' -l threads
complete -c zstdcat -l single-thread -o T1 -o T1
complete -c zstdcat -l auto-threads -o T0
complete -c zstdcat -l adapt -s v -l long -l adapt
complete -c zstdcat -s D
complete -c zstdcat -l patch-from
complete -c zstdcat -l rsyncable
complete -c zstdcat -s C -l check
complete -c zstdcat -l content-size -l content-size
complete -c zstdcat -l no-dictID
complete -c zstdcat -o 'M#' -l memory
complete -c zstdcat -l stream-size
complete -c zstdcat -l size-hint
complete -c zstdcat -s o
complete -c zstdcat -s f -l force
complete -c zstdcat -s c -l stdout
complete -c zstdcat -l sparse
complete -c zstdcat -l rm
complete -c zstdcat -s k -l keep
complete -c zstdcat -s r
complete -c zstdcat -l filelist
complete -c zstdcat -l output-dir-flat
complete -c zstdcat -l output-dir-mirror
complete -c zstdcat -l format
complete -c zstdcat -o h/-H -l help
complete -c zstdcat -s V -l version -o vV -o vvV -s q
complete -c zstdcat -l verbose
complete -c zstdcat -l quiet
complete -c zstdcat -l no-progress
complete -c zstdcat -l show-default-cparams
complete -c zstdcat -l train-fastcover -l train-legacy -l train-cover -l train-fastcover
complete -c zstdcat -l maxdict -d 'Limit dictionary to specified size (default: 112640)'
complete -c zstdcat -o 'B#' -d 'Split input files into blocks of size # (default: no split)'
complete -c zstdcat -l dictID -d 'A dictionary ID is a locally unique ID that a decoder can use to verify it is…'
complete -c zstdcat -o 'e#' -d 'benchmark file(s) using multiple compression levels, from -b# to -e# (inclusi…'
complete -c zstdcat -o 'i#' -d 'minimum evaluation time, in seconds (default: 3s), benchmark mode only'
complete -c zstdcat -l block-size -d 'cut file(s) into independent blocks of size # (default: no block)'
complete -c zstdcat -l priority -d 'set process priority to real-time Output Format: CompressionLevel#Filename : …'
complete -c zstdcat -l zstd -d 'zstd provides 22 predefined compression levels'

