# zstdmt
# Autogenerated from man page /usr/share/man/man1/zstdmt.1.gz
complete -c zstdmt -s '#'
complete -c zstdmt -l ultra
complete -c zstdmt -l fast -l fast
complete -c zstdmt -o 'T#' -l threads
complete -c zstdmt -l single-thread -o T1 -o T1
complete -c zstdmt -l auto-threads -o T0
complete -c zstdmt -l adapt -s v -l long -l adapt
complete -c zstdmt -s D
complete -c zstdmt -l patch-from
complete -c zstdmt -l rsyncable
complete -c zstdmt -s C -l check
complete -c zstdmt -l content-size -l content-size
complete -c zstdmt -l no-dictID
complete -c zstdmt -o 'M#' -l memory
complete -c zstdmt -l stream-size
complete -c zstdmt -l size-hint
complete -c zstdmt -s o
complete -c zstdmt -s f -l force
complete -c zstdmt -s c -l stdout
complete -c zstdmt -l sparse
complete -c zstdmt -l rm
complete -c zstdmt -s k -l keep
complete -c zstdmt -s r
complete -c zstdmt -l filelist
complete -c zstdmt -l output-dir-flat
complete -c zstdmt -l output-dir-mirror
complete -c zstdmt -l format
complete -c zstdmt -o h/-H -l help
complete -c zstdmt -s V -l version -o vV -o vvV -s q
complete -c zstdmt -l verbose
complete -c zstdmt -l quiet
complete -c zstdmt -l no-progress
complete -c zstdmt -l show-default-cparams
complete -c zstdmt -l train-fastcover -l train-legacy -l train-cover -l train-fastcover
complete -c zstdmt -l maxdict -d 'Limit dictionary to specified size (default: 112640)'
complete -c zstdmt -o 'B#' -d 'Split input files into blocks of size # (default: no split)'
complete -c zstdmt -l dictID -d 'A dictionary ID is a locally unique ID that a decoder can use to verify it is…'
complete -c zstdmt -o 'e#' -d 'benchmark file(s) using multiple compression levels, from -b# to -e# (inclusi…'
complete -c zstdmt -o 'i#' -d 'minimum evaluation time, in seconds (default: 3s), benchmark mode only'
complete -c zstdmt -l block-size -d 'cut file(s) into independent blocks of size # (default: no block)'
complete -c zstdmt -l priority -d 'set process priority to real-time Output Format: CompressionLevel#Filename : …'
complete -c zstdmt -l zstd -d 'zstd provides 22 predefined compression levels'

