# zstreamdump
# Autogenerated from man page /usr/share/man/man8/zstreamdump.8.gz
complete -c zstreamdump -s C -d 'Suppress the validation of checksums'
complete -c zstreamdump -s v -d 'Verbose.  Print metadata for each record'
complete -c zstreamdump -s d -d 'Dump data contained in each record.  Implies verbose'
complete -c zstreamdump -s l -d 'Specifies compression level'

