# zstream
# Autogenerated from man page /usr/share/man/man8/zstream.8.gz
complete -c zstream -s C -d 'Suppress the validation of checksums'
complete -c zstream -s v -d 'Verbose.  Print metadata for each record'
complete -c zstream -s d -d 'Dump data contained in each record.  Implies verbose'
complete -c zstream -s l -d 'Specifies compression level'

